; Hc/NtAddAtomEx
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciAddAtomEx:DWORD

.DATA
.CODE

HcAddAtomEx PROC
	mov r10, rcx
	mov eax, sciAddAtomEx
	syscall
	ret
HcAddAtomEx ENDP

ELSE
; 32bit

EXTERNDEF C sciAddAtomEx:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcAddAtomEx PROC
	mov eax, sciAddAtomEx
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcAddAtomEx ENDP

ENDIF

END