; Hc/NtAddBootEntry
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciAddBootEntry:DWORD

.DATA
.CODE

HcAddBootEntry PROC
	mov r10, rcx
	mov eax, sciAddBootEntry
	syscall
	ret
HcAddBootEntry ENDP

ELSE
; 32bit

EXTERNDEF C sciAddBootEntry:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcAddBootEntry PROC
	mov eax, sciAddBootEntry
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcAddBootEntry ENDP

ENDIF

END