; Hc/NtAllocateLocallyUniqueId
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciAllocateLocallyUniqueId:DWORD

.DATA
.CODE

HcAllocateLocallyUniqueId PROC
	mov r10, rcx
	mov eax, sciAllocateLocallyUniqueId
	syscall
	ret
HcAllocateLocallyUniqueId ENDP

ELSE
; 32bit

EXTERNDEF C sciAllocateLocallyUniqueId:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcAllocateLocallyUniqueId PROC
	mov eax, sciAllocateLocallyUniqueId
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcAllocateLocallyUniqueId ENDP

ENDIF

END