; Hc/NtAllocateReserveObject
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciAllocateReserveObject:DWORD

.DATA
.CODE

HcAllocateReserveObject PROC
	mov r10, rcx
	mov eax, sciAllocateReserveObject
	syscall
	ret
HcAllocateReserveObject ENDP

ELSE
; 32bit

EXTERNDEF C sciAllocateReserveObject:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcAllocateReserveObject PROC
	mov eax, sciAllocateReserveObject
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcAllocateReserveObject ENDP

ENDIF

END