; Hc/NtAllocateUserPhysicalPages
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciAllocateUserPhysicalPages:DWORD

.DATA
.CODE

HcAllocateUserPhysicalPages PROC
	mov r10, rcx
	mov eax, sciAllocateUserPhysicalPages
	syscall
	ret
HcAllocateUserPhysicalPages ENDP

ELSE
; 32bit

EXTERNDEF C sciAllocateUserPhysicalPages:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcAllocateUserPhysicalPages PROC
	mov eax, sciAllocateUserPhysicalPages
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcAllocateUserPhysicalPages ENDP

ENDIF

END