; Hc/NtAlpcCreateSectionView
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciAlpcCreateSectionView:DWORD

.DATA
.CODE

HcAlpcCreateSectionView PROC
	mov r10, rcx
	mov eax, sciAlpcCreateSectionView
	syscall
	ret
HcAlpcCreateSectionView ENDP

ELSE
; 32bit

EXTERNDEF C sciAlpcCreateSectionView:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcAlpcCreateSectionView PROC
	mov eax, sciAlpcCreateSectionView
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcAlpcCreateSectionView ENDP

ENDIF

END