; Hc/NtAlpcConnectPortEx
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciAlpcConnectPortEx:DWORD

.DATA
.CODE

HcAlpcConnectPortEx PROC
	mov r10, rcx
	mov eax, sciAlpcConnectPortEx
	syscall
	ret
HcAlpcConnectPortEx ENDP

ELSE
; 32bit

EXTERNDEF C sciAlpcConnectPortEx:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcAlpcConnectPortEx PROC
	mov eax, sciAlpcConnectPortEx
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcAlpcConnectPortEx ENDP

ENDIF

END