; Hc/NtAlpcOpenSenderProcess
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciAlpcOpenSenderProcess:DWORD

.DATA
.CODE

HcAlpcOpenSenderProcess PROC
	mov r10, rcx
	mov eax, sciAlpcOpenSenderProcess
	syscall
	ret
HcAlpcOpenSenderProcess ENDP

ELSE
; 32bit

EXTERNDEF C sciAlpcOpenSenderProcess:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcAlpcOpenSenderProcess PROC
	mov eax, sciAlpcOpenSenderProcess
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcAlpcOpenSenderProcess ENDP

ENDIF

END