; Hc/NtAlpcOpenSenderThread
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciAlpcOpenSenderThread:DWORD

.DATA
.CODE

HcAlpcOpenSenderThread PROC
	mov r10, rcx
	mov eax, sciAlpcOpenSenderThread
	syscall
	ret
HcAlpcOpenSenderThread ENDP

ELSE
; 32bit

EXTERNDEF C sciAlpcOpenSenderThread:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcAlpcOpenSenderThread PROC
	mov eax, sciAlpcOpenSenderThread
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcAlpcOpenSenderThread ENDP

ENDIF

END