; Hc/NtCancelWaitCompletionPacket
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciCancelWaitCompletionPacket:DWORD

.DATA
.CODE

HcCancelWaitCompletionPacket PROC
	mov r10, rcx
	mov eax, sciCancelWaitCompletionPacket
	syscall
	ret
HcCancelWaitCompletionPacket ENDP

ELSE
; 32bit

EXTERNDEF C sciCancelWaitCompletionPacket:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcCancelWaitCompletionPacket PROC
	mov eax, sciCancelWaitCompletionPacket
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcCancelWaitCompletionPacket ENDP

ENDIF

END