; Hc/NtCommitComplete
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciCommitComplete:DWORD

.DATA
.CODE

HcCommitComplete PROC
	mov r10, rcx
	mov eax, sciCommitComplete
	syscall
	ret
HcCommitComplete ENDP

ELSE
; 32bit

EXTERNDEF C sciCommitComplete:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcCommitComplete PROC
	mov eax, sciCommitComplete
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcCommitComplete ENDP

ENDIF

END