; Hc/NtCompareObjects
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciCompareObjects:DWORD

.DATA
.CODE

HcCompareObjects PROC
	mov r10, rcx
	mov eax, sciCompareObjects
	syscall
	ret
HcCompareObjects ENDP

ELSE
; 32bit

EXTERNDEF C sciCompareObjects:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcCompareObjects PROC
	mov eax, sciCompareObjects
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcCompareObjects ENDP

ENDIF

END