; Hc/NtCreateTimer
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciCreateTimer:DWORD

.DATA
.CODE

HcCreateTimer PROC
	mov r10, rcx
	mov eax, sciCreateTimer
	syscall
	ret
HcCreateTimer ENDP

ELSE
; 32bit

EXTERNDEF C sciCreateTimer:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcCreateTimer PROC
	mov eax, sciCreateTimer
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcCreateTimer ENDP

ENDIF

END