; Hc/NtCreateRegistryTransaction
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciCreateRegistryTransaction:DWORD

.DATA
.CODE

HcCreateRegistryTransaction PROC
	mov r10, rcx
	mov eax, sciCreateRegistryTransaction
	syscall
	ret
HcCreateRegistryTransaction ENDP

ELSE
; 32bit

EXTERNDEF C sciCreateRegistryTransaction:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcCreateRegistryTransaction PROC
	mov eax, sciCreateRegistryTransaction
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcCreateRegistryTransaction ENDP

ENDIF

END