; Hc/NtCreateKeyTransacted
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciCreateKeyTransacted:DWORD

.DATA
.CODE

HcCreateKeyTransacted PROC
	mov r10, rcx
	mov eax, sciCreateKeyTransacted
	syscall
	ret
HcCreateKeyTransacted ENDP

ELSE
; 32bit

EXTERNDEF C sciCreateKeyTransacted:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcCreateKeyTransacted PROC
	mov eax, sciCreateKeyTransacted
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcCreateKeyTransacted ENDP

ENDIF

END