; Hc/NtCreateTokenEx
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciCreateTokenEx:DWORD

.DATA
.CODE

HcCreateTokenEx PROC
	mov r10, rcx
	mov eax, sciCreateTokenEx
	syscall
	ret
HcCreateTokenEx ENDP

ELSE
; 32bit

EXTERNDEF C sciCreateTokenEx:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcCreateTokenEx PROC
	mov eax, sciCreateTokenEx
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcCreateTokenEx ENDP

ENDIF

END