; Hc/NtCreatePort
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciCreatePort:DWORD

.DATA
.CODE

HcCreatePort PROC
	mov r10, rcx
	mov eax, sciCreatePort
	syscall
	ret
HcCreatePort ENDP

ELSE
; 32bit

EXTERNDEF C sciCreatePort:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcCreatePort PROC
	mov eax, sciCreatePort
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcCreatePort ENDP

ENDIF

END