; Hc/NtCreateProfileEx
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciCreateProfileEx:DWORD

.DATA
.CODE

HcCreateProfileEx PROC
	mov r10, rcx
	mov eax, sciCreateProfileEx
	syscall
	ret
HcCreateProfileEx ENDP

ELSE
; 32bit

EXTERNDEF C sciCreateProfileEx:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcCreateProfileEx PROC
	mov eax, sciCreateProfileEx
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcCreateProfileEx ENDP

ENDIF

END