; Hc/NtCreateMutant
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciCreateMutant:DWORD

.DATA
.CODE

HcCreateMutant PROC
	mov r10, rcx
	mov eax, sciCreateMutant
	syscall
	ret
HcCreateMutant ENDP

ELSE
; 32bit

EXTERNDEF C sciCreateMutant:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcCreateMutant PROC
	mov eax, sciCreateMutant
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcCreateMutant ENDP

ENDIF

END