; Hc/NtCreateProcessEx
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciCreateProcessEx:DWORD

.DATA
.CODE

HcCreateProcessEx PROC
	mov r10, rcx
	mov eax, sciCreateProcessEx
	syscall
	ret
HcCreateProcessEx ENDP

ELSE
; 32bit

EXTERNDEF C sciCreateProcessEx:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcCreateProcessEx PROC
	mov eax, sciCreateProcessEx
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcCreateProcessEx ENDP

ENDIF

END