; Hc/NtCreatePartition
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciCreatePartition:DWORD

.DATA
.CODE

HcCreatePartition PROC
	mov r10, rcx
	mov eax, sciCreatePartition
	syscall
	ret
HcCreatePartition ENDP

ELSE
; 32bit

EXTERNDEF C sciCreatePartition:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcCreatePartition PROC
	mov eax, sciCreatePartition
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcCreatePartition ENDP

ENDIF

END