; Hc/NtDebugActiveProcess
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciDebugActiveProcess:DWORD

.DATA
.CODE

HcDebugActiveProcess PROC
	mov r10, rcx
	mov eax, sciDebugActiveProcess
	syscall
	ret
HcDebugActiveProcess ENDP

ELSE
; 32bit

EXTERNDEF C sciDebugActiveProcess:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcDebugActiveProcess PROC
	mov eax, sciDebugActiveProcess
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcDebugActiveProcess ENDP

ENDIF

END