; Hc/NtDeleteKey
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciDeleteKey:DWORD

.DATA
.CODE

HcDeleteKey PROC
	mov r10, rcx
	mov eax, sciDeleteKey
	syscall
	ret
HcDeleteKey ENDP

ELSE
; 32bit

EXTERNDEF C sciDeleteKey:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcDeleteKey PROC
	mov eax, sciDeleteKey
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcDeleteKey ENDP

ENDIF

END