; Hc/NtDeleteFile
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciDeleteFile:DWORD

.DATA
.CODE

HcDeleteFile PROC
	mov r10, rcx
	mov eax, sciDeleteFile
	syscall
	ret
HcDeleteFile ENDP

ELSE
; 32bit

EXTERNDEF C sciDeleteFile:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcDeleteFile PROC
	mov eax, sciDeleteFile
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcDeleteFile ENDP

ENDIF

END