; Hc/NtEnumerateKey
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciEnumerateKey:DWORD

.DATA
.CODE

HcEnumerateKey PROC
	mov r10, rcx
	mov eax, sciEnumerateKey
	syscall
	ret
HcEnumerateKey ENDP

ELSE
; 32bit

EXTERNDEF C sciEnumerateKey:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcEnumerateKey PROC
	mov eax, sciEnumerateKey
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcEnumerateKey ENDP

ENDIF

END