; Hc/NtFlushProcessWriteBuffers
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciFlushProcessWriteBuffers:DWORD

.DATA
.CODE

HcFlushProcessWriteBuffers PROC
	mov r10, rcx
	mov eax, sciFlushProcessWriteBuffers
	syscall
	ret
HcFlushProcessWriteBuffers ENDP

ELSE
; 32bit

EXTERNDEF C sciFlushProcessWriteBuffers:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcFlushProcessWriteBuffers PROC
	mov eax, sciFlushProcessWriteBuffers
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcFlushProcessWriteBuffers ENDP

ENDIF

END