; Hc/NtFlushWriteBuffer
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciFlushWriteBuffer:DWORD

.DATA
.CODE

HcFlushWriteBuffer PROC
	mov r10, rcx
	mov eax, sciFlushWriteBuffer
	syscall
	ret
HcFlushWriteBuffer ENDP

ELSE
; 32bit

EXTERNDEF C sciFlushWriteBuffer:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcFlushWriteBuffer PROC
	mov eax, sciFlushWriteBuffer
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcFlushWriteBuffer ENDP

ENDIF

END