; Hc/NtFreezeTransactions
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciFreezeTransactions:DWORD

.DATA
.CODE

HcFreezeTransactions PROC
	mov r10, rcx
	mov eax, sciFreezeTransactions
	syscall
	ret
HcFreezeTransactions ENDP

ELSE
; 32bit

EXTERNDEF C sciFreezeTransactions:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcFreezeTransactions PROC
	mov eax, sciFreezeTransactions
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcFreezeTransactions ENDP

ENDIF

END