; Hc/NtGetWriteWatch
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGetWriteWatch:DWORD

.DATA
.CODE

HcGetWriteWatch PROC
	mov r10, rcx
	mov eax, sciGetWriteWatch
	syscall
	ret
HcGetWriteWatch ENDP

ELSE
; 32bit

EXTERNDEF C sciGetWriteWatch:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGetWriteWatch PROC
	mov eax, sciGetWriteWatch
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGetWriteWatch ENDP

ENDIF

END