; Hc/NtImpersonateClientOfPort
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciImpersonateClientOfPort:DWORD

.DATA
.CODE

HcImpersonateClientOfPort PROC
	mov r10, rcx
	mov eax, sciImpersonateClientOfPort
	syscall
	ret
HcImpersonateClientOfPort ENDP

ELSE
; 32bit

EXTERNDEF C sciImpersonateClientOfPort:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcImpersonateClientOfPort PROC
	mov eax, sciImpersonateClientOfPort
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcImpersonateClientOfPort ENDP

ENDIF

END