; Hc/NtMapViewOfSection
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciMapViewOfSection:DWORD

.DATA
.CODE

HcMapViewOfSection PROC
	mov r10, rcx
	mov eax, sciMapViewOfSection
	syscall
	ret
HcMapViewOfSection ENDP

ELSE
; 32bit

EXTERNDEF C sciMapViewOfSection:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcMapViewOfSection PROC
	mov eax, sciMapViewOfSection
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcMapViewOfSection ENDP

ENDIF

END