; Hc/NtModifyBootEntry
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciModifyBootEntry:DWORD

.DATA
.CODE

HcModifyBootEntry PROC
	mov r10, rcx
	mov eax, sciModifyBootEntry
	syscall
	ret
HcModifyBootEntry ENDP

ELSE
; 32bit

EXTERNDEF C sciModifyBootEntry:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcModifyBootEntry PROC
	mov eax, sciModifyBootEntry
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcModifyBootEntry ENDP

ENDIF

END