; Hc/NtNotifyChangeDirectoryFile
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciNotifyChangeDirectoryFile:DWORD

.DATA
.CODE

HcNotifyChangeDirectoryFile PROC
	mov r10, rcx
	mov eax, sciNotifyChangeDirectoryFile
	syscall
	ret
HcNotifyChangeDirectoryFile ENDP

ELSE
; 32bit

EXTERNDEF C sciNotifyChangeDirectoryFile:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcNotifyChangeDirectoryFile PROC
	mov eax, sciNotifyChangeDirectoryFile
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcNotifyChangeDirectoryFile ENDP

ENDIF

END