; Hc/NtOpenKeyTransactedEx
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciOpenKeyTransactedEx:DWORD

.DATA
.CODE

HcOpenKeyTransactedEx PROC
	mov r10, rcx
	mov eax, sciOpenKeyTransactedEx
	syscall
	ret
HcOpenKeyTransactedEx ENDP

ELSE
; 32bit

EXTERNDEF C sciOpenKeyTransactedEx:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcOpenKeyTransactedEx PROC
	mov eax, sciOpenKeyTransactedEx
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcOpenKeyTransactedEx ENDP

ENDIF

END