; Hc/NtOpenSymbolicLinkObject
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciOpenSymbolicLinkObject:DWORD

.DATA
.CODE

HcOpenSymbolicLinkObject PROC
	mov r10, rcx
	mov eax, sciOpenSymbolicLinkObject
	syscall
	ret
HcOpenSymbolicLinkObject ENDP

ELSE
; 32bit

EXTERNDEF C sciOpenSymbolicLinkObject:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcOpenSymbolicLinkObject PROC
	mov eax, sciOpenSymbolicLinkObject
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcOpenSymbolicLinkObject ENDP

ENDIF

END