; Hc/NtOpenPartition
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciOpenPartition:DWORD

.DATA
.CODE

HcOpenPartition PROC
	mov r10, rcx
	mov eax, sciOpenPartition
	syscall
	ret
HcOpenPartition ENDP

ELSE
; 32bit

EXTERNDEF C sciOpenPartition:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcOpenPartition PROC
	mov eax, sciOpenPartition
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcOpenPartition ENDP

ENDIF

END