; Hc/NtPulseEvent
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciPulseEvent:DWORD

.DATA
.CODE

HcPulseEvent PROC
	mov r10, rcx
	mov eax, sciPulseEvent
	syscall
	ret
HcPulseEvent ENDP

ELSE
; 32bit

EXTERNDEF C sciPulseEvent:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcPulseEvent PROC
	mov eax, sciPulseEvent
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcPulseEvent ENDP

ENDIF

END