; Hc/NtQueryAttributesFile
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciQueryAttributesFile:DWORD

.DATA
.CODE

HcQueryAttributesFile PROC
	mov r10, rcx
	mov eax, sciQueryAttributesFile
	syscall
	ret
HcQueryAttributesFile ENDP

ELSE
; 32bit

EXTERNDEF C sciQueryAttributesFile:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcQueryAttributesFile PROC
	mov eax, sciQueryAttributesFile
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcQueryAttributesFile ENDP

ENDIF

END