; Hc/NtQueryDefaultLocale
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciQueryDefaultLocale:DWORD

.DATA
.CODE

HcQueryDefaultLocale PROC
	mov r10, rcx
	mov eax, sciQueryDefaultLocale
	syscall
	ret
HcQueryDefaultLocale ENDP

ELSE
; 32bit

EXTERNDEF C sciQueryDefaultLocale:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcQueryDefaultLocale PROC
	mov eax, sciQueryDefaultLocale
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcQueryDefaultLocale ENDP

ENDIF

END