; Hc/NtQueryOpenSubKeys
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciQueryOpenSubKeys:DWORD

.DATA
.CODE

HcQueryOpenSubKeys PROC
	mov r10, rcx
	mov eax, sciQueryOpenSubKeys
	syscall
	ret
HcQueryOpenSubKeys ENDP

ELSE
; 32bit

EXTERNDEF C sciQueryOpenSubKeys:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcQueryOpenSubKeys PROC
	mov eax, sciQueryOpenSubKeys
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcQueryOpenSubKeys ENDP

ENDIF

END