; Hc/NtQueryVolumeInformationFile
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciQueryVolumeInformationFile:DWORD

.DATA
.CODE

HcQueryVolumeInformationFile PROC
	mov r10, rcx
	mov eax, sciQueryVolumeInformationFile
	syscall
	ret
HcQueryVolumeInformationFile ENDP

ELSE
; 32bit

EXTERNDEF C sciQueryVolumeInformationFile:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcQueryVolumeInformationFile PROC
	mov eax, sciQueryVolumeInformationFile
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcQueryVolumeInformationFile ENDP

ENDIF

END