; Hc/NtQueueApcThread
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciQueueApcThread:DWORD

.DATA
.CODE

HcQueueApcThread PROC
	mov r10, rcx
	mov eax, sciQueueApcThread
	syscall
	ret
HcQueueApcThread ENDP

ELSE
; 32bit

EXTERNDEF C sciQueueApcThread:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcQueueApcThread PROC
	mov eax, sciQueueApcThread
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcQueueApcThread ENDP

ENDIF

END