; Hc/NtReadOnlyEnlistment
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciReadOnlyEnlistment:DWORD

.DATA
.CODE

HcReadOnlyEnlistment PROC
	mov r10, rcx
	mov eax, sciReadOnlyEnlistment
	syscall
	ret
HcReadOnlyEnlistment ENDP

ELSE
; 32bit

EXTERNDEF C sciReadOnlyEnlistment:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcReadOnlyEnlistment PROC
	mov eax, sciReadOnlyEnlistment
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcReadOnlyEnlistment ENDP

ENDIF

END