; Hc/NtReleaseSemaphore
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciReleaseSemaphore:DWORD

.DATA
.CODE

HcReleaseSemaphore PROC
	mov r10, rcx
	mov eax, sciReleaseSemaphore
	syscall
	ret
HcReleaseSemaphore ENDP

ELSE
; 32bit

EXTERNDEF C sciReleaseSemaphore:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcReleaseSemaphore PROC
	mov eax, sciReleaseSemaphore
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcReleaseSemaphore ENDP

ENDIF

END