; Hc/NtRemoveIoCompletionEx
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciRemoveIoCompletionEx:DWORD

.DATA
.CODE

HcRemoveIoCompletionEx PROC
	mov r10, rcx
	mov eax, sciRemoveIoCompletionEx
	syscall
	ret
HcRemoveIoCompletionEx ENDP

ELSE
; 32bit

EXTERNDEF C sciRemoveIoCompletionEx:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcRemoveIoCompletionEx PROC
	mov eax, sciRemoveIoCompletionEx
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcRemoveIoCompletionEx ENDP

ENDIF

END