; Hc/NtSaveKey
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciSaveKey:DWORD

.DATA
.CODE

HcSaveKey PROC
	mov r10, rcx
	mov eax, sciSaveKey
	syscall
	ret
HcSaveKey ENDP

ELSE
; 32bit

EXTERNDEF C sciSaveKey:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcSaveKey PROC
	mov eax, sciSaveKey
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcSaveKey ENDP

ENDIF

END