; Hc/NtSetEventBoostPriority
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciSetEventBoostPriority:DWORD

.DATA
.CODE

HcSetEventBoostPriority PROC
	mov r10, rcx
	mov eax, sciSetEventBoostPriority
	syscall
	ret
HcSetEventBoostPriority ENDP

ELSE
; 32bit

EXTERNDEF C sciSetEventBoostPriority:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcSetEventBoostPriority PROC
	mov eax, sciSetEventBoostPriority
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcSetEventBoostPriority ENDP

ENDIF

END