; Hc/NtSetIoCompletionEx
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciSetIoCompletionEx:DWORD

.DATA
.CODE

HcSetIoCompletionEx PROC
	mov r10, rcx
	mov eax, sciSetIoCompletionEx
	syscall
	ret
HcSetIoCompletionEx ENDP

ELSE
; 32bit

EXTERNDEF C sciSetIoCompletionEx:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcSetIoCompletionEx PROC
	mov eax, sciSetIoCompletionEx
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcSetIoCompletionEx ENDP

ENDIF

END