; Hc/NtSetQuotaInformationFile
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciSetQuotaInformationFile:DWORD

.DATA
.CODE

HcSetQuotaInformationFile PROC
	mov r10, rcx
	mov eax, sciSetQuotaInformationFile
	syscall
	ret
HcSetQuotaInformationFile ENDP

ELSE
; 32bit

EXTERNDEF C sciSetQuotaInformationFile:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcSetQuotaInformationFile PROC
	mov eax, sciSetQuotaInformationFile
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcSetQuotaInformationFile ENDP

ENDIF

END