; Hc/NtSetSystemTime
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciSetSystemTime:DWORD

.DATA
.CODE

HcSetSystemTime PROC
	mov r10, rcx
	mov eax, sciSetSystemTime
	syscall
	ret
HcSetSystemTime ENDP

ELSE
; 32bit

EXTERNDEF C sciSetSystemTime:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcSetSystemTime PROC
	mov eax, sciSetSystemTime
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcSetSystemTime ENDP

ENDIF

END