; Hc/NtSetSystemInformation
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciSetSystemInformation:DWORD

.DATA
.CODE

HcSetSystemInformation PROC
	mov r10, rcx
	mov eax, sciSetSystemInformation
	syscall
	ret
HcSetSystemInformation ENDP

ELSE
; 32bit

EXTERNDEF C sciSetSystemInformation:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcSetSystemInformation PROC
	mov eax, sciSetSystemInformation
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcSetSystemInformation ENDP

ENDIF

END