; Hc/NtSetThreadExecutionState
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciSetThreadExecutionState:DWORD

.DATA
.CODE

HcSetThreadExecutionState PROC
	mov r10, rcx
	mov eax, sciSetThreadExecutionState
	syscall
	ret
HcSetThreadExecutionState ENDP

ELSE
; 32bit

EXTERNDEF C sciSetThreadExecutionState:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcSetThreadExecutionState PROC
	mov eax, sciSetThreadExecutionState
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcSetThreadExecutionState ENDP

ENDIF

END