; Hc/NtSignalAndWaitForSingleObject
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciSignalAndWaitForSingleObject:DWORD

.DATA
.CODE

HcSignalAndWaitForSingleObject PROC
	mov r10, rcx
	mov eax, sciSignalAndWaitForSingleObject
	syscall
	ret
HcSignalAndWaitForSingleObject ENDP

ELSE
; 32bit

EXTERNDEF C sciSignalAndWaitForSingleObject:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcSignalAndWaitForSingleObject PROC
	mov eax, sciSignalAndWaitForSingleObject
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcSignalAndWaitForSingleObject ENDP

ENDIF

END