; Hc/NtWorkerFactoryWorkerReady
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciWorkerFactoryWorkerReady:DWORD

.DATA
.CODE

HcWorkerFactoryWorkerReady PROC
	mov r10, rcx
	mov eax, sciWorkerFactoryWorkerReady
	syscall
	ret
HcWorkerFactoryWorkerReady ENDP

ELSE
; 32bit

EXTERNDEF C sciWorkerFactoryWorkerReady:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcWorkerFactoryWorkerReady PROC
	mov eax, sciWorkerFactoryWorkerReady
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcWorkerFactoryWorkerReady ENDP

ENDIF

END