; Hc/NtWriteFile
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciWriteFile:DWORD

.DATA
.CODE

HcWriteFile PROC
	mov r10, rcx
	mov eax, sciWriteFile
	syscall
	ret
HcWriteFile ENDP

ELSE
; 32bit

EXTERNDEF C sciWriteFile:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcWriteFile PROC
	mov eax, sciWriteFile
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcWriteFile ENDP

ENDIF

END