; Hc/NtAccessCheckByTypeAndAuditAlarm
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciAccessCheckByTypeAndAuditAlarm:DWORD

.DATA
.CODE

HcAccessCheckByTypeAndAuditAlarm PROC
	mov r10, rcx
	mov eax, sciAccessCheckByTypeAndAuditAlarm
	syscall
	ret
HcAccessCheckByTypeAndAuditAlarm ENDP

ELSE
; 32bit

EXTERNDEF C sciAccessCheckByTypeAndAuditAlarm:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcAccessCheckByTypeAndAuditAlarm PROC
	mov eax, sciAccessCheckByTypeAndAuditAlarm
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcAccessCheckByTypeAndAuditAlarm ENDP

ENDIF

END