; Hc/NtAlertResumeThread
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciAlertResumeThread:DWORD

.DATA
.CODE

HcAlertResumeThread PROC
	mov r10, rcx
	mov eax, sciAlertResumeThread
	syscall
	ret
HcAlertResumeThread ENDP

ELSE
; 32bit

EXTERNDEF C sciAlertResumeThread:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcAlertResumeThread PROC
	mov eax, sciAlertResumeThread
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcAlertResumeThread ENDP

ENDIF

END