; Hc/NtAlertThread
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciAlertThread:DWORD

.DATA
.CODE

HcAlertThread PROC
	mov r10, rcx
	mov eax, sciAlertThread
	syscall
	ret
HcAlertThread ENDP

ELSE
; 32bit

EXTERNDEF C sciAlertThread:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcAlertThread PROC
	mov eax, sciAlertThread
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcAlertThread ENDP

ENDIF

END