; Hc/NtAlpcDeletePortSection
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciAlpcDeletePortSection:DWORD

.DATA
.CODE

HcAlpcDeletePortSection PROC
	mov r10, rcx
	mov eax, sciAlpcDeletePortSection
	syscall
	ret
HcAlpcDeletePortSection ENDP

ELSE
; 32bit

EXTERNDEF C sciAlpcDeletePortSection:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcAlpcDeletePortSection PROC
	mov eax, sciAlpcDeletePortSection
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcAlpcDeletePortSection ENDP

ENDIF

END