; Hc/NtAlpcSendWaitReceivePort
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciAlpcSendWaitReceivePort:DWORD

.DATA
.CODE

HcAlpcSendWaitReceivePort PROC
	mov r10, rcx
	mov eax, sciAlpcSendWaitReceivePort
	syscall
	ret
HcAlpcSendWaitReceivePort ENDP

ELSE
; 32bit

EXTERNDEF C sciAlpcSendWaitReceivePort:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcAlpcSendWaitReceivePort PROC
	mov eax, sciAlpcSendWaitReceivePort
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcAlpcSendWaitReceivePort ENDP

ENDIF

END