; Hc/NtAlpcQueryInformation
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciAlpcQueryInformation:DWORD

.DATA
.CODE

HcAlpcQueryInformation PROC
	mov r10, rcx
	mov eax, sciAlpcQueryInformation
	syscall
	ret
HcAlpcQueryInformation ENDP

ELSE
; 32bit

EXTERNDEF C sciAlpcQueryInformation:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcAlpcQueryInformation PROC
	mov eax, sciAlpcQueryInformation
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcAlpcQueryInformation ENDP

ENDIF

END