; Hc/NtCompressKey
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciCompressKey:DWORD

.DATA
.CODE

HcCompressKey PROC
	mov r10, rcx
	mov eax, sciCompressKey
	syscall
	ret
HcCompressKey ENDP

ELSE
; 32bit

EXTERNDEF C sciCompressKey:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcCompressKey PROC
	mov eax, sciCompressKey
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcCompressKey ENDP

ENDIF

END