; Hc/NtCreateJobSet
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciCreateJobSet:DWORD

.DATA
.CODE

HcCreateJobSet PROC
	mov r10, rcx
	mov eax, sciCreateJobSet
	syscall
	ret
HcCreateJobSet ENDP

ELSE
; 32bit

EXTERNDEF C sciCreateJobSet:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcCreateJobSet PROC
	mov eax, sciCreateJobSet
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcCreateJobSet ENDP

ENDIF

END