; Hc/NtCreateKey
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciCreateKey:DWORD

.DATA
.CODE

HcCreateKey PROC
	mov r10, rcx
	mov eax, sciCreateKey
	syscall
	ret
HcCreateKey ENDP

ELSE
; 32bit

EXTERNDEF C sciCreateKey:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcCreateKey PROC
	mov eax, sciCreateKey
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcCreateKey ENDP

ENDIF

END