; Hc/NtCreateTransactionManager
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciCreateTransactionManager:DWORD

.DATA
.CODE

HcCreateTransactionManager PROC
	mov r10, rcx
	mov eax, sciCreateTransactionManager
	syscall
	ret
HcCreateTransactionManager ENDP

ELSE
; 32bit

EXTERNDEF C sciCreateTransactionManager:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcCreateTransactionManager PROC
	mov eax, sciCreateTransactionManager
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcCreateTransactionManager ENDP

ENDIF

END