; Hc/NtCreateEnlistment
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciCreateEnlistment:DWORD

.DATA
.CODE

HcCreateEnlistment PROC
	mov r10, rcx
	mov eax, sciCreateEnlistment
	syscall
	ret
HcCreateEnlistment ENDP

ELSE
; 32bit

EXTERNDEF C sciCreateEnlistment:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcCreateEnlistment PROC
	mov eax, sciCreateEnlistment
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcCreateEnlistment ENDP

ENDIF

END