; Hc/NtCreateEventPair
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciCreateEventPair:DWORD

.DATA
.CODE

HcCreateEventPair PROC
	mov r10, rcx
	mov eax, sciCreateEventPair
	syscall
	ret
HcCreateEventPair ENDP

ELSE
; 32bit

EXTERNDEF C sciCreateEventPair:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcCreateEventPair PROC
	mov eax, sciCreateEventPair
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcCreateEventPair ENDP

ENDIF

END