; Hc/NtCreateImplicitCompositionInputSink
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciCreateImplicitCompositionInputSink:DWORD

.DATA
.CODE

HcCreateImplicitCompositionInputSink PROC
	mov r10, rcx
	mov eax, sciCreateImplicitCompositionInputSink
	syscall
	ret
HcCreateImplicitCompositionInputSink ENDP

ELSE
; 32bit

EXTERNDEF C sciCreateImplicitCompositionInputSink:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcCreateImplicitCompositionInputSink PROC
	mov eax, sciCreateImplicitCompositionInputSink
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcCreateImplicitCompositionInputSink ENDP

ENDIF

END