; Hc/NtDCompositionSetChildRootVisual
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciDCompositionSetChildRootVisual:DWORD

.DATA
.CODE

HcDCompositionSetChildRootVisual PROC
	mov r10, rcx
	mov eax, sciDCompositionSetChildRootVisual
	syscall
	ret
HcDCompositionSetChildRootVisual ENDP

ELSE
; 32bit

EXTERNDEF C sciDCompositionSetChildRootVisual:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcDCompositionSetChildRootVisual PROC
	mov eax, sciDCompositionSetChildRootVisual
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcDCompositionSetChildRootVisual ENDP

ENDIF

END