; Hc/NtDCompositionReferenceSharedResourceOnDwmChannel
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciDCompositionReferenceSharedResourceOnDwmChannel:DWORD

.DATA
.CODE

HcDCompositionReferenceSharedResourceOnDwmChannel PROC
	mov r10, rcx
	mov eax, sciDCompositionReferenceSharedResourceOnDwmChannel
	syscall
	ret
HcDCompositionReferenceSharedResourceOnDwmChannel ENDP

ELSE
; 32bit

EXTERNDEF C sciDCompositionReferenceSharedResourceOnDwmChannel:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcDCompositionReferenceSharedResourceOnDwmChannel PROC
	mov eax, sciDCompositionReferenceSharedResourceOnDwmChannel
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcDCompositionReferenceSharedResourceOnDwmChannel ENDP

ENDIF

END