; Hc/NtDCompositionRetireFrame
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciDCompositionRetireFrame:DWORD

.DATA
.CODE

HcDCompositionRetireFrame PROC
	mov r10, rcx
	mov eax, sciDCompositionRetireFrame
	syscall
	ret
HcDCompositionRetireFrame ENDP

ELSE
; 32bit

EXTERNDEF C sciDCompositionRetireFrame:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcDCompositionRetireFrame PROC
	mov eax, sciDCompositionRetireFrame
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcDCompositionRetireFrame ENDP

ENDIF

END