; Hc/NtDCompositionCommitSynchronizationObject
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciDCompositionCommitSynchronizationObject:DWORD

.DATA
.CODE

HcDCompositionCommitSynchronizationObject PROC
	mov r10, rcx
	mov eax, sciDCompositionCommitSynchronizationObject
	syscall
	ret
HcDCompositionCommitSynchronizationObject ENDP

ELSE
; 32bit

EXTERNDEF C sciDCompositionCommitSynchronizationObject:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcDCompositionCommitSynchronizationObject PROC
	mov eax, sciDCompositionCommitSynchronizationObject
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcDCompositionCommitSynchronizationObject ENDP

ENDIF

END