; Hc/NtDCompositionCreateAndBindSharedSection
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciDCompositionCreateAndBindSharedSection:DWORD

.DATA
.CODE

HcDCompositionCreateAndBindSharedSection PROC
	mov r10, rcx
	mov eax, sciDCompositionCreateAndBindSharedSection
	syscall
	ret
HcDCompositionCreateAndBindSharedSection ENDP

ELSE
; 32bit

EXTERNDEF C sciDCompositionCreateAndBindSharedSection:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcDCompositionCreateAndBindSharedSection PROC
	mov eax, sciDCompositionCreateAndBindSharedSection
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcDCompositionCreateAndBindSharedSection ENDP

ENDIF

END