; Hc/NtDCompositionTelemetryAnimationScenarioReference
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciDCompositionTelemetryAnimationScenarioReference:DWORD

.DATA
.CODE

HcDCompositionTelemetryAnimationScenarioReference PROC
	mov r10, rcx
	mov eax, sciDCompositionTelemetryAnimationScenarioReference
	syscall
	ret
HcDCompositionTelemetryAnimationScenarioReference ENDP

ELSE
; 32bit

EXTERNDEF C sciDCompositionTelemetryAnimationScenarioReference:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcDCompositionTelemetryAnimationScenarioReference PROC
	mov eax, sciDCompositionTelemetryAnimationScenarioReference
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcDCompositionTelemetryAnimationScenarioReference ENDP

ENDIF

END