; Hc/NtDCompositionDestroyConnectionContext
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciDCompositionDestroyConnectionContext:DWORD

.DATA
.CODE

HcDCompositionDestroyConnectionContext PROC
	mov r10, rcx
	mov eax, sciDCompositionDestroyConnectionContext
	syscall
	ret
HcDCompositionDestroyConnectionContext ENDP

ELSE
; 32bit

EXTERNDEF C sciDCompositionDestroyConnectionContext:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcDCompositionDestroyConnectionContext PROC
	mov eax, sciDCompositionDestroyConnectionContext
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcDCompositionDestroyConnectionContext ENDP

ENDIF

END