; Hc/NtDCompositionDwmSyncFlush
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciDCompositionDwmSyncFlush:DWORD

.DATA
.CODE

HcDCompositionDwmSyncFlush PROC
	mov r10, rcx
	mov eax, sciDCompositionDwmSyncFlush
	syscall
	ret
HcDCompositionDwmSyncFlush ENDP

ELSE
; 32bit

EXTERNDEF C sciDCompositionDwmSyncFlush:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcDCompositionDwmSyncFlush PROC
	mov eax, sciDCompositionDwmSyncFlush
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcDCompositionDwmSyncFlush ENDP

ENDIF

END