; Hc/NtDCompositionTelemetryTouchInteractionEnd
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciDCompositionTelemetryTouchInteractionEnd:DWORD

.DATA
.CODE

HcDCompositionTelemetryTouchInteractionEnd PROC
	mov r10, rcx
	mov eax, sciDCompositionTelemetryTouchInteractionEnd
	syscall
	ret
HcDCompositionTelemetryTouchInteractionEnd ENDP

ELSE
; 32bit

EXTERNDEF C sciDCompositionTelemetryTouchInteractionEnd:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcDCompositionTelemetryTouchInteractionEnd PROC
	mov eax, sciDCompositionTelemetryTouchInteractionEnd
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcDCompositionTelemetryTouchInteractionEnd ENDP

ENDIF

END