; Hc/NtDCompositionDiscardFrame
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciDCompositionDiscardFrame:DWORD

.DATA
.CODE

HcDCompositionDiscardFrame PROC
	mov r10, rcx
	mov eax, sciDCompositionDiscardFrame
	syscall
	ret
HcDCompositionDiscardFrame ENDP

ELSE
; 32bit

EXTERNDEF C sciDCompositionDiscardFrame:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcDCompositionDiscardFrame PROC
	mov eax, sciDCompositionDiscardFrame
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcDCompositionDiscardFrame ENDP

ENDIF

END