; Hc/NtDCompositionConnectPipe
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciDCompositionConnectPipe:DWORD

.DATA
.CODE

HcDCompositionConnectPipe PROC
	mov r10, rcx
	mov eax, sciDCompositionConnectPipe
	syscall
	ret
HcDCompositionConnectPipe ENDP

ELSE
; 32bit

EXTERNDEF C sciDCompositionConnectPipe:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcDCompositionConnectPipe PROC
	mov eax, sciDCompositionConnectPipe
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcDCompositionConnectPipe ENDP

ENDIF

END