; Hc/NtDCompositionRemoveVisualChild
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciDCompositionRemoveVisualChild:DWORD

.DATA
.CODE

HcDCompositionRemoveVisualChild PROC
	mov r10, rcx
	mov eax, sciDCompositionRemoveVisualChild
	syscall
	ret
HcDCompositionRemoveVisualChild ENDP

ELSE
; 32bit

EXTERNDEF C sciDCompositionRemoveVisualChild:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcDCompositionRemoveVisualChild PROC
	mov eax, sciDCompositionRemoveVisualChild
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcDCompositionRemoveVisualChild ENDP

ENDIF

END