; Hc/NtDCompositionConfirmFrame
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciDCompositionConfirmFrame:DWORD

.DATA
.CODE

HcDCompositionConfirmFrame PROC
	mov r10, rcx
	mov eax, sciDCompositionConfirmFrame
	syscall
	ret
HcDCompositionConfirmFrame ENDP

ELSE
; 32bit

EXTERNDEF C sciDCompositionConfirmFrame:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcDCompositionConfirmFrame PROC
	mov eax, sciDCompositionConfirmFrame
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcDCompositionConfirmFrame ENDP

ENDIF

END