; Hc/NtDCompositionDuplicateHandleToProcess
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciDCompositionDuplicateHandleToProcess:DWORD

.DATA
.CODE

HcDCompositionDuplicateHandleToProcess PROC
	mov r10, rcx
	mov eax, sciDCompositionDuplicateHandleToProcess
	syscall
	ret
HcDCompositionDuplicateHandleToProcess ENDP

ELSE
; 32bit

EXTERNDEF C sciDCompositionDuplicateHandleToProcess:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcDCompositionDuplicateHandleToProcess PROC
	mov eax, sciDCompositionDuplicateHandleToProcess
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcDCompositionDuplicateHandleToProcess ENDP

ENDIF

END