; Hc/NtDCompositionSignalGpuFence
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciDCompositionSignalGpuFence:DWORD

.DATA
.CODE

HcDCompositionSignalGpuFence PROC
	mov r10, rcx
	mov eax, sciDCompositionSignalGpuFence
	syscall
	ret
HcDCompositionSignalGpuFence ENDP

ELSE
; 32bit

EXTERNDEF C sciDCompositionSignalGpuFence:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcDCompositionSignalGpuFence PROC
	mov eax, sciDCompositionSignalGpuFence
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcDCompositionSignalGpuFence ENDP

ENDIF

END