; Hc/NtDCompositionTelemetryAnimationScenarioBegin
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciDCompositionTelemetryAnimationScenarioBegin:DWORD

.DATA
.CODE

HcDCompositionTelemetryAnimationScenarioBegin PROC
	mov r10, rcx
	mov eax, sciDCompositionTelemetryAnimationScenarioBegin
	syscall
	ret
HcDCompositionTelemetryAnimationScenarioBegin ENDP

ELSE
; 32bit

EXTERNDEF C sciDCompositionTelemetryAnimationScenarioBegin:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcDCompositionTelemetryAnimationScenarioBegin PROC
	mov eax, sciDCompositionTelemetryAnimationScenarioBegin
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcDCompositionTelemetryAnimationScenarioBegin ENDP

ENDIF

END