; Hc/NtDCompositionGetFrameStatistics
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciDCompositionGetFrameStatistics:DWORD

.DATA
.CODE

HcDCompositionGetFrameStatistics PROC
	mov r10, rcx
	mov eax, sciDCompositionGetFrameStatistics
	syscall
	ret
HcDCompositionGetFrameStatistics ENDP

ELSE
; 32bit

EXTERNDEF C sciDCompositionGetFrameStatistics:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcDCompositionGetFrameStatistics PROC
	mov eax, sciDCompositionGetFrameStatistics
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcDCompositionGetFrameStatistics ENDP

ENDIF

END