; Hc/NtDCompositionGetConnectionBatch
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciDCompositionGetConnectionBatch:DWORD

.DATA
.CODE

HcDCompositionGetConnectionBatch PROC
	mov r10, rcx
	mov eax, sciDCompositionGetConnectionBatch
	syscall
	ret
HcDCompositionGetConnectionBatch ENDP

ELSE
; 32bit

EXTERNDEF C sciDCompositionGetConnectionBatch:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcDCompositionGetConnectionBatch PROC
	mov eax, sciDCompositionGetConnectionBatch
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcDCompositionGetConnectionBatch ENDP

ENDIF

END