; Hc/NtDCompositionSetResourceCallbackId
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciDCompositionSetResourceCallbackId:DWORD

.DATA
.CODE

HcDCompositionSetResourceCallbackId PROC
	mov r10, rcx
	mov eax, sciDCompositionSetResourceCallbackId
	syscall
	ret
HcDCompositionSetResourceCallbackId ENDP

ELSE
; 32bit

EXTERNDEF C sciDCompositionSetResourceCallbackId:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcDCompositionSetResourceCallbackId PROC
	mov eax, sciDCompositionSetResourceCallbackId
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcDCompositionSetResourceCallbackId ENDP

ENDIF

END