; Hc/NtDCompositionTelemetryTouchInteractionBegin
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciDCompositionTelemetryTouchInteractionBegin:DWORD

.DATA
.CODE

HcDCompositionTelemetryTouchInteractionBegin PROC
	mov r10, rcx
	mov eax, sciDCompositionTelemetryTouchInteractionBegin
	syscall
	ret
HcDCompositionTelemetryTouchInteractionBegin ENDP

ELSE
; 32bit

EXTERNDEF C sciDCompositionTelemetryTouchInteractionBegin:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcDCompositionTelemetryTouchInteractionBegin PROC
	mov eax, sciDCompositionTelemetryTouchInteractionBegin
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcDCompositionTelemetryTouchInteractionBegin ENDP

ENDIF

END