; Hc/NtDelayExecution
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciDelayExecution:DWORD

.DATA
.CODE

HcDelayExecution PROC
	mov r10, rcx
	mov eax, sciDelayExecution
	syscall
	ret
HcDelayExecution ENDP

ELSE
; 32bit

EXTERNDEF C sciDelayExecution:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcDelayExecution PROC
	mov eax, sciDelayExecution
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcDelayExecution ENDP

ENDIF

END