; Hc/NtDeletePrivateNamespace
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciDeletePrivateNamespace:DWORD

.DATA
.CODE

HcDeletePrivateNamespace PROC
	mov r10, rcx
	mov eax, sciDeletePrivateNamespace
	syscall
	ret
HcDeletePrivateNamespace ENDP

ELSE
; 32bit

EXTERNDEF C sciDeletePrivateNamespace:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcDeletePrivateNamespace PROC
	mov eax, sciDeletePrivateNamespace
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcDeletePrivateNamespace ENDP

ENDIF

END