; Hc/NtDisplayString
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciDisplayString:DWORD

.DATA
.CODE

HcDisplayString PROC
	mov r10, rcx
	mov eax, sciDisplayString
	syscall
	ret
HcDisplayString ENDP

ELSE
; 32bit

EXTERNDEF C sciDisplayString:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcDisplayString PROC
	mov eax, sciDisplayString
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcDisplayString ENDP

ENDIF

END