; Hc/NtDuplicateObject
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciDuplicateObject:DWORD

.DATA
.CODE

HcDuplicateObject PROC
	mov r10, rcx
	mov eax, sciDuplicateObject
	syscall
	ret
HcDuplicateObject ENDP

ELSE
; 32bit

EXTERNDEF C sciDuplicateObject:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcDuplicateObject PROC
	mov eax, sciDuplicateObject
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcDuplicateObject ENDP

ENDIF

END