; Hc/NtDuplicateToken
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciDuplicateToken:DWORD

.DATA
.CODE

HcDuplicateToken PROC
	mov r10, rcx
	mov eax, sciDuplicateToken
	syscall
	ret
HcDuplicateToken ENDP

ELSE
; 32bit

EXTERNDEF C sciDuplicateToken:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcDuplicateToken PROC
	mov eax, sciDuplicateToken
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcDuplicateToken ENDP

ENDIF

END