; Hc/NtDWMBindCursorToOutputConfig
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciDWMBindCursorToOutputConfig:DWORD

.DATA
.CODE

HcDWMBindCursorToOutputConfig PROC
	mov r10, rcx
	mov eax, sciDWMBindCursorToOutputConfig
	syscall
	ret
HcDWMBindCursorToOutputConfig ENDP

ELSE
; 32bit

EXTERNDEF C sciDWMBindCursorToOutputConfig:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcDWMBindCursorToOutputConfig PROC
	mov eax, sciDWMBindCursorToOutputConfig
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcDWMBindCursorToOutputConfig ENDP

ENDIF

END