; Hc/NtEnumerateSystemEnvironmentValuesEx
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciEnumerateSystemEnvironmentValuesEx:DWORD

.DATA
.CODE

HcEnumerateSystemEnvironmentValuesEx PROC
	mov r10, rcx
	mov eax, sciEnumerateSystemEnvironmentValuesEx
	syscall
	ret
HcEnumerateSystemEnvironmentValuesEx ENDP

ELSE
; 32bit

EXTERNDEF C sciEnumerateSystemEnvironmentValuesEx:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcEnumerateSystemEnvironmentValuesEx PROC
	mov eax, sciEnumerateSystemEnvironmentValuesEx
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcEnumerateSystemEnvironmentValuesEx ENDP

ENDIF

END