; Hc/NtFilterBootOption
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciFilterBootOption:DWORD

.DATA
.CODE

HcFilterBootOption PROC
	mov r10, rcx
	mov eax, sciFilterBootOption
	syscall
	ret
HcFilterBootOption ENDP

ELSE
; 32bit

EXTERNDEF C sciFilterBootOption:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcFilterBootOption PROC
	mov eax, sciFilterBootOption
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcFilterBootOption ENDP

ENDIF

END