; Hc/NtFlipObjectCreate
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciFlipObjectCreate:DWORD

.DATA
.CODE

HcFlipObjectCreate PROC
	mov r10, rcx
	mov eax, sciFlipObjectCreate
	syscall
	ret
HcFlipObjectCreate ENDP

ELSE
; 32bit

EXTERNDEF C sciFlipObjectCreate:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcFlipObjectCreate PROC
	mov eax, sciFlipObjectCreate
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcFlipObjectCreate ENDP

ENDIF

END