; Hc/NtFreeUserPhysicalPages
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciFreeUserPhysicalPages:DWORD

.DATA
.CODE

HcFreeUserPhysicalPages PROC
	mov r10, rcx
	mov eax, sciFreeUserPhysicalPages
	syscall
	ret
HcFreeUserPhysicalPages ENDP

ELSE
; 32bit

EXTERNDEF C sciFreeUserPhysicalPages:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcFreeUserPhysicalPages PROC
	mov eax, sciFreeUserPhysicalPages
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcFreeUserPhysicalPages ENDP

ENDIF

END