; Hc/NtFreezeRegistry
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciFreezeRegistry:DWORD

.DATA
.CODE

HcFreezeRegistry PROC
	mov r10, rcx
	mov eax, sciFreezeRegistry
	syscall
	ret
HcFreezeRegistry ENDP

ELSE
; 32bit

EXTERNDEF C sciFreezeRegistry:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcFreezeRegistry PROC
	mov eax, sciFreezeRegistry
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcFreezeRegistry ENDP

ENDIF

END