; Hc/NtGdiAlphaBlend
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiAlphaBlend:DWORD

.DATA
.CODE

HcGdiAlphaBlend PROC
	mov r10, rcx
	mov eax, sciGdiAlphaBlend
	syscall
	ret
HcGdiAlphaBlend ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiAlphaBlend:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiAlphaBlend PROC
	mov eax, sciGdiAlphaBlend
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiAlphaBlend ENDP

ENDIF

END