; Hc/NtGdiAddInitialFonts
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiAddInitialFonts:DWORD

.DATA
.CODE

HcGdiAddInitialFonts PROC
	mov r10, rcx
	mov eax, sciGdiAddInitialFonts
	syscall
	ret
HcGdiAddInitialFonts ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiAddInitialFonts:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiAddInitialFonts PROC
	mov eax, sciGdiAddInitialFonts
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiAddInitialFonts ENDP

ENDIF

END