; Hc/NtGdiAddFontResourceW
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiAddFontResourceW:DWORD

.DATA
.CODE

HcGdiAddFontResourceW PROC
	mov r10, rcx
	mov eax, sciGdiAddFontResourceW
	syscall
	ret
HcGdiAddFontResourceW ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiAddFontResourceW:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiAddFontResourceW PROC
	mov eax, sciGdiAddFontResourceW
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiAddFontResourceW ENDP

ENDIF

END