; Hc/NtGdiBRUSHOBJ_ulGetBrushColor
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiBRUSHOBJ_ulGetBrushColor:DWORD

.DATA
.CODE

HcGdiBRUSHOBJ_ulGetBrushColor PROC
	mov r10, rcx
	mov eax, sciGdiBRUSHOBJ_ulGetBrushColor
	syscall
	ret
HcGdiBRUSHOBJ_ulGetBrushColor ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiBRUSHOBJ_ulGetBrushColor:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiBRUSHOBJ_ulGetBrushColor PROC
	mov eax, sciGdiBRUSHOBJ_ulGetBrushColor
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiBRUSHOBJ_ulGetBrushColor ENDP

ENDIF

END