; Hc/NtGdiCombineTransform
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiCombineTransform:DWORD

.DATA
.CODE

HcGdiCombineTransform PROC
	mov r10, rcx
	mov eax, sciGdiCombineTransform
	syscall
	ret
HcGdiCombineTransform ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiCombineTransform:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiCombineTransform PROC
	mov eax, sciGdiCombineTransform
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiCombineTransform ENDP

ENDIF

END