; Hc/NtGdiCreateOPMProtectedOutput
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiCreateOPMProtectedOutput:DWORD

.DATA
.CODE

HcGdiCreateOPMProtectedOutput PROC
	mov r10, rcx
	mov eax, sciGdiCreateOPMProtectedOutput
	syscall
	ret
HcGdiCreateOPMProtectedOutput ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiCreateOPMProtectedOutput:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiCreateOPMProtectedOutput PROC
	mov eax, sciGdiCreateOPMProtectedOutput
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiCreateOPMProtectedOutput ENDP

ENDIF

END