; Hc/NtGdiCheckBitmapBits
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiCheckBitmapBits:DWORD

.DATA
.CODE

HcGdiCheckBitmapBits PROC
	mov r10, rcx
	mov eax, sciGdiCheckBitmapBits
	syscall
	ret
HcGdiCheckBitmapBits ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiCheckBitmapBits:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiCheckBitmapBits PROC
	mov eax, sciGdiCheckBitmapBits
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiCheckBitmapBits ENDP

ENDIF

END