; Hc/NtGdiCreateOPMProtectedOutputs
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiCreateOPMProtectedOutputs:DWORD

.DATA
.CODE

HcGdiCreateOPMProtectedOutputs PROC
	mov r10, rcx
	mov eax, sciGdiCreateOPMProtectedOutputs
	syscall
	ret
HcGdiCreateOPMProtectedOutputs ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiCreateOPMProtectedOutputs:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiCreateOPMProtectedOutputs PROC
	mov eax, sciGdiCreateOPMProtectedOutputs
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiCreateOPMProtectedOutputs ENDP

ENDIF

END