; Hc/NtGdiCreateHatchBrushInternal
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiCreateHatchBrushInternal:DWORD

.DATA
.CODE

HcGdiCreateHatchBrushInternal PROC
	mov r10, rcx
	mov eax, sciGdiCreateHatchBrushInternal
	syscall
	ret
HcGdiCreateHatchBrushInternal ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiCreateHatchBrushInternal:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiCreateHatchBrushInternal PROC
	mov eax, sciGdiCreateHatchBrushInternal
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiCreateHatchBrushInternal ENDP

ENDIF

END