; Hc/NtGdiCreateDIBitmapInternal
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiCreateDIBitmapInternal:DWORD

.DATA
.CODE

HcGdiCreateDIBitmapInternal PROC
	mov r10, rcx
	mov eax, sciGdiCreateDIBitmapInternal
	syscall
	ret
HcGdiCreateDIBitmapInternal ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiCreateDIBitmapInternal:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiCreateDIBitmapInternal PROC
	mov eax, sciGdiCreateDIBitmapInternal
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiCreateDIBitmapInternal ENDP

ENDIF

END