; Hc/NtGdiCreateEllipticRgn
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiCreateEllipticRgn:DWORD

.DATA
.CODE

HcGdiCreateEllipticRgn PROC
	mov r10, rcx
	mov eax, sciGdiCreateEllipticRgn
	syscall
	ret
HcGdiCreateEllipticRgn ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiCreateEllipticRgn:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiCreateEllipticRgn PROC
	mov eax, sciGdiCreateEllipticRgn
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiCreateEllipticRgn ENDP

ENDIF

END