; Hc/NtGdiColorCorrectPalette
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiColorCorrectPalette:DWORD

.DATA
.CODE

HcGdiColorCorrectPalette PROC
	mov r10, rcx
	mov eax, sciGdiColorCorrectPalette
	syscall
	ret
HcGdiColorCorrectPalette ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiColorCorrectPalette:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiColorCorrectPalette PROC
	mov eax, sciGdiColorCorrectPalette
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiColorCorrectPalette ENDP

ENDIF

END