; Hc/NtGdiCombineRgn
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiCombineRgn:DWORD

.DATA
.CODE

HcGdiCombineRgn PROC
	mov r10, rcx
	mov eax, sciGdiCombineRgn
	syscall
	ret
HcGdiCombineRgn ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiCombineRgn:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiCombineRgn PROC
	mov eax, sciGdiCombineRgn
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiCombineRgn ENDP

ENDIF

END