; Hc/NtGdiCreateBitmap
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiCreateBitmap:DWORD

.DATA
.CODE

HcGdiCreateBitmap PROC
	mov r10, rcx
	mov eax, sciGdiCreateBitmap
	syscall
	ret
HcGdiCreateBitmap ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiCreateBitmap:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiCreateBitmap PROC
	mov eax, sciGdiCreateBitmap
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiCreateBitmap ENDP

ENDIF

END