; Hc/NtGdiDdDDIQueryStatistics
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDIQueryStatistics:DWORD

.DATA
.CODE

HcGdiDdDDIQueryStatistics PROC
	mov r10, rcx
	mov eax, sciGdiDdDDIQueryStatistics
	syscall
	ret
HcGdiDdDDIQueryStatistics ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDIQueryStatistics:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDIQueryStatistics PROC
	mov eax, sciGdiDdDDIQueryStatistics
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDIQueryStatistics ENDP

ENDIF

END