; Hc/NtGdiDdDDIGetPresentHistory
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDIGetPresentHistory:DWORD

.DATA
.CODE

HcGdiDdDDIGetPresentHistory PROC
	mov r10, rcx
	mov eax, sciGdiDdDDIGetPresentHistory
	syscall
	ret
HcGdiDdDDIGetPresentHistory ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDIGetPresentHistory:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDIGetPresentHistory PROC
	mov eax, sciGdiDdDDIGetPresentHistory
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDIGetPresentHistory ENDP

ENDIF

END