; Hc/NtGdiDdDDIOpenSwapChain
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDIOpenSwapChain:DWORD

.DATA
.CODE

HcGdiDdDDIOpenSwapChain PROC
	mov r10, rcx
	mov eax, sciGdiDdDDIOpenSwapChain
	syscall
	ret
HcGdiDdDDIOpenSwapChain ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDIOpenSwapChain:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDIOpenSwapChain PROC
	mov eax, sciGdiDdDDIOpenSwapChain
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDIOpenSwapChain ENDP

ENDIF

END