; Hc/NtGdiDdDDIQueryAdapterInfo
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDIQueryAdapterInfo:DWORD

.DATA
.CODE

HcGdiDdDDIQueryAdapterInfo PROC
	mov r10, rcx
	mov eax, sciGdiDdDDIQueryAdapterInfo
	syscall
	ret
HcGdiDdDDIQueryAdapterInfo ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDIQueryAdapterInfo:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDIQueryAdapterInfo PROC
	mov eax, sciGdiDdDDIQueryAdapterInfo
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDIQueryAdapterInfo ENDP

ENDIF

END