; Hc/NtGdiDdFlipToGDISurface
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdFlipToGDISurface:DWORD

.DATA
.CODE

HcGdiDdFlipToGDISurface PROC
	mov r10, rcx
	mov eax, sciGdiDdFlipToGDISurface
	syscall
	ret
HcGdiDdFlipToGDISurface ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdFlipToGDISurface:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdFlipToGDISurface PROC
	mov eax, sciGdiDdFlipToGDISurface
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdFlipToGDISurface ENDP

ENDIF

END