; Hc/NtGdiDdUnlockD3D
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdUnlockD3D:DWORD

.DATA
.CODE

HcGdiDdUnlockD3D PROC
	mov r10, rcx
	mov eax, sciGdiDdUnlockD3D
	syscall
	ret
HcGdiDdUnlockD3D ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdUnlockD3D:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdUnlockD3D PROC
	mov eax, sciGdiDdUnlockD3D
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdUnlockD3D ENDP

ENDIF

END