; Hc/NtGdiDdDDICheckMonitorPowerState
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDICheckMonitorPowerState:DWORD

.DATA
.CODE

HcGdiDdDDICheckMonitorPowerState PROC
	mov r10, rcx
	mov eax, sciGdiDdDDICheckMonitorPowerState
	syscall
	ret
HcGdiDdDDICheckMonitorPowerState ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDICheckMonitorPowerState:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDICheckMonitorPowerState PROC
	mov eax, sciGdiDdDDICheckMonitorPowerState
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDICheckMonitorPowerState ENDP

ENDIF

END