; Hc/NtGdiDdDDIUpdateAllocationProperty
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDIUpdateAllocationProperty:DWORD

.DATA
.CODE

HcGdiDdDDIUpdateAllocationProperty PROC
	mov r10, rcx
	mov eax, sciGdiDdDDIUpdateAllocationProperty
	syscall
	ret
HcGdiDdDDIUpdateAllocationProperty ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDIUpdateAllocationProperty:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDIUpdateAllocationProperty PROC
	mov eax, sciGdiDdDDIUpdateAllocationProperty
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDIUpdateAllocationProperty ENDP

ENDIF

END