; Hc/NtGdiDdDDIOutputDuplPresent
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDIOutputDuplPresent:DWORD

.DATA
.CODE

HcGdiDdDDIOutputDuplPresent PROC
	mov r10, rcx
	mov eax, sciGdiDdDDIOutputDuplPresent
	syscall
	ret
HcGdiDdDDIOutputDuplPresent ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDIOutputDuplPresent:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDIOutputDuplPresent PROC
	mov eax, sciGdiDdDDIOutputDuplPresent
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDIOutputDuplPresent ENDP

ENDIF

END