; Hc/NtGdiDdDDISetVidPnSourceOwner
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDISetVidPnSourceOwner:DWORD

.DATA
.CODE

HcGdiDdDDISetVidPnSourceOwner PROC
	mov r10, rcx
	mov eax, sciGdiDdDDISetVidPnSourceOwner
	syscall
	ret
HcGdiDdDDISetVidPnSourceOwner ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDISetVidPnSourceOwner:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDISetVidPnSourceOwner PROC
	mov eax, sciGdiDdDDISetVidPnSourceOwner
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDISetVidPnSourceOwner ENDP

ENDIF

END