; Hc/NtGdiDdDDIDestroyOverlay
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDIDestroyOverlay:DWORD

.DATA
.CODE

HcGdiDdDDIDestroyOverlay PROC
	mov r10, rcx
	mov eax, sciGdiDdDDIDestroyOverlay
	syscall
	ret
HcGdiDdDDIDestroyOverlay ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDIDestroyOverlay:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDIDestroyOverlay PROC
	mov eax, sciGdiDdDDIDestroyOverlay
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDIDestroyOverlay ENDP

ENDIF

END