; Hc/NtGdiDvpDestroyVideoPort
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDvpDestroyVideoPort:DWORD

.DATA
.CODE

HcGdiDvpDestroyVideoPort PROC
	mov r10, rcx
	mov eax, sciGdiDvpDestroyVideoPort
	syscall
	ret
HcGdiDvpDestroyVideoPort ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDvpDestroyVideoPort:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDvpDestroyVideoPort PROC
	mov eax, sciGdiDvpDestroyVideoPort
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDvpDestroyVideoPort ENDP

ENDIF

END