; Hc/NtGdiDdEndMoCompFrame
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdEndMoCompFrame:DWORD

.DATA
.CODE

HcGdiDdEndMoCompFrame PROC
	mov r10, rcx
	mov eax, sciGdiDdEndMoCompFrame
	syscall
	ret
HcGdiDdEndMoCompFrame ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdEndMoCompFrame:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdEndMoCompFrame PROC
	mov eax, sciGdiDdEndMoCompFrame
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdEndMoCompFrame ENDP

ENDIF

END