; Hc/NtGdiDdDDIOpenNtHandleFromName
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDIOpenNtHandleFromName:DWORD

.DATA
.CODE

HcGdiDdDDIOpenNtHandleFromName PROC
	mov r10, rcx
	mov eax, sciGdiDdDDIOpenNtHandleFromName
	syscall
	ret
HcGdiDdDDIOpenNtHandleFromName ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDIOpenNtHandleFromName:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDIOpenNtHandleFromName PROC
	mov eax, sciGdiDdDDIOpenNtHandleFromName
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDIOpenNtHandleFromName ENDP

ENDIF

END