; Hc/NtGdiDdDDIOpenAdapterFromDeviceName
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDIOpenAdapterFromDeviceName:DWORD

.DATA
.CODE

HcGdiDdDDIOpenAdapterFromDeviceName PROC
	mov r10, rcx
	mov eax, sciGdiDdDDIOpenAdapterFromDeviceName
	syscall
	ret
HcGdiDdDDIOpenAdapterFromDeviceName ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDIOpenAdapterFromDeviceName:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDIOpenAdapterFromDeviceName PROC
	mov eax, sciGdiDdDDIOpenAdapterFromDeviceName
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDIOpenAdapterFromDeviceName ENDP

ENDIF

END