; Hc/NtGdiDdGetDriverInfo
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdGetDriverInfo:DWORD

.DATA
.CODE

HcGdiDdGetDriverInfo PROC
	mov r10, rcx
	mov eax, sciGdiDdGetDriverInfo
	syscall
	ret
HcGdiDdGetDriverInfo ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdGetDriverInfo:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdGetDriverInfo PROC
	mov eax, sciGdiDdGetDriverInfo
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdGetDriverInfo ENDP

ENDIF

END