; Hc/NtGdiDestroyPhysicalMonitor
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDestroyPhysicalMonitor:DWORD

.DATA
.CODE

HcGdiDestroyPhysicalMonitor PROC
	mov r10, rcx
	mov eax, sciGdiDestroyPhysicalMonitor
	syscall
	ret
HcGdiDestroyPhysicalMonitor ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDestroyPhysicalMonitor:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDestroyPhysicalMonitor PROC
	mov eax, sciGdiDestroyPhysicalMonitor
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDestroyPhysicalMonitor ENDP

ENDIF

END