; Hc/NtGdiD3dContextDestroyAll
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiD3dContextDestroyAll:DWORD

.DATA
.CODE

HcGdiD3dContextDestroyAll PROC
	mov r10, rcx
	mov eax, sciGdiD3dContextDestroyAll
	syscall
	ret
HcGdiD3dContextDestroyAll ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiD3dContextDestroyAll:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiD3dContextDestroyAll PROC
	mov eax, sciGdiD3dContextDestroyAll
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiD3dContextDestroyAll ENDP

ENDIF

END