; Hc/NtGdiDDCCIGetVCPFeature
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDDCCIGetVCPFeature:DWORD

.DATA
.CODE

HcGdiDDCCIGetVCPFeature PROC
	mov r10, rcx
	mov eax, sciGdiDDCCIGetVCPFeature
	syscall
	ret
HcGdiDDCCIGetVCPFeature ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDDCCIGetVCPFeature:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDDCCIGetVCPFeature PROC
	mov eax, sciGdiDDCCIGetVCPFeature
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDDCCIGetVCPFeature ENDP

ENDIF

END