; Hc/NtGdiDdDDIGetScanLine
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDIGetScanLine:DWORD

.DATA
.CODE

HcGdiDdDDIGetScanLine PROC
	mov r10, rcx
	mov eax, sciGdiDdDDIGetScanLine
	syscall
	ret
HcGdiDdDDIGetScanLine ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDIGetScanLine:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDIGetScanLine PROC
	mov eax, sciGdiDdDDIGetScanLine
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDIGetScanLine ENDP

ENDIF

END