; Hc/NtGdiDdDDICreateKeyedMutex2
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDICreateKeyedMutex2:DWORD

.DATA
.CODE

HcGdiDdDDICreateKeyedMutex2 PROC
	mov r10, rcx
	mov eax, sciGdiDdDDICreateKeyedMutex2
	syscall
	ret
HcGdiDdDDICreateKeyedMutex2 ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDICreateKeyedMutex2:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDICreateKeyedMutex2 PROC
	mov eax, sciGdiDdDDICreateKeyedMutex2
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDICreateKeyedMutex2 ENDP

ENDIF

END