; Hc/NtGdiDdDDISignalSynchronizationObjectFromCpu
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDISignalSynchronizationObjectFromCpu:DWORD

.DATA
.CODE

HcGdiDdDDISignalSynchronizationObjectFromCpu PROC
	mov r10, rcx
	mov eax, sciGdiDdDDISignalSynchronizationObjectFromCpu
	syscall
	ret
HcGdiDdDDISignalSynchronizationObjectFromCpu ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDISignalSynchronizationObjectFromCpu:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDISignalSynchronizationObjectFromCpu PROC
	mov eax, sciGdiDdDDISignalSynchronizationObjectFromCpu
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDISignalSynchronizationObjectFromCpu ENDP

ENDIF

END