; Hc/NtGdiDdDDIDestroyAllocation2
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDIDestroyAllocation2:DWORD

.DATA
.CODE

HcGdiDdDDIDestroyAllocation2 PROC
	mov r10, rcx
	mov eax, sciGdiDdDDIDestroyAllocation2
	syscall
	ret
HcGdiDdDDIDestroyAllocation2 ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDIDestroyAllocation2:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDIDestroyAllocation2 PROC
	mov eax, sciGdiDdDDIDestroyAllocation2
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDIDestroyAllocation2 ENDP

ENDIF

END