; Hc/NtGdiDdSetGammaRamp
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdSetGammaRamp:DWORD

.DATA
.CODE

HcGdiDdSetGammaRamp PROC
	mov r10, rcx
	mov eax, sciGdiDdSetGammaRamp
	syscall
	ret
HcGdiDdSetGammaRamp ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdSetGammaRamp:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdSetGammaRamp PROC
	mov eax, sciGdiDdSetGammaRamp
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdSetGammaRamp ENDP

ENDIF

END