; Hc/NtGdiDvpGetVideoPortConnectInfo
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDvpGetVideoPortConnectInfo:DWORD

.DATA
.CODE

HcGdiDvpGetVideoPortConnectInfo PROC
	mov r10, rcx
	mov eax, sciGdiDvpGetVideoPortConnectInfo
	syscall
	ret
HcGdiDvpGetVideoPortConnectInfo ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDvpGetVideoPortConnectInfo:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDvpGetVideoPortConnectInfo PROC
	mov eax, sciGdiDvpGetVideoPortConnectInfo
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDvpGetVideoPortConnectInfo ENDP

ENDIF

END