; Hc/NtGdiDxgGenericThunk
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDxgGenericThunk:DWORD

.DATA
.CODE

HcGdiDxgGenericThunk PROC
	mov r10, rcx
	mov eax, sciGdiDxgGenericThunk
	syscall
	ret
HcGdiDxgGenericThunk ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDxgGenericThunk:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDxgGenericThunk PROC
	mov eax, sciGdiDxgGenericThunk
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDxgGenericThunk ENDP

ENDIF

END