; Hc/NtGdiDdGetScanLine
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdGetScanLine:DWORD

.DATA
.CODE

HcGdiDdGetScanLine PROC
	mov r10, rcx
	mov eax, sciGdiDdGetScanLine
	syscall
	ret
HcGdiDdGetScanLine ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdGetScanLine:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdGetScanLine PROC
	mov eax, sciGdiDdGetScanLine
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdGetScanLine ENDP

ENDIF

END