; Hc/NtGdiDvpGetVideoPortFlipStatus
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDvpGetVideoPortFlipStatus:DWORD

.DATA
.CODE

HcGdiDvpGetVideoPortFlipStatus PROC
	mov r10, rcx
	mov eax, sciGdiDvpGetVideoPortFlipStatus
	syscall
	ret
HcGdiDvpGetVideoPortFlipStatus ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDvpGetVideoPortFlipStatus:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDvpGetVideoPortFlipStatus PROC
	mov eax, sciGdiDvpGetVideoPortFlipStatus
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDvpGetVideoPortFlipStatus ENDP

ENDIF

END