; Hc/NtGdiDdDDIPollDisplayChildren
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDIPollDisplayChildren:DWORD

.DATA
.CODE

HcGdiDdDDIPollDisplayChildren PROC
	mov r10, rcx
	mov eax, sciGdiDdDDIPollDisplayChildren
	syscall
	ret
HcGdiDdDDIPollDisplayChildren ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDIPollDisplayChildren:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDIPollDisplayChildren PROC
	mov eax, sciGdiDdDDIPollDisplayChildren
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDIPollDisplayChildren ENDP

ENDIF

END