; Hc/NtGdiDwmCreatedBitmapRemotingOutput
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDwmCreatedBitmapRemotingOutput:DWORD

.DATA
.CODE

HcGdiDwmCreatedBitmapRemotingOutput PROC
	mov r10, rcx
	mov eax, sciGdiDwmCreatedBitmapRemotingOutput
	syscall
	ret
HcGdiDwmCreatedBitmapRemotingOutput ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDwmCreatedBitmapRemotingOutput:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDwmCreatedBitmapRemotingOutput PROC
	mov eax, sciGdiDwmCreatedBitmapRemotingOutput
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDwmCreatedBitmapRemotingOutput ENDP

ENDIF

END