; Hc/NtGdiDdDDIMapGpuVirtualAddress
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDIMapGpuVirtualAddress:DWORD

.DATA
.CODE

HcGdiDdDDIMapGpuVirtualAddress PROC
	mov r10, rcx
	mov eax, sciGdiDdDDIMapGpuVirtualAddress
	syscall
	ret
HcGdiDdDDIMapGpuVirtualAddress ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDIMapGpuVirtualAddress:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDIMapGpuVirtualAddress PROC
	mov eax, sciGdiDdDDIMapGpuVirtualAddress
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDIMapGpuVirtualAddress ENDP

ENDIF

END