; Hc/NtGdiDvpCreateVideoPort
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDvpCreateVideoPort:DWORD

.DATA
.CODE

HcGdiDvpCreateVideoPort PROC
	mov r10, rcx
	mov eax, sciGdiDvpCreateVideoPort
	syscall
	ret
HcGdiDvpCreateVideoPort ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDvpCreateVideoPort:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDvpCreateVideoPort PROC
	mov eax, sciGdiDvpCreateVideoPort
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDvpCreateVideoPort ENDP

ENDIF

END