; Hc/NtGdiDdDDIOutputDuplGetMetaData
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDIOutputDuplGetMetaData:DWORD

.DATA
.CODE

HcGdiDdDDIOutputDuplGetMetaData PROC
	mov r10, rcx
	mov eax, sciGdiDdDDIOutputDuplGetMetaData
	syscall
	ret
HcGdiDdDDIOutputDuplGetMetaData ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDIOutputDuplGetMetaData:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDIOutputDuplGetMetaData PROC
	mov eax, sciGdiDdDDIOutputDuplGetMetaData
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDIOutputDuplGetMetaData ENDP

ENDIF

END