; Hc/NtGdiDeleteClientObj
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDeleteClientObj:DWORD

.DATA
.CODE

HcGdiDeleteClientObj PROC
	mov r10, rcx
	mov eax, sciGdiDeleteClientObj
	syscall
	ret
HcGdiDeleteClientObj ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDeleteClientObj:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDeleteClientObj PROC
	mov eax, sciGdiDeleteClientObj
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDeleteClientObj ENDP

ENDIF

END