; Hc/NtGdiDdCreateDirectDrawObject
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdCreateDirectDrawObject:DWORD

.DATA
.CODE

HcGdiDdCreateDirectDrawObject PROC
	mov r10, rcx
	mov eax, sciGdiDdCreateDirectDrawObject
	syscall
	ret
HcGdiDdCreateDirectDrawObject ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdCreateDirectDrawObject:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdCreateDirectDrawObject PROC
	mov eax, sciGdiDdCreateDirectDrawObject
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdCreateDirectDrawObject ENDP

ENDIF

END