; Hc/NtGdiDdDDIEscape
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDIEscape:DWORD

.DATA
.CODE

HcGdiDdDDIEscape PROC
	mov r10, rcx
	mov eax, sciGdiDdDDIEscape
	syscall
	ret
HcGdiDdDDIEscape ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDIEscape:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDIEscape PROC
	mov eax, sciGdiDdDDIEscape
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDIEscape ENDP

ENDIF

END