; Hc/NtGdiDdDDINetDispStopMiracastDisplayDevice
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDINetDispStopMiracastDisplayDevice:DWORD

.DATA
.CODE

HcGdiDdDDINetDispStopMiracastDisplayDevice PROC
	mov r10, rcx
	mov eax, sciGdiDdDDINetDispStopMiracastDisplayDevice
	syscall
	ret
HcGdiDdDDINetDispStopMiracastDisplayDevice ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDINetDispStopMiracastDisplayDevice:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDINetDispStopMiracastDisplayDevice PROC
	mov eax, sciGdiDdDDINetDispStopMiracastDisplayDevice
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDINetDispStopMiracastDisplayDevice ENDP

ENDIF

END