; Hc/NtGdiDdDestroyMoComp
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDestroyMoComp:DWORD

.DATA
.CODE

HcGdiDdDestroyMoComp PROC
	mov r10, rcx
	mov eax, sciGdiDdDestroyMoComp
	syscall
	ret
HcGdiDdDestroyMoComp ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDestroyMoComp:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDestroyMoComp PROC
	mov eax, sciGdiDdDestroyMoComp
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDestroyMoComp ENDP

ENDIF

END