; Hc/NtGdiDdDDICreateSwapChain
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDICreateSwapChain:DWORD

.DATA
.CODE

HcGdiDdDDICreateSwapChain PROC
	mov r10, rcx
	mov eax, sciGdiDdDDICreateSwapChain
	syscall
	ret
HcGdiDdDDICreateSwapChain ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDICreateSwapChain:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDICreateSwapChain PROC
	mov eax, sciGdiDdDDICreateSwapChain
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDICreateSwapChain ENDP

ENDIF

END