; Hc/NtGdiDdDDIAcquireKeyedMutex
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDIAcquireKeyedMutex:DWORD

.DATA
.CODE

HcGdiDdDDIAcquireKeyedMutex PROC
	mov r10, rcx
	mov eax, sciGdiDdDDIAcquireKeyedMutex
	syscall
	ret
HcGdiDdDDIAcquireKeyedMutex ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDIAcquireKeyedMutex:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDIAcquireKeyedMutex PROC
	mov eax, sciGdiDdDDIAcquireKeyedMutex
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDIAcquireKeyedMutex ENDP

ENDIF

END