; Hc/NtGdiDvpGetVideoSignalStatus
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDvpGetVideoSignalStatus:DWORD

.DATA
.CODE

HcGdiDvpGetVideoSignalStatus PROC
	mov r10, rcx
	mov eax, sciGdiDvpGetVideoSignalStatus
	syscall
	ret
HcGdiDvpGetVideoSignalStatus ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDvpGetVideoSignalStatus:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDvpGetVideoSignalStatus PROC
	mov eax, sciGdiDvpGetVideoSignalStatus
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDvpGetVideoSignalStatus ENDP

ENDIF

END