; Hc/NtGdiDDCCIGetTimingReport
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDDCCIGetTimingReport:DWORD

.DATA
.CODE

HcGdiDDCCIGetTimingReport PROC
	mov r10, rcx
	mov eax, sciGdiDDCCIGetTimingReport
	syscall
	ret
HcGdiDDCCIGetTimingReport ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDDCCIGetTimingReport:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDDCCIGetTimingReport PROC
	mov eax, sciGdiDDCCIGetTimingReport
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDDCCIGetTimingReport ENDP

ENDIF

END