; Hc/NtGdiDdDDIAbandonSwapChain
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDIAbandonSwapChain:DWORD

.DATA
.CODE

HcGdiDdDDIAbandonSwapChain PROC
	mov r10, rcx
	mov eax, sciGdiDdDDIAbandonSwapChain
	syscall
	ret
HcGdiDdDDIAbandonSwapChain ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDIAbandonSwapChain:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDIAbandonSwapChain PROC
	mov eax, sciGdiDdDDIAbandonSwapChain
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDIAbandonSwapChain ENDP

ENDIF

END