; Hc/NtGdiDdWaitForVerticalBlank
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdWaitForVerticalBlank:DWORD

.DATA
.CODE

HcGdiDdWaitForVerticalBlank PROC
	mov r10, rcx
	mov eax, sciGdiDdWaitForVerticalBlank
	syscall
	ret
HcGdiDdWaitForVerticalBlank ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdWaitForVerticalBlank:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdWaitForVerticalBlank PROC
	mov eax, sciGdiDdWaitForVerticalBlank
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdWaitForVerticalBlank ENDP

ENDIF

END