; Hc/NtGdiDdDDICreateAllocation
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDICreateAllocation:DWORD

.DATA
.CODE

HcGdiDdDDICreateAllocation PROC
	mov r10, rcx
	mov eax, sciGdiDdDDICreateAllocation
	syscall
	ret
HcGdiDdDDICreateAllocation ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDICreateAllocation:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDICreateAllocation PROC
	mov eax, sciGdiDdDDICreateAllocation
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDICreateAllocation ENDP

ENDIF

END