; Hc/NtGdiDdDDIGetCachedHybridQueryValue
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDIGetCachedHybridQueryValue:DWORD

.DATA
.CODE

HcGdiDdDDIGetCachedHybridQueryValue PROC
	mov r10, rcx
	mov eax, sciGdiDdDDIGetCachedHybridQueryValue
	syscall
	ret
HcGdiDdDDIGetCachedHybridQueryValue ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDIGetCachedHybridQueryValue:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDIGetCachedHybridQueryValue PROC
	mov eax, sciGdiDdDDIGetCachedHybridQueryValue
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDIGetCachedHybridQueryValue ENDP

ENDIF

END