; Hc/NtGdiD3dDrawPrimitives2
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiD3dDrawPrimitives2:DWORD

.DATA
.CODE

HcGdiD3dDrawPrimitives2 PROC
	mov r10, rcx
	mov eax, sciGdiD3dDrawPrimitives2
	syscall
	ret
HcGdiD3dDrawPrimitives2 ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiD3dDrawPrimitives2:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiD3dDrawPrimitives2 PROC
	mov eax, sciGdiD3dDrawPrimitives2
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiD3dDrawPrimitives2 ENDP

ENDIF

END