; Hc/NtGdiDdDDIGetMultiPlaneOverlayCaps
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDIGetMultiPlaneOverlayCaps:DWORD

.DATA
.CODE

HcGdiDdDDIGetMultiPlaneOverlayCaps PROC
	mov r10, rcx
	mov eax, sciGdiDdDDIGetMultiPlaneOverlayCaps
	syscall
	ret
HcGdiDdDDIGetMultiPlaneOverlayCaps ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDIGetMultiPlaneOverlayCaps:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDIGetMultiPlaneOverlayCaps PROC
	mov eax, sciGdiDdDDIGetMultiPlaneOverlayCaps
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDIGetMultiPlaneOverlayCaps ENDP

ENDIF

END