; Hc/NtGdiDdDDIAcquireKeyedMutex2
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDIAcquireKeyedMutex2:DWORD

.DATA
.CODE

HcGdiDdDDIAcquireKeyedMutex2 PROC
	mov r10, rcx
	mov eax, sciGdiDdDDIAcquireKeyedMutex2
	syscall
	ret
HcGdiDdDDIAcquireKeyedMutex2 ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDIAcquireKeyedMutex2:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDIAcquireKeyedMutex2 PROC
	mov eax, sciGdiDdDDIAcquireKeyedMutex2
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDIAcquireKeyedMutex2 ENDP

ENDIF

END