; Hc/NtGdiDdDDISignalSynchronizationObject
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDISignalSynchronizationObject:DWORD

.DATA
.CODE

HcGdiDdDDISignalSynchronizationObject PROC
	mov r10, rcx
	mov eax, sciGdiDdDDISignalSynchronizationObject
	syscall
	ret
HcGdiDdDDISignalSynchronizationObject ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDISignalSynchronizationObject:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDISignalSynchronizationObject PROC
	mov eax, sciGdiDdDDISignalSynchronizationObject
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDISignalSynchronizationObject ENDP

ENDIF

END