; Hc/NtGdiDdDDIDestroyPagingQueue
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDIDestroyPagingQueue:DWORD

.DATA
.CODE

HcGdiDdDDIDestroyPagingQueue PROC
	mov r10, rcx
	mov eax, sciGdiDdDDIDestroyPagingQueue
	syscall
	ret
HcGdiDdDDIDestroyPagingQueue ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDIDestroyPagingQueue:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDIDestroyPagingQueue PROC
	mov eax, sciGdiDdDDIDestroyPagingQueue
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDIDestroyPagingQueue ENDP

ENDIF

END