; Hc/NtGdiDdLock
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdLock:DWORD

.DATA
.CODE

HcGdiDdLock PROC
	mov r10, rcx
	mov eax, sciGdiDdLock
	syscall
	ret
HcGdiDdLock ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdLock:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdLock PROC
	mov eax, sciGdiDdLock
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdLock ENDP

ENDIF

END