; Hc/NtGdiDrawEscape
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDrawEscape:DWORD

.DATA
.CODE

HcGdiDrawEscape PROC
	mov r10, rcx
	mov eax, sciGdiDrawEscape
	syscall
	ret
HcGdiDrawEscape ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDrawEscape:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDrawEscape PROC
	mov eax, sciGdiDrawEscape
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDrawEscape ENDP

ENDIF

END