; Hc/NtGdiDdDDILock
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDILock:DWORD

.DATA
.CODE

HcGdiDdDDILock PROC
	mov r10, rcx
	mov eax, sciGdiDdDDILock
	syscall
	ret
HcGdiDdDDILock ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDILock:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDILock PROC
	mov eax, sciGdiDdDDILock
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDILock ENDP

ENDIF

END