; Hc/NtGdiDdDDICacheHybridQueryValue
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDICacheHybridQueryValue:DWORD

.DATA
.CODE

HcGdiDdDDICacheHybridQueryValue PROC
	mov r10, rcx
	mov eax, sciGdiDdDDICacheHybridQueryValue
	syscall
	ret
HcGdiDdDDICacheHybridQueryValue ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDICacheHybridQueryValue:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDICacheHybridQueryValue PROC
	mov eax, sciGdiDdDDICacheHybridQueryValue
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDICacheHybridQueryValue ENDP

ENDIF

END