; Hc/NtGdiDdAlphaBlt
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdAlphaBlt:DWORD

.DATA
.CODE

HcGdiDdAlphaBlt PROC
	mov r10, rcx
	mov eax, sciGdiDdAlphaBlt
	syscall
	ret
HcGdiDdAlphaBlt ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdAlphaBlt:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdAlphaBlt PROC
	mov eax, sciGdiDdAlphaBlt
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdAlphaBlt ENDP

ENDIF

END