; Hc/NtGdiDdDDISetStereoEnabled
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDISetStereoEnabled:DWORD

.DATA
.CODE

HcGdiDdDDISetStereoEnabled PROC
	mov r10, rcx
	mov eax, sciGdiDdDDISetStereoEnabled
	syscall
	ret
HcGdiDdDDISetStereoEnabled ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDISetStereoEnabled:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDISetStereoEnabled PROC
	mov eax, sciGdiDdDDISetStereoEnabled
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDISetStereoEnabled ENDP

ENDIF

END