; Hc/NtGdiDdDDIFreeGpuVirtualAddress
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDIFreeGpuVirtualAddress:DWORD

.DATA
.CODE

HcGdiDdDDIFreeGpuVirtualAddress PROC
	mov r10, rcx
	mov eax, sciGdiDdDDIFreeGpuVirtualAddress
	syscall
	ret
HcGdiDdDDIFreeGpuVirtualAddress ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDIFreeGpuVirtualAddress:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDIFreeGpuVirtualAddress PROC
	mov eax, sciGdiDdDDIFreeGpuVirtualAddress
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDIFreeGpuVirtualAddress ENDP

ENDIF

END