; Hc/NtGdiD3dContextDestroy
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiD3dContextDestroy:DWORD

.DATA
.CODE

HcGdiD3dContextDestroy PROC
	mov r10, rcx
	mov eax, sciGdiD3dContextDestroy
	syscall
	ret
HcGdiD3dContextDestroy ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiD3dContextDestroy:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiD3dContextDestroy PROC
	mov eax, sciGdiD3dContextDestroy
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiD3dContextDestroy ENDP

ENDIF

END