; Hc/NtGdiDvpGetVideoPortField
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDvpGetVideoPortField:DWORD

.DATA
.CODE

HcGdiDvpGetVideoPortField PROC
	mov r10, rcx
	mov eax, sciGdiDvpGetVideoPortField
	syscall
	ret
HcGdiDvpGetVideoPortField ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDvpGetVideoPortField:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDvpGetVideoPortField PROC
	mov eax, sciGdiDvpGetVideoPortField
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDvpGetVideoPortField ENDP

ENDIF

END