; Hc/NtGdiDdDDIGetContextSchedulingPriority
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDIGetContextSchedulingPriority:DWORD

.DATA
.CODE

HcGdiDdDDIGetContextSchedulingPriority PROC
	mov r10, rcx
	mov eax, sciGdiDdDDIGetContextSchedulingPriority
	syscall
	ret
HcGdiDdDDIGetContextSchedulingPriority ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDIGetContextSchedulingPriority:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDIGetContextSchedulingPriority PROC
	mov eax, sciGdiDdDDIGetContextSchedulingPriority
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDIGetContextSchedulingPriority ENDP

ENDIF

END