; Hc/NtGdiDdDDIConfigureSharedResource
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDIConfigureSharedResource:DWORD

.DATA
.CODE

HcGdiDdDDIConfigureSharedResource PROC
	mov r10, rcx
	mov eax, sciGdiDdDDIConfigureSharedResource
	syscall
	ret
HcGdiDdDDIConfigureSharedResource ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDIConfigureSharedResource:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDIConfigureSharedResource PROC
	mov eax, sciGdiDdDDIConfigureSharedResource
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDIConfigureSharedResource ENDP

ENDIF

END