; Hc/NtGdiDdDDIGetOverlayState
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDIGetOverlayState:DWORD

.DATA
.CODE

HcGdiDdDDIGetOverlayState PROC
	mov r10, rcx
	mov eax, sciGdiDdDDIGetOverlayState
	syscall
	ret
HcGdiDdDDIGetOverlayState ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDIGetOverlayState:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDIGetOverlayState PROC
	mov eax, sciGdiDdDDIGetOverlayState
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDIGetOverlayState ENDP

ENDIF

END