; Hc/NtGdiDdCreateMoComp
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdCreateMoComp:DWORD

.DATA
.CODE

HcGdiDdCreateMoComp PROC
	mov r10, rcx
	mov eax, sciGdiDdCreateMoComp
	syscall
	ret
HcGdiDdCreateMoComp ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdCreateMoComp:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdCreateMoComp PROC
	mov eax, sciGdiDdCreateMoComp
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdCreateMoComp ENDP

ENDIF

END