; Hc/NtGdiDdCreateD3DBuffer
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdCreateD3DBuffer:DWORD

.DATA
.CODE

HcGdiDdCreateD3DBuffer PROC
	mov r10, rcx
	mov eax, sciGdiDdCreateD3DBuffer
	syscall
	ret
HcGdiDdCreateD3DBuffer ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdCreateD3DBuffer:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdCreateD3DBuffer PROC
	mov eax, sciGdiDdCreateD3DBuffer
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdCreateD3DBuffer ENDP

ENDIF

END