; Hc/NtGdiDdGetBltStatus
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdGetBltStatus:DWORD

.DATA
.CODE

HcGdiDdGetBltStatus PROC
	mov r10, rcx
	mov eax, sciGdiDdGetBltStatus
	syscall
	ret
HcGdiDdGetBltStatus ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdGetBltStatus:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdGetBltStatus PROC
	mov eax, sciGdiDdGetBltStatus
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdGetBltStatus ENDP

ENDIF

END