; Hc/NtGdiDdDDICreateContext
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDICreateContext:DWORD

.DATA
.CODE

HcGdiDdDDICreateContext PROC
	mov r10, rcx
	mov eax, sciGdiDdDDICreateContext
	syscall
	ret
HcGdiDdDDICreateContext ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDICreateContext:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDICreateContext PROC
	mov eax, sciGdiDdDDICreateContext
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDICreateContext ENDP

ENDIF

END