; Hc/NtGdiDdDDISubmitSignalSyncObjectsToHwQueue
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDISubmitSignalSyncObjectsToHwQueue:DWORD

.DATA
.CODE

HcGdiDdDDISubmitSignalSyncObjectsToHwQueue PROC
	mov r10, rcx
	mov eax, sciGdiDdDDISubmitSignalSyncObjectsToHwQueue
	syscall
	ret
HcGdiDdDDISubmitSignalSyncObjectsToHwQueue ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDISubmitSignalSyncObjectsToHwQueue:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDISubmitSignalSyncObjectsToHwQueue PROC
	mov eax, sciGdiDdDDISubmitSignalSyncObjectsToHwQueue
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDISubmitSignalSyncObjectsToHwQueue ENDP

ENDIF

END