; Hc/NtGdiDdDDIGetRuntimeData
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDIGetRuntimeData:DWORD

.DATA
.CODE

HcGdiDdDDIGetRuntimeData PROC
	mov r10, rcx
	mov eax, sciGdiDdDDIGetRuntimeData
	syscall
	ret
HcGdiDdDDIGetRuntimeData ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDIGetRuntimeData:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDIGetRuntimeData PROC
	mov eax, sciGdiDdDDIGetRuntimeData
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDIGetRuntimeData ENDP

ENDIF

END