; Hc/NtGdiDdUnattachSurface
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdUnattachSurface:DWORD

.DATA
.CODE

HcGdiDdUnattachSurface PROC
	mov r10, rcx
	mov eax, sciGdiDdUnattachSurface
	syscall
	ret
HcGdiDdUnattachSurface ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdUnattachSurface:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdUnattachSurface PROC
	mov eax, sciGdiDdUnattachSurface
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdUnattachSurface ENDP

ENDIF

END