; Hc/NtGdiDvpGetVideoPortInputFormats
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDvpGetVideoPortInputFormats:DWORD

.DATA
.CODE

HcGdiDvpGetVideoPortInputFormats PROC
	mov r10, rcx
	mov eax, sciGdiDvpGetVideoPortInputFormats
	syscall
	ret
HcGdiDvpGetVideoPortInputFormats ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDvpGetVideoPortInputFormats:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDvpGetVideoPortInputFormats PROC
	mov eax, sciGdiDvpGetVideoPortInputFormats
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDvpGetVideoPortInputFormats ENDP

ENDIF

END