; Hc/NtGdiDdDDICloseAdapter
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDICloseAdapter:DWORD

.DATA
.CODE

HcGdiDdDDICloseAdapter PROC
	mov r10, rcx
	mov eax, sciGdiDdDDICloseAdapter
	syscall
	ret
HcGdiDdDDICloseAdapter ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDICloseAdapter:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDICloseAdapter PROC
	mov eax, sciGdiDdDDICloseAdapter
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDICloseAdapter ENDP

ENDIF

END