; Hc/NtGdiDdDDIOpenSyncObjectNtHandleFromName
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDIOpenSyncObjectNtHandleFromName:DWORD

.DATA
.CODE

HcGdiDdDDIOpenSyncObjectNtHandleFromName PROC
	mov r10, rcx
	mov eax, sciGdiDdDDIOpenSyncObjectNtHandleFromName
	syscall
	ret
HcGdiDdDDIOpenSyncObjectNtHandleFromName ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDIOpenSyncObjectNtHandleFromName:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDIOpenSyncObjectNtHandleFromName PROC
	mov eax, sciGdiDdDDIOpenSyncObjectNtHandleFromName
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDIOpenSyncObjectNtHandleFromName ENDP

ENDIF

END