; Hc/NtGdiDdDDIDispMgrSourceOperation
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDIDispMgrSourceOperation:DWORD

.DATA
.CODE

HcGdiDdDDIDispMgrSourceOperation PROC
	mov r10, rcx
	mov eax, sciGdiDdDDIDispMgrSourceOperation
	syscall
	ret
HcGdiDdDDIDispMgrSourceOperation ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDIDispMgrSourceOperation:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDIDispMgrSourceOperation PROC
	mov eax, sciGdiDdDDIDispMgrSourceOperation
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDIDispMgrSourceOperation ENDP

ENDIF

END