; Hc/NtGdiDeleteColorTransform
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDeleteColorTransform:DWORD

.DATA
.CODE

HcGdiDeleteColorTransform PROC
	mov r10, rcx
	mov eax, sciGdiDeleteColorTransform
	syscall
	ret
HcGdiDeleteColorTransform ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDeleteColorTransform:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDeleteColorTransform PROC
	mov eax, sciGdiDeleteColorTransform
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDeleteColorTransform ENDP

ENDIF

END