; Hc/NtGdiDdGetDxHandle
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdGetDxHandle:DWORD

.DATA
.CODE

HcGdiDdGetDxHandle PROC
	mov r10, rcx
	mov eax, sciGdiDdGetDxHandle
	syscall
	ret
HcGdiDdGetDxHandle ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdGetDxHandle:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdGetDxHandle PROC
	mov eax, sciGdiDdGetDxHandle
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdGetDxHandle ENDP

ENDIF

END