; Hc/NtGdiDdDDIGetProcessSchedulingPriorityBand
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDIGetProcessSchedulingPriorityBand:DWORD

.DATA
.CODE

HcGdiDdDDIGetProcessSchedulingPriorityBand PROC
	mov r10, rcx
	mov eax, sciGdiDdDDIGetProcessSchedulingPriorityBand
	syscall
	ret
HcGdiDdDDIGetProcessSchedulingPriorityBand ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDIGetProcessSchedulingPriorityBand:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDIGetProcessSchedulingPriorityBand PROC
	mov eax, sciGdiDdDDIGetProcessSchedulingPriorityBand
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDIGetProcessSchedulingPriorityBand ENDP

ENDIF

END