; Hc/NtGdiDdDestroyD3DBuffer
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDestroyD3DBuffer:DWORD

.DATA
.CODE

HcGdiDdDestroyD3DBuffer PROC
	mov r10, rcx
	mov eax, sciGdiDdDestroyD3DBuffer
	syscall
	ret
HcGdiDdDestroyD3DBuffer ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDestroyD3DBuffer:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDestroyD3DBuffer PROC
	mov eax, sciGdiDdDestroyD3DBuffer
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDestroyD3DBuffer ENDP

ENDIF

END