; Hc/NtGdiDdDDIDestroyKeyedMutex
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDIDestroyKeyedMutex:DWORD

.DATA
.CODE

HcGdiDdDDIDestroyKeyedMutex PROC
	mov r10, rcx
	mov eax, sciGdiDdDDIDestroyKeyedMutex
	syscall
	ret
HcGdiDdDDIDestroyKeyedMutex ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDIDestroyKeyedMutex:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDIDestroyKeyedMutex PROC
	mov eax, sciGdiDdDDIDestroyKeyedMutex
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDIDestroyKeyedMutex ENDP

ENDIF

END