; Hc/NtGdiDdGetMoCompBuffInfo
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdGetMoCompBuffInfo:DWORD

.DATA
.CODE

HcGdiDdGetMoCompBuffInfo PROC
	mov r10, rcx
	mov eax, sciGdiDdGetMoCompBuffInfo
	syscall
	ret
HcGdiDdGetMoCompBuffInfo ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdGetMoCompBuffInfo:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdGetMoCompBuffInfo PROC
	mov eax, sciGdiDdGetMoCompBuffInfo
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdGetMoCompBuffInfo ENDP

ENDIF

END