; Hc/NtGdiDdDeleteSurfaceObject
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDeleteSurfaceObject:DWORD

.DATA
.CODE

HcGdiDdDeleteSurfaceObject PROC
	mov r10, rcx
	mov eax, sciGdiDdDeleteSurfaceObject
	syscall
	ret
HcGdiDdDeleteSurfaceObject ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDeleteSurfaceObject:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDeleteSurfaceObject PROC
	mov eax, sciGdiDdDeleteSurfaceObject
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDeleteSurfaceObject ENDP

ENDIF

END