; Hc/NtGdiDwmGetSurfaceData
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDwmGetSurfaceData:DWORD

.DATA
.CODE

HcGdiDwmGetSurfaceData PROC
	mov r10, rcx
	mov eax, sciGdiDwmGetSurfaceData
	syscall
	ret
HcGdiDwmGetSurfaceData ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDwmGetSurfaceData:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDwmGetSurfaceData PROC
	mov eax, sciGdiDwmGetSurfaceData
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDwmGetSurfaceData ENDP

ENDIF

END