; Hc/NtGdiDdDDIEnumAdapters
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDIEnumAdapters:DWORD

.DATA
.CODE

HcGdiDdDDIEnumAdapters PROC
	mov r10, rcx
	mov eax, sciGdiDdDDIEnumAdapters
	syscall
	ret
HcGdiDdDDIEnumAdapters ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDIEnumAdapters:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDIEnumAdapters PROC
	mov eax, sciGdiDdDDIEnumAdapters
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDIEnumAdapters ENDP

ENDIF

END