; Hc/NtGdiDescribePixelFormat
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDescribePixelFormat:DWORD

.DATA
.CODE

HcGdiDescribePixelFormat PROC
	mov r10, rcx
	mov eax, sciGdiDescribePixelFormat
	syscall
	ret
HcGdiDescribePixelFormat ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDescribePixelFormat:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDescribePixelFormat PROC
	mov eax, sciGdiDescribePixelFormat
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDescribePixelFormat ENDP

ENDIF

END