; Hc/NtGdiDdDDIOfferAllocations
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDIOfferAllocations:DWORD

.DATA
.CODE

HcGdiDdDDIOfferAllocations PROC
	mov r10, rcx
	mov eax, sciGdiDdDDIOfferAllocations
	syscall
	ret
HcGdiDdDDIOfferAllocations ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDIOfferAllocations:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDIOfferAllocations PROC
	mov eax, sciGdiDdDDIOfferAllocations
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDIOfferAllocations ENDP

ENDIF

END