; Hc/NtGdiDDCCISaveCurrentSettings
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDDCCISaveCurrentSettings:DWORD

.DATA
.CODE

HcGdiDDCCISaveCurrentSettings PROC
	mov r10, rcx
	mov eax, sciGdiDDCCISaveCurrentSettings
	syscall
	ret
HcGdiDDCCISaveCurrentSettings ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDDCCISaveCurrentSettings:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDDCCISaveCurrentSettings PROC
	mov eax, sciGdiDDCCISaveCurrentSettings
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDDCCISaveCurrentSettings ENDP

ENDIF

END