; Hc/NtGdiDdDDINetDispQueryMiracastDisplayDeviceSupport
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDINetDispQueryMiracastDisplayDeviceSupport:DWORD

.DATA
.CODE

HcGdiDdDDINetDispQueryMiracastDisplayDeviceSupport PROC
	mov r10, rcx
	mov eax, sciGdiDdDDINetDispQueryMiracastDisplayDeviceSupport
	syscall
	ret
HcGdiDdDDINetDispQueryMiracastDisplayDeviceSupport ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDINetDispQueryMiracastDisplayDeviceSupport:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDINetDispQueryMiracastDisplayDeviceSupport PROC
	mov eax, sciGdiDdDDINetDispQueryMiracastDisplayDeviceSupport
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDINetDispQueryMiracastDisplayDeviceSupport ENDP

ENDIF

END