; Hc/NtGdiDdDDIGetSetSwapChainMetadata
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdDDIGetSetSwapChainMetadata:DWORD

.DATA
.CODE

HcGdiDdDDIGetSetSwapChainMetadata PROC
	mov r10, rcx
	mov eax, sciGdiDdDDIGetSetSwapChainMetadata
	syscall
	ret
HcGdiDdDDIGetSetSwapChainMetadata ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdDDIGetSetSwapChainMetadata:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdDDIGetSetSwapChainMetadata PROC
	mov eax, sciGdiDdDDIGetSetSwapChainMetadata
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdDDIGetSetSwapChainMetadata ENDP

ENDIF

END