; Hc/NtGdiDdCreateSurface
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdCreateSurface:DWORD

.DATA
.CODE

HcGdiDdCreateSurface PROC
	mov r10, rcx
	mov eax, sciGdiDdCreateSurface
	syscall
	ret
HcGdiDdCreateSurface ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdCreateSurface:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdCreateSurface PROC
	mov eax, sciGdiDdCreateSurface
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdCreateSurface ENDP

ENDIF

END