; Hc/NtGdiDvpGetVideoPortBandwidth
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDvpGetVideoPortBandwidth:DWORD

.DATA
.CODE

HcGdiDvpGetVideoPortBandwidth PROC
	mov r10, rcx
	mov eax, sciGdiDvpGetVideoPortBandwidth
	syscall
	ret
HcGdiDvpGetVideoPortBandwidth ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDvpGetVideoPortBandwidth:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDvpGetVideoPortBandwidth PROC
	mov eax, sciGdiDvpGetVideoPortBandwidth
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDvpGetVideoPortBandwidth ENDP

ENDIF

END