; Hc/NtGdiDdFlip
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiDdFlip:DWORD

.DATA
.CODE

HcGdiDdFlip PROC
	mov r10, rcx
	mov eax, sciGdiDdFlip
	syscall
	ret
HcGdiDdFlip ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiDdFlip:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiDdFlip PROC
	mov eax, sciGdiDdFlip
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiDdFlip ENDP

ENDIF

END