; Hc/NtGdiEngCreateClip
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiEngCreateClip:DWORD

.DATA
.CODE

HcGdiEngCreateClip PROC
	mov r10, rcx
	mov eax, sciGdiEngCreateClip
	syscall
	ret
HcGdiEngCreateClip ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiEngCreateClip:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiEngCreateClip PROC
	mov eax, sciGdiEngCreateClip
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiEngCreateClip ENDP

ENDIF

END