; Hc/NtGdiEngUnlockSurface
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiEngUnlockSurface:DWORD

.DATA
.CODE

HcGdiEngUnlockSurface PROC
	mov r10, rcx
	mov eax, sciGdiEngUnlockSurface
	syscall
	ret
HcGdiEngUnlockSurface ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiEngUnlockSurface:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiEngUnlockSurface PROC
	mov eax, sciGdiEngUnlockSurface
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiEngUnlockSurface ENDP

ENDIF

END