; Hc/NtGdiEngCreateDeviceBitmap
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiEngCreateDeviceBitmap:DWORD

.DATA
.CODE

HcGdiEngCreateDeviceBitmap PROC
	mov r10, rcx
	mov eax, sciGdiEngCreateDeviceBitmap
	syscall
	ret
HcGdiEngCreateDeviceBitmap ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiEngCreateDeviceBitmap:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiEngCreateDeviceBitmap PROC
	mov eax, sciGdiEngCreateDeviceBitmap
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiEngCreateDeviceBitmap ENDP

ENDIF

END