; Hc/NtGdiEngTextOut
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiEngTextOut:DWORD

.DATA
.CODE

HcGdiEngTextOut PROC
	mov r10, rcx
	mov eax, sciGdiEngTextOut
	syscall
	ret
HcGdiEngTextOut ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiEngTextOut:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiEngTextOut PROC
	mov eax, sciGdiEngTextOut
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiEngTextOut ENDP

ENDIF

END