; Hc/NtGdiEngLineTo
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiEngLineTo:DWORD

.DATA
.CODE

HcGdiEngLineTo PROC
	mov r10, rcx
	mov eax, sciGdiEngLineTo
	syscall
	ret
HcGdiEngLineTo ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiEngLineTo:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiEngLineTo PROC
	mov eax, sciGdiEngLineTo
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiEngLineTo ENDP

ENDIF

END