; Hc/NtGdiEngCreateBitmap
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiEngCreateBitmap:DWORD

.DATA
.CODE

HcGdiEngCreateBitmap PROC
	mov r10, rcx
	mov eax, sciGdiEngCreateBitmap
	syscall
	ret
HcGdiEngCreateBitmap ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiEngCreateBitmap:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiEngCreateBitmap PROC
	mov eax, sciGdiEngCreateBitmap
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiEngCreateBitmap ENDP

ENDIF

END