; Hc/NtGdiEngCopyBits
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiEngCopyBits:DWORD

.DATA
.CODE

HcGdiEngCopyBits PROC
	mov r10, rcx
	mov eax, sciGdiEngCopyBits
	syscall
	ret
HcGdiEngCopyBits ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiEngCopyBits:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiEngCopyBits PROC
	mov eax, sciGdiEngCopyBits
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiEngCopyBits ENDP

ENDIF

END