; Hc/NtGdiEnumFontOpen
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiEnumFontOpen:DWORD

.DATA
.CODE

HcGdiEnumFontOpen PROC
	mov r10, rcx
	mov eax, sciGdiEnumFontOpen
	syscall
	ret
HcGdiEnumFontOpen ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiEnumFontOpen:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiEnumFontOpen PROC
	mov eax, sciGdiEnumFontOpen
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiEnumFontOpen ENDP

ENDIF

END