; Hc/NtGdiExtTextOutW
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiExtTextOutW:DWORD

.DATA
.CODE

HcGdiExtTextOutW PROC
	mov r10, rcx
	mov eax, sciGdiExtTextOutW
	syscall
	ret
HcGdiExtTextOutW ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiExtTextOutW:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiExtTextOutW PROC
	mov eax, sciGdiExtTextOutW
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiExtTextOutW ENDP

ENDIF

END