; Hc/NtGdiEngGradientFill
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiEngGradientFill:DWORD

.DATA
.CODE

HcGdiEngGradientFill PROC
	mov r10, rcx
	mov eax, sciGdiEngGradientFill
	syscall
	ret
HcGdiEngGradientFill ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiEngGradientFill:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiEngGradientFill PROC
	mov eax, sciGdiEngGradientFill
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiEngGradientFill ENDP

ENDIF

END