; Hc/NtGdiEnsureDpiDepDefaultGuiFontForPlateau
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiEnsureDpiDepDefaultGuiFontForPlateau:DWORD

.DATA
.CODE

HcGdiEnsureDpiDepDefaultGuiFontForPlateau PROC
	mov r10, rcx
	mov eax, sciGdiEnsureDpiDepDefaultGuiFontForPlateau
	syscall
	ret
HcGdiEnsureDpiDepDefaultGuiFontForPlateau ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiEnsureDpiDepDefaultGuiFontForPlateau:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiEnsureDpiDepDefaultGuiFontForPlateau PROC
	mov eax, sciGdiEnsureDpiDepDefaultGuiFontForPlateau
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiEnsureDpiDepDefaultGuiFontForPlateau ENDP

ENDIF

END