; Hc/NtGdiEngCheckAbort
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiEngCheckAbort:DWORD

.DATA
.CODE

HcGdiEngCheckAbort PROC
	mov r10, rcx
	mov eax, sciGdiEngCheckAbort
	syscall
	ret
HcGdiEngCheckAbort ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiEngCheckAbort:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiEngCheckAbort PROC
	mov eax, sciGdiEngCheckAbort
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiEngCheckAbort ENDP

ENDIF

END