; Hc/NtGdiEngStrokeAndFillPath
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiEngStrokeAndFillPath:DWORD

.DATA
.CODE

HcGdiEngStrokeAndFillPath PROC
	mov r10, rcx
	mov eax, sciGdiEngStrokeAndFillPath
	syscall
	ret
HcGdiEngStrokeAndFillPath ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiEngStrokeAndFillPath:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiEngStrokeAndFillPath PROC
	mov eax, sciGdiEngStrokeAndFillPath
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiEngStrokeAndFillPath ENDP

ENDIF

END