; Hc/NtGdiEngDeletePalette
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiEngDeletePalette:DWORD

.DATA
.CODE

HcGdiEngDeletePalette PROC
	mov r10, rcx
	mov eax, sciGdiEngDeletePalette
	syscall
	ret
HcGdiEngDeletePalette ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiEngDeletePalette:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiEngDeletePalette PROC
	mov eax, sciGdiEngDeletePalette
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiEngDeletePalette ENDP

ENDIF

END