; Hc/NtGdiEnumFontChunk
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiEnumFontChunk:DWORD

.DATA
.CODE

HcGdiEnumFontChunk PROC
	mov r10, rcx
	mov eax, sciGdiEnumFontChunk
	syscall
	ret
HcGdiEnumFontChunk ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiEnumFontChunk:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiEnumFontChunk PROC
	mov eax, sciGdiEnumFontChunk
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiEnumFontChunk ENDP

ENDIF

END