; Hc/NtGdiExtSelectClipRgn
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiExtSelectClipRgn:DWORD

.DATA
.CODE

HcGdiExtSelectClipRgn PROC
	mov r10, rcx
	mov eax, sciGdiExtSelectClipRgn
	syscall
	ret
HcGdiExtSelectClipRgn ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiExtSelectClipRgn:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiExtSelectClipRgn PROC
	mov eax, sciGdiExtSelectClipRgn
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiExtSelectClipRgn ENDP

ENDIF

END