; Hc/NtGdiFONTOBJ_vGetInfo
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiFONTOBJ_vGetInfo:DWORD

.DATA
.CODE

HcGdiFONTOBJ_vGetInfo PROC
	mov r10, rcx
	mov eax, sciGdiFONTOBJ_vGetInfo
	syscall
	ret
HcGdiFONTOBJ_vGetInfo ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiFONTOBJ_vGetInfo:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiFONTOBJ_vGetInfo PROC
	mov eax, sciGdiFONTOBJ_vGetInfo
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiFONTOBJ_vGetInfo ENDP

ENDIF

END