; Hc/NtGdiFillPath
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiFillPath:DWORD

.DATA
.CODE

HcGdiFillPath PROC
	mov r10, rcx
	mov eax, sciGdiFillPath
	syscall
	ret
HcGdiFillPath ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiFillPath:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiFillPath PROC
	mov eax, sciGdiFillPath
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiFillPath ENDP

ENDIF

END