; Hc/NtGdiFONTOBJ_pfdg
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiFONTOBJ_pfdg:DWORD

.DATA
.CODE

HcGdiFONTOBJ_pfdg PROC
	mov r10, rcx
	mov eax, sciGdiFONTOBJ_pfdg
	syscall
	ret
HcGdiFONTOBJ_pfdg ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiFONTOBJ_pfdg:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiFONTOBJ_pfdg PROC
	mov eax, sciGdiFONTOBJ_pfdg
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiFONTOBJ_pfdg ENDP

ENDIF

END