; Hc/NtGdiFONTOBJ_cGetGlyphs
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiFONTOBJ_cGetGlyphs:DWORD

.DATA
.CODE

HcGdiFONTOBJ_cGetGlyphs PROC
	mov r10, rcx
	mov eax, sciGdiFONTOBJ_cGetGlyphs
	syscall
	ret
HcGdiFONTOBJ_cGetGlyphs ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiFONTOBJ_cGetGlyphs:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiFONTOBJ_cGetGlyphs PROC
	mov eax, sciGdiFONTOBJ_cGetGlyphs
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiFONTOBJ_cGetGlyphs ENDP

ENDIF

END