; Hc/NtGdiGetAppClipBox
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiGetAppClipBox:DWORD

.DATA
.CODE

HcGdiGetAppClipBox PROC
	mov r10, rcx
	mov eax, sciGdiGetAppClipBox
	syscall
	ret
HcGdiGetAppClipBox ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiGetAppClipBox:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiGetAppClipBox PROC
	mov eax, sciGdiGetAppClipBox
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiGetAppClipBox ENDP

ENDIF

END