; Hc/NtGdiGetCharacterPlacementW
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiGetCharacterPlacementW:DWORD

.DATA
.CODE

HcGdiGetCharacterPlacementW PROC
	mov r10, rcx
	mov eax, sciGdiGetCharacterPlacementW
	syscall
	ret
HcGdiGetCharacterPlacementW ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiGetCharacterPlacementW:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiGetCharacterPlacementW PROC
	mov eax, sciGdiGetCharacterPlacementW
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiGetCharacterPlacementW ENDP

ENDIF

END