; Hc/NtGdiGetGammaRampCapability
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiGetGammaRampCapability:DWORD

.DATA
.CODE

HcGdiGetGammaRampCapability PROC
	mov r10, rcx
	mov eax, sciGdiGetGammaRampCapability
	syscall
	ret
HcGdiGetGammaRampCapability ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiGetGammaRampCapability:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiGetGammaRampCapability PROC
	mov eax, sciGdiGetGammaRampCapability
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiGetGammaRampCapability ENDP

ENDIF

END