; Hc/NtGdiGetSystemPaletteUse
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiGetSystemPaletteUse:DWORD

.DATA
.CODE

HcGdiGetSystemPaletteUse PROC
	mov r10, rcx
	mov eax, sciGdiGetSystemPaletteUse
	syscall
	ret
HcGdiGetSystemPaletteUse ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiGetSystemPaletteUse:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiGetSystemPaletteUse PROC
	mov eax, sciGdiGetSystemPaletteUse
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiGetSystemPaletteUse ENDP

ENDIF

END