; Hc/NtGdiGetNearestPaletteIndex
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiGetNearestPaletteIndex:DWORD

.DATA
.CODE

HcGdiGetNearestPaletteIndex PROC
	mov r10, rcx
	mov eax, sciGdiGetNearestPaletteIndex
	syscall
	ret
HcGdiGetNearestPaletteIndex ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiGetNearestPaletteIndex:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiGetNearestPaletteIndex PROC
	mov eax, sciGdiGetNearestPaletteIndex
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiGetNearestPaletteIndex ENDP

ENDIF

END