; Hc/NtGdiGetNumberOfPhysicalMonitors
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiGetNumberOfPhysicalMonitors:DWORD

.DATA
.CODE

HcGdiGetNumberOfPhysicalMonitors PROC
	mov r10, rcx
	mov eax, sciGdiGetNumberOfPhysicalMonitors
	syscall
	ret
HcGdiGetNumberOfPhysicalMonitors ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiGetNumberOfPhysicalMonitors:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiGetNumberOfPhysicalMonitors PROC
	mov eax, sciGdiGetNumberOfPhysicalMonitors
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiGetNumberOfPhysicalMonitors ENDP

ENDIF

END