; Hc/NtGdiGetTextExtent
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiGetTextExtent:DWORD

.DATA
.CODE

HcGdiGetTextExtent PROC
	mov r10, rcx
	mov eax, sciGdiGetTextExtent
	syscall
	ret
HcGdiGetTextExtent ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiGetTextExtent:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiGetTextExtent PROC
	mov eax, sciGdiGetTextExtent
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiGetTextExtent ENDP

ENDIF

END