; Hc/NtGdiGetProcessSessionFonts
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiGetProcessSessionFonts:DWORD

.DATA
.CODE

HcGdiGetProcessSessionFonts PROC
	mov r10, rcx
	mov eax, sciGdiGetProcessSessionFonts
	syscall
	ret
HcGdiGetProcessSessionFonts ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiGetProcessSessionFonts:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiGetProcessSessionFonts PROC
	mov eax, sciGdiGetProcessSessionFonts
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiGetProcessSessionFonts ENDP

ENDIF

END