; Hc/NtGdiGetPublicFontTableChangeCookie
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiGetPublicFontTableChangeCookie:DWORD

.DATA
.CODE

HcGdiGetPublicFontTableChangeCookie PROC
	mov r10, rcx
	mov eax, sciGdiGetPublicFontTableChangeCookie
	syscall
	ret
HcGdiGetPublicFontTableChangeCookie ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiGetPublicFontTableChangeCookie:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiGetPublicFontTableChangeCookie PROC
	mov eax, sciGdiGetPublicFontTableChangeCookie
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiGetPublicFontTableChangeCookie ENDP

ENDIF

END