; Hc/NtGdiGetDCPoint
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiGetDCPoint:DWORD

.DATA
.CODE

HcGdiGetDCPoint PROC
	mov r10, rcx
	mov eax, sciGdiGetDCPoint
	syscall
	ret
HcGdiGetDCPoint ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiGetDCPoint:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiGetDCPoint PROC
	mov eax, sciGdiGetDCPoint
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiGetDCPoint ENDP

ENDIF

END