; Hc/NtGdiGetTextCharsetInfo
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiGetTextCharsetInfo:DWORD

.DATA
.CODE

HcGdiGetTextCharsetInfo PROC
	mov r10, rcx
	mov eax, sciGdiGetTextCharsetInfo
	syscall
	ret
HcGdiGetTextCharsetInfo ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiGetTextCharsetInfo:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiGetTextCharsetInfo PROC
	mov eax, sciGdiGetTextCharsetInfo
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiGetTextCharsetInfo ENDP

ENDIF

END