; Hc/NtGdiGetObjectBitmapHandle
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiGetObjectBitmapHandle:DWORD

.DATA
.CODE

HcGdiGetObjectBitmapHandle PROC
	mov r10, rcx
	mov eax, sciGdiGetObjectBitmapHandle
	syscall
	ret
HcGdiGetObjectBitmapHandle ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiGetObjectBitmapHandle:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiGetObjectBitmapHandle PROC
	mov eax, sciGdiGetObjectBitmapHandle
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiGetObjectBitmapHandle ENDP

ENDIF

END