; Hc/NtGdiGetSuggestedOPMProtectedOutputArraySize
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiGetSuggestedOPMProtectedOutputArraySize:DWORD

.DATA
.CODE

HcGdiGetSuggestedOPMProtectedOutputArraySize PROC
	mov r10, rcx
	mov eax, sciGdiGetSuggestedOPMProtectedOutputArraySize
	syscall
	ret
HcGdiGetSuggestedOPMProtectedOutputArraySize ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiGetSuggestedOPMProtectedOutputArraySize:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiGetSuggestedOPMProtectedOutputArraySize PROC
	mov eax, sciGdiGetSuggestedOPMProtectedOutputArraySize
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiGetSuggestedOPMProtectedOutputArraySize ENDP

ENDIF

END