; Hc/NtGdiGetCharABCWidthsW
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiGetCharABCWidthsW:DWORD

.DATA
.CODE

HcGdiGetCharABCWidthsW PROC
	mov r10, rcx
	mov eax, sciGdiGetCharABCWidthsW
	syscall
	ret
HcGdiGetCharABCWidthsW ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiGetCharABCWidthsW:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiGetCharABCWidthsW PROC
	mov eax, sciGdiGetCharABCWidthsW
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiGetCharABCWidthsW ENDP

ENDIF

END