; Hc/NtGdiGetFontFileData
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiGetFontFileData:DWORD

.DATA
.CODE

HcGdiGetFontFileData PROC
	mov r10, rcx
	mov eax, sciGdiGetFontFileData
	syscall
	ret
HcGdiGetFontFileData ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiGetFontFileData:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiGetFontFileData PROC
	mov eax, sciGdiGetFontFileData
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiGetFontFileData ENDP

ENDIF

END