; Hc/NtGdiGetFontData
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiGetFontData:DWORD

.DATA
.CODE

HcGdiGetFontData PROC
	mov r10, rcx
	mov eax, sciGdiGetFontData
	syscall
	ret
HcGdiGetFontData ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiGetFontData:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiGetFontData PROC
	mov eax, sciGdiGetFontData
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiGetFontData ENDP

ENDIF

END