; Hc/NtGdiGetDCDpiScaleValue
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiGetDCDpiScaleValue:DWORD

.DATA
.CODE

HcGdiGetDCDpiScaleValue PROC
	mov r10, rcx
	mov eax, sciGdiGetDCDpiScaleValue
	syscall
	ret
HcGdiGetDCDpiScaleValue ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiGetDCDpiScaleValue:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiGetDCDpiScaleValue PROC
	mov eax, sciGdiGetDCDpiScaleValue
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiGetDCDpiScaleValue ENDP

ENDIF

END