; Hc/NtGdiGetTransform
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiGetTransform:DWORD

.DATA
.CODE

HcGdiGetTransform PROC
	mov r10, rcx
	mov eax, sciGdiGetTransform
	syscall
	ret
HcGdiGetTransform ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiGetTransform:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiGetTransform PROC
	mov eax, sciGdiGetTransform
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiGetTransform ENDP

ENDIF

END