; Hc/NtGdiGetBitmapDpiScaleValue
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiGetBitmapDpiScaleValue:DWORD

.DATA
.CODE

HcGdiGetBitmapDpiScaleValue PROC
	mov r10, rcx
	mov eax, sciGdiGetBitmapDpiScaleValue
	syscall
	ret
HcGdiGetBitmapDpiScaleValue ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiGetBitmapDpiScaleValue:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiGetBitmapDpiScaleValue PROC
	mov eax, sciGdiGetBitmapDpiScaleValue
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiGetBitmapDpiScaleValue ENDP

ENDIF

END