; Hc/NtGdiGetEmbedFonts
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiGetEmbedFonts:DWORD

.DATA
.CODE

HcGdiGetEmbedFonts PROC
	mov r10, rcx
	mov eax, sciGdiGetEmbedFonts
	syscall
	ret
HcGdiGetEmbedFonts ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiGetEmbedFonts:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiGetEmbedFonts PROC
	mov eax, sciGdiGetEmbedFonts
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiGetEmbedFonts ENDP

ENDIF

END