; Hc/NtGdiGetRandomRgn
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiGetRandomRgn:DWORD

.DATA
.CODE

HcGdiGetRandomRgn PROC
	mov r10, rcx
	mov eax, sciGdiGetRandomRgn
	syscall
	ret
HcGdiGetRandomRgn ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiGetRandomRgn:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiGetRandomRgn PROC
	mov eax, sciGdiGetRandomRgn
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiGetRandomRgn ENDP

ENDIF

END