; Hc/NtGdiGetDeviceCaps
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiGetDeviceCaps:DWORD

.DATA
.CODE

HcGdiGetDeviceCaps PROC
	mov r10, rcx
	mov eax, sciGdiGetDeviceCaps
	syscall
	ret
HcGdiGetDeviceCaps ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiGetDeviceCaps:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiGetDeviceCaps PROC
	mov eax, sciGdiGetDeviceCaps
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiGetDeviceCaps ENDP

ENDIF

END