; Hc/NtGdiGetDhpdev
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiGetDhpdev:DWORD

.DATA
.CODE

HcGdiGetDhpdev PROC
	mov r10, rcx
	mov eax, sciGdiGetDhpdev
	syscall
	ret
HcGdiGetDhpdev ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiGetDhpdev:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiGetDhpdev PROC
	mov eax, sciGdiGetDhpdev
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiGetDhpdev ENDP

ENDIF

END