; Hc/NtGdiGetBoundsRect
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiGetBoundsRect:DWORD

.DATA
.CODE

HcGdiGetBoundsRect PROC
	mov r10, rcx
	mov eax, sciGdiGetBoundsRect
	syscall
	ret
HcGdiGetBoundsRect ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiGetBoundsRect:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiGetBoundsRect PROC
	mov eax, sciGdiGetBoundsRect
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiGetBoundsRect ENDP

ENDIF

END