; Hc/NtGdiGetCharSet
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiGetCharSet:DWORD

.DATA
.CODE

HcGdiGetCharSet PROC
	mov r10, rcx
	mov eax, sciGdiGetCharSet
	syscall
	ret
HcGdiGetCharSet ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiGetCharSet:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiGetCharSet PROC
	mov eax, sciGdiGetCharSet
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiGetCharSet ENDP

ENDIF

END