; Hc/NtGdiGetBitmapBits
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiGetBitmapBits:DWORD

.DATA
.CODE

HcGdiGetBitmapBits PROC
	mov r10, rcx
	mov eax, sciGdiGetBitmapBits
	syscall
	ret
HcGdiGetBitmapBits ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiGetBitmapBits:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiGetBitmapBits PROC
	mov eax, sciGdiGetBitmapBits
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiGetBitmapBits ENDP

ENDIF

END