; Hc/NtGdiGetStringBitmapW
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiGetStringBitmapW:DWORD

.DATA
.CODE

HcGdiGetStringBitmapW PROC
	mov r10, rcx
	mov eax, sciGdiGetStringBitmapW
	syscall
	ret
HcGdiGetStringBitmapW ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiGetStringBitmapW:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiGetStringBitmapW PROC
	mov eax, sciGdiGetStringBitmapW
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiGetStringBitmapW ENDP

ENDIF

END