; Hc/NtGdiGetDIBitsInternal
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiGetDIBitsInternal:DWORD

.DATA
.CODE

HcGdiGetDIBitsInternal PROC
	mov r10, rcx
	mov eax, sciGdiGetDIBitsInternal
	syscall
	ret
HcGdiGetDIBitsInternal ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiGetDIBitsInternal:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiGetDIBitsInternal PROC
	mov eax, sciGdiGetDIBitsInternal
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiGetDIBitsInternal ENDP

ENDIF

END