; Hc/NtGdiGetLinkedUFIs
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiGetLinkedUFIs:DWORD

.DATA
.CODE

HcGdiGetLinkedUFIs PROC
	mov r10, rcx
	mov eax, sciGdiGetLinkedUFIs
	syscall
	ret
HcGdiGetLinkedUFIs ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiGetLinkedUFIs:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiGetLinkedUFIs PROC
	mov eax, sciGdiGetLinkedUFIs
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiGetLinkedUFIs ENDP

ENDIF

END