; Hc/NtGdiGetOPMInformation
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiGetOPMInformation:DWORD

.DATA
.CODE

HcGdiGetOPMInformation PROC
	mov r10, rcx
	mov eax, sciGdiGetOPMInformation
	syscall
	ret
HcGdiGetOPMInformation ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiGetOPMInformation:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiGetOPMInformation PROC
	mov eax, sciGdiGetOPMInformation
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiGetOPMInformation ENDP

ENDIF

END