; Hc/NtGdiHLSurfSetInformation
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiHLSurfSetInformation:DWORD

.DATA
.CODE

HcGdiHLSurfSetInformation PROC
	mov r10, rcx
	mov eax, sciGdiHLSurfSetInformation
	syscall
	ret
HcGdiHLSurfSetInformation ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiHLSurfSetInformation:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiHLSurfSetInformation PROC
	mov eax, sciGdiHLSurfSetInformation
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiHLSurfSetInformation ENDP

ENDIF

END