; Hc/NtGdiIcmBrushInfo
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiIcmBrushInfo:DWORD

.DATA
.CODE

HcGdiIcmBrushInfo PROC
	mov r10, rcx
	mov eax, sciGdiIcmBrushInfo
	syscall
	ret
HcGdiIcmBrushInfo ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiIcmBrushInfo:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiIcmBrushInfo PROC
	mov eax, sciGdiIcmBrushInfo
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiIcmBrushInfo ENDP

ENDIF

END