; Hc/NtGdiIntersectClipRect
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiIntersectClipRect:DWORD

.DATA
.CODE

HcGdiIntersectClipRect PROC
	mov r10, rcx
	mov eax, sciGdiIntersectClipRect
	syscall
	ret
HcGdiIntersectClipRect ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiIntersectClipRect:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiIntersectClipRect PROC
	mov eax, sciGdiIntersectClipRect
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiIntersectClipRect ENDP

ENDIF

END