; Hc/NtGdiInvertRgn
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiInvertRgn:DWORD

.DATA
.CODE

HcGdiInvertRgn PROC
	mov r10, rcx
	mov eax, sciGdiInvertRgn
	syscall
	ret
HcGdiInvertRgn ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiInvertRgn:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiInvertRgn PROC
	mov eax, sciGdiInvertRgn
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiInvertRgn ENDP

ENDIF

END