; Hc/NtGdiOpenDCW
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiOpenDCW:DWORD

.DATA
.CODE

HcGdiOpenDCW PROC
	mov r10, rcx
	mov eax, sciGdiOpenDCW
	syscall
	ret
HcGdiOpenDCW ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiOpenDCW:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiOpenDCW PROC
	mov eax, sciGdiOpenDCW
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiOpenDCW ENDP

ENDIF

END