; Hc/NtGdiOffsetClipRgn
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiOffsetClipRgn:DWORD

.DATA
.CODE

HcGdiOffsetClipRgn PROC
	mov r10, rcx
	mov eax, sciGdiOffsetClipRgn
	syscall
	ret
HcGdiOffsetClipRgn ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiOffsetClipRgn:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiOffsetClipRgn PROC
	mov eax, sciGdiOffsetClipRgn
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiOffsetClipRgn ENDP

ENDIF

END