; Hc/NtGdiPATHOBJ_vEnumStart
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiPATHOBJ_vEnumStart:DWORD

.DATA
.CODE

HcGdiPATHOBJ_vEnumStart PROC
	mov r10, rcx
	mov eax, sciGdiPATHOBJ_vEnumStart
	syscall
	ret
HcGdiPATHOBJ_vEnumStart ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiPATHOBJ_vEnumStart:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiPATHOBJ_vEnumStart PROC
	mov eax, sciGdiPATHOBJ_vEnumStart
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiPATHOBJ_vEnumStart ENDP

ENDIF

END