; Hc/NtGdiPatBlt
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiPatBlt:DWORD

.DATA
.CODE

HcGdiPatBlt PROC
	mov r10, rcx
	mov eax, sciGdiPatBlt
	syscall
	ret
HcGdiPatBlt ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiPatBlt:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiPatBlt PROC
	mov eax, sciGdiPatBlt
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiPatBlt ENDP

ENDIF

END