; Hc/NtGdiPATHOBJ_vEnumStartClipLines
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiPATHOBJ_vEnumStartClipLines:DWORD

.DATA
.CODE

HcGdiPATHOBJ_vEnumStartClipLines PROC
	mov r10, rcx
	mov eax, sciGdiPATHOBJ_vEnumStartClipLines
	syscall
	ret
HcGdiPATHOBJ_vEnumStartClipLines ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiPATHOBJ_vEnumStartClipLines:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiPATHOBJ_vEnumStartClipLines PROC
	mov eax, sciGdiPATHOBJ_vEnumStartClipLines
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiPATHOBJ_vEnumStartClipLines ENDP

ENDIF

END