; Hc/NtGdiPlgBlt
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiPlgBlt:DWORD

.DATA
.CODE

HcGdiPlgBlt PROC
	mov r10, rcx
	mov eax, sciGdiPlgBlt
	syscall
	ret
HcGdiPlgBlt ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiPlgBlt:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiPlgBlt PROC
	mov eax, sciGdiPlgBlt
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiPlgBlt ENDP

ENDIF

END