; Hc/NtGdiPathToRegion
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiPathToRegion:DWORD

.DATA
.CODE

HcGdiPathToRegion PROC
	mov r10, rcx
	mov eax, sciGdiPathToRegion
	syscall
	ret
HcGdiPathToRegion ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiPathToRegion:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiPathToRegion PROC
	mov eax, sciGdiPathToRegion
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiPathToRegion ENDP

ENDIF

END