; Hc/NtGdiPATHOBJ_bEnum
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiPATHOBJ_bEnum:DWORD

.DATA
.CODE

HcGdiPATHOBJ_bEnum PROC
	mov r10, rcx
	mov eax, sciGdiPATHOBJ_bEnum
	syscall
	ret
HcGdiPATHOBJ_bEnum ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiPATHOBJ_bEnum:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiPATHOBJ_bEnum PROC
	mov eax, sciGdiPATHOBJ_bEnum
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiPATHOBJ_bEnum ENDP

ENDIF

END