; Hc/NtGdiRectInRegion
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiRectInRegion:DWORD

.DATA
.CODE

HcGdiRectInRegion PROC
	mov r10, rcx
	mov eax, sciGdiRectInRegion
	syscall
	ret
HcGdiRectInRegion ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiRectInRegion:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiRectInRegion PROC
	mov eax, sciGdiRectInRegion
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiRectInRegion ENDP

ENDIF

END