; Hc/NtGdiRemoveMergeFont
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiRemoveMergeFont:DWORD

.DATA
.CODE

HcGdiRemoveMergeFont PROC
	mov r10, rcx
	mov eax, sciGdiRemoveMergeFont
	syscall
	ret
HcGdiRemoveMergeFont ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiRemoveMergeFont:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiRemoveMergeFont PROC
	mov eax, sciGdiRemoveMergeFont
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiRemoveMergeFont ENDP

ENDIF

END