; Hc/NtGdiRectVisible
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiRectVisible:DWORD

.DATA
.CODE

HcGdiRectVisible PROC
	mov r10, rcx
	mov eax, sciGdiRectVisible
	syscall
	ret
HcGdiRectVisible ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiRectVisible:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiRectVisible PROC
	mov eax, sciGdiRectVisible
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiRectVisible ENDP

ENDIF

END