; Hc/NtGdiRemoveFontMemResourceEx
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiRemoveFontMemResourceEx:DWORD

.DATA
.CODE

HcGdiRemoveFontMemResourceEx PROC
	mov r10, rcx
	mov eax, sciGdiRemoveFontMemResourceEx
	syscall
	ret
HcGdiRemoveFontMemResourceEx ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiRemoveFontMemResourceEx:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiRemoveFontMemResourceEx PROC
	mov eax, sciGdiRemoveFontMemResourceEx
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiRemoveFontMemResourceEx ENDP

ENDIF

END