; Hc/NtGdiRoundRect
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiRoundRect:DWORD

.DATA
.CODE

HcGdiRoundRect PROC
	mov r10, rcx
	mov eax, sciGdiRoundRect
	syscall
	ret
HcGdiRoundRect ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiRoundRect:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiRoundRect PROC
	mov eax, sciGdiRoundRect
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiRoundRect ENDP

ENDIF

END