; Hc/NtGdiSTROBJ_bEnumPositionsOnly
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiSTROBJ_bEnumPositionsOnly:DWORD

.DATA
.CODE

HcGdiSTROBJ_bEnumPositionsOnly PROC
	mov r10, rcx
	mov eax, sciGdiSTROBJ_bEnumPositionsOnly
	syscall
	ret
HcGdiSTROBJ_bEnumPositionsOnly ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiSTROBJ_bEnumPositionsOnly:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiSTROBJ_bEnumPositionsOnly PROC
	mov eax, sciGdiSTROBJ_bEnumPositionsOnly
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiSTROBJ_bEnumPositionsOnly ENDP

ENDIF

END