; Hc/NtGdiStartDoc
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiStartDoc:DWORD

.DATA
.CODE

HcGdiStartDoc PROC
	mov r10, rcx
	mov eax, sciGdiStartDoc
	syscall
	ret
HcGdiStartDoc ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiStartDoc:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiStartDoc PROC
	mov eax, sciGdiStartDoc
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiStartDoc ENDP

ENDIF

END