; Hc/NtGdiSelectBitmap
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiSelectBitmap:DWORD

.DATA
.CODE

HcGdiSelectBitmap PROC
	mov r10, rcx
	mov eax, sciGdiSelectBitmap
	syscall
	ret
HcGdiSelectBitmap ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiSelectBitmap:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiSelectBitmap PROC
	mov eax, sciGdiSelectBitmap
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiSelectBitmap ENDP

ENDIF

END