; Hc/NtGdiSetColorSpace
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiSetColorSpace:DWORD

.DATA
.CODE

HcGdiSetColorSpace PROC
	mov r10, rcx
	mov eax, sciGdiSetColorSpace
	syscall
	ret
HcGdiSetColorSpace ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiSetColorSpace:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiSetColorSpace PROC
	mov eax, sciGdiSetColorSpace
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiSetColorSpace ENDP

ENDIF

END