; Hc/NtGdiSetRectRgn
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiSetRectRgn:DWORD

.DATA
.CODE

HcGdiSetRectRgn PROC
	mov r10, rcx
	mov eax, sciGdiSetRectRgn
	syscall
	ret
HcGdiSetRectRgn ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiSetRectRgn:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiSetRectRgn PROC
	mov eax, sciGdiSetRectRgn
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiSetRectRgn ENDP

ENDIF

END