; Hc/NtGdiSTROBJ_bGetAdvanceWidths
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiSTROBJ_bGetAdvanceWidths:DWORD

.DATA
.CODE

HcGdiSTROBJ_bGetAdvanceWidths PROC
	mov r10, rcx
	mov eax, sciGdiSTROBJ_bGetAdvanceWidths
	syscall
	ret
HcGdiSTROBJ_bGetAdvanceWidths ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiSTROBJ_bGetAdvanceWidths:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiSTROBJ_bGetAdvanceWidths PROC
	mov eax, sciGdiSTROBJ_bGetAdvanceWidths
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiSTROBJ_bGetAdvanceWidths ENDP

ENDIF

END