; Hc/NtGdiSetFontEnumeration
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiSetFontEnumeration:DWORD

.DATA
.CODE

HcGdiSetFontEnumeration PROC
	mov r10, rcx
	mov eax, sciGdiSetFontEnumeration
	syscall
	ret
HcGdiSetFontEnumeration ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiSetFontEnumeration:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiSetFontEnumeration PROC
	mov eax, sciGdiSetFontEnumeration
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiSetFontEnumeration ENDP

ENDIF

END