; Hc/NtGdiSetPixel
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiSetPixel:DWORD

.DATA
.CODE

HcGdiSetPixel PROC
	mov r10, rcx
	mov eax, sciGdiSetPixel
	syscall
	ret
HcGdiSetPixel ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiSetPixel:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiSetPixel PROC
	mov eax, sciGdiSetPixel
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiSetPixel ENDP

ENDIF

END