; Hc/NtGdiSaveDC
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiSaveDC:DWORD

.DATA
.CODE

HcGdiSaveDC PROC
	mov r10, rcx
	mov eax, sciGdiSaveDC
	syscall
	ret
HcGdiSaveDC ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiSaveDC:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiSaveDC PROC
	mov eax, sciGdiSaveDC
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiSaveDC ENDP

ENDIF

END