; Hc/NtGdiSetVirtualResolution
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiSetVirtualResolution:DWORD

.DATA
.CODE

HcGdiSetVirtualResolution PROC
	mov r10, rcx
	mov eax, sciGdiSetVirtualResolution
	syscall
	ret
HcGdiSetVirtualResolution ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiSetVirtualResolution:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiSetVirtualResolution PROC
	mov eax, sciGdiSetVirtualResolution
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiSetVirtualResolution ENDP

ENDIF

END