; Hc/NtGdiScaleValues
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiScaleValues:DWORD

.DATA
.CODE

HcGdiScaleValues PROC
	mov r10, rcx
	mov eax, sciGdiScaleValues
	syscall
	ret
HcGdiScaleValues ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiScaleValues:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiScaleValues PROC
	mov eax, sciGdiScaleValues
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiScaleValues ENDP

ENDIF

END