; Hc/NtGdiSetSystemPaletteUse
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiSetSystemPaletteUse:DWORD

.DATA
.CODE

HcGdiSetSystemPaletteUse PROC
	mov r10, rcx
	mov eax, sciGdiSetSystemPaletteUse
	syscall
	ret
HcGdiSetSystemPaletteUse ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiSetSystemPaletteUse:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiSetSystemPaletteUse PROC
	mov eax, sciGdiSetSystemPaletteUse
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiSetSystemPaletteUse ENDP

ENDIF

END