; Hc/NtGdiSwapBuffers
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiSwapBuffers:DWORD

.DATA
.CODE

HcGdiSwapBuffers PROC
	mov r10, rcx
	mov eax, sciGdiSwapBuffers
	syscall
	ret
HcGdiSwapBuffers ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiSwapBuffers:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiSwapBuffers PROC
	mov eax, sciGdiSwapBuffers
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiSwapBuffers ENDP

ENDIF

END