; Hc/NtGdiTransformPoints
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiTransformPoints:DWORD

.DATA
.CODE

HcGdiTransformPoints PROC
	mov r10, rcx
	mov eax, sciGdiTransformPoints
	syscall
	ret
HcGdiTransformPoints ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiTransformPoints:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiTransformPoints PROC
	mov eax, sciGdiTransformPoints
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiTransformPoints ENDP

ENDIF

END