; Hc/NtGdiTransparentBlt
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiTransparentBlt:DWORD

.DATA
.CODE

HcGdiTransparentBlt PROC
	mov r10, rcx
	mov eax, sciGdiTransparentBlt
	syscall
	ret
HcGdiTransparentBlt ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiTransparentBlt:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiTransparentBlt PROC
	mov eax, sciGdiTransparentBlt
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiTransparentBlt ENDP

ENDIF

END