; Hc/NtGdiUpdateTransform
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiUpdateTransform:DWORD

.DATA
.CODE

HcGdiUpdateTransform PROC
	mov r10, rcx
	mov eax, sciGdiUpdateTransform
	syscall
	ret
HcGdiUpdateTransform ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiUpdateTransform:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiUpdateTransform PROC
	mov eax, sciGdiUpdateTransform
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiUpdateTransform ENDP

ENDIF

END