; Hc/NtGdiUnmapMemFont
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiUnmapMemFont:DWORD

.DATA
.CODE

HcGdiUnmapMemFont PROC
	mov r10, rcx
	mov eax, sciGdiUnmapMemFont
	syscall
	ret
HcGdiUnmapMemFont ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiUnmapMemFont:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiUnmapMemFont PROC
	mov eax, sciGdiUnmapMemFont
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiUnmapMemFont ENDP

ENDIF

END