; Hc/NtGdiXLATEOBJ_cGetPalette
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiXLATEOBJ_cGetPalette:DWORD

.DATA
.CODE

HcGdiXLATEOBJ_cGetPalette PROC
	mov r10, rcx
	mov eax, sciGdiXLATEOBJ_cGetPalette
	syscall
	ret
HcGdiXLATEOBJ_cGetPalette ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiXLATEOBJ_cGetPalette:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiXLATEOBJ_cGetPalette PROC
	mov eax, sciGdiXLATEOBJ_cGetPalette
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiXLATEOBJ_cGetPalette ENDP

ENDIF

END