; Hc/NtGdiXFORMOBJ_iGetXform
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGdiXFORMOBJ_iGetXform:DWORD

.DATA
.CODE

HcGdiXFORMOBJ_iGetXform PROC
	mov r10, rcx
	mov eax, sciGdiXFORMOBJ_iGetXform
	syscall
	ret
HcGdiXFORMOBJ_iGetXform ENDP

ELSE
; 32bit

EXTERNDEF C sciGdiXFORMOBJ_iGetXform:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGdiXFORMOBJ_iGetXform PROC
	mov eax, sciGdiXFORMOBJ_iGetXform
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGdiXFORMOBJ_iGetXform ENDP

ENDIF

END