; Hc/NtGetDevicePowerState
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciGetDevicePowerState:DWORD

.DATA
.CODE

HcGetDevicePowerState PROC
	mov r10, rcx
	mov eax, sciGetDevicePowerState
	syscall
	ret
HcGetDevicePowerState ENDP

ELSE
; 32bit

EXTERNDEF C sciGetDevicePowerState:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcGetDevicePowerState PROC
	mov eax, sciGetDevicePowerState
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcGetDevicePowerState ENDP

ENDIF

END