; Hc/NtLockRegistryKey
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciLockRegistryKey:DWORD

.DATA
.CODE

HcLockRegistryKey PROC
	mov r10, rcx
	mov eax, sciLockRegistryKey
	syscall
	ret
HcLockRegistryKey ENDP

ELSE
; 32bit

EXTERNDEF C sciLockRegistryKey:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcLockRegistryKey PROC
	mov eax, sciLockRegistryKey
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcLockRegistryKey ENDP

ENDIF

END