; Hc/NtMITBindInputTypeToMonitors
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciMITBindInputTypeToMonitors:DWORD

.DATA
.CODE

HcMITBindInputTypeToMonitors PROC
	mov r10, rcx
	mov eax, sciMITBindInputTypeToMonitors
	syscall
	ret
HcMITBindInputTypeToMonitors ENDP

ELSE
; 32bit

EXTERNDEF C sciMITBindInputTypeToMonitors:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcMITBindInputTypeToMonitors PROC
	mov eax, sciMITBindInputTypeToMonitors
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcMITBindInputTypeToMonitors ENDP

ENDIF

END