; Hc/NtMITDeactivateInputProcessing
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciMITDeactivateInputProcessing:DWORD

.DATA
.CODE

HcMITDeactivateInputProcessing PROC
	mov r10, rcx
	mov eax, sciMITDeactivateInputProcessing
	syscall
	ret
HcMITDeactivateInputProcessing ENDP

ELSE
; 32bit

EXTERNDEF C sciMITDeactivateInputProcessing:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcMITDeactivateInputProcessing PROC
	mov eax, sciMITDeactivateInputProcessing
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcMITDeactivateInputProcessing ENDP

ENDIF

END