; Hc/NtMITDisableMouseIntercept
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciMITDisableMouseIntercept:DWORD

.DATA
.CODE

HcMITDisableMouseIntercept PROC
	mov r10, rcx
	mov eax, sciMITDisableMouseIntercept
	syscall
	ret
HcMITDisableMouseIntercept ENDP

ELSE
; 32bit

EXTERNDEF C sciMITDisableMouseIntercept:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcMITDisableMouseIntercept PROC
	mov eax, sciMITDisableMouseIntercept
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcMITDisableMouseIntercept ENDP

ENDIF

END