; Hc/NtMITSetInputCallbacks
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciMITSetInputCallbacks:DWORD

.DATA
.CODE

HcMITSetInputCallbacks PROC
	mov r10, rcx
	mov eax, sciMITSetInputCallbacks
	syscall
	ret
HcMITSetInputCallbacks ENDP

ELSE
; 32bit

EXTERNDEF C sciMITSetInputCallbacks:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcMITSetInputCallbacks PROC
	mov eax, sciMITSetInputCallbacks
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcMITSetInputCallbacks ENDP

ENDIF

END