; Hc/NtMITSynthesizeMouseInput
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciMITSynthesizeMouseInput:DWORD

.DATA
.CODE

HcMITSynthesizeMouseInput PROC
	mov r10, rcx
	mov eax, sciMITSynthesizeMouseInput
	syscall
	ret
HcMITSynthesizeMouseInput ENDP

ELSE
; 32bit

EXTERNDEF C sciMITSynthesizeMouseInput:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcMITSynthesizeMouseInput PROC
	mov eax, sciMITSynthesizeMouseInput
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcMITSynthesizeMouseInput ENDP

ENDIF

END