; Hc/NtMITSynthesizeTouchInput
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciMITSynthesizeTouchInput:DWORD

.DATA
.CODE

HcMITSynthesizeTouchInput PROC
	mov r10, rcx
	mov eax, sciMITSynthesizeTouchInput
	syscall
	ret
HcMITSynthesizeTouchInput ENDP

ELSE
; 32bit

EXTERNDEF C sciMITSynthesizeTouchInput:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcMITSynthesizeTouchInput PROC
	mov eax, sciMITSynthesizeTouchInput
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcMITSynthesizeTouchInput ENDP

ENDIF

END