; Hc/NtNotifyPresentToCompositionSurface
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciNotifyPresentToCompositionSurface:DWORD

.DATA
.CODE

HcNotifyPresentToCompositionSurface PROC
	mov r10, rcx
	mov eax, sciNotifyPresentToCompositionSurface
	syscall
	ret
HcNotifyPresentToCompositionSurface ENDP

ELSE
; 32bit

EXTERNDEF C sciNotifyPresentToCompositionSurface:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcNotifyPresentToCompositionSurface PROC
	mov eax, sciNotifyPresentToCompositionSurface
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcNotifyPresentToCompositionSurface ENDP

ENDIF

END