; Hc/NtOpenCompositionSurfaceSectionInfo
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciOpenCompositionSurfaceSectionInfo:DWORD

.DATA
.CODE

HcOpenCompositionSurfaceSectionInfo PROC
	mov r10, rcx
	mov eax, sciOpenCompositionSurfaceSectionInfo
	syscall
	ret
HcOpenCompositionSurfaceSectionInfo ENDP

ELSE
; 32bit

EXTERNDEF C sciOpenCompositionSurfaceSectionInfo:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcOpenCompositionSurfaceSectionInfo PROC
	mov eax, sciOpenCompositionSurfaceSectionInfo
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcOpenCompositionSurfaceSectionInfo ENDP

ENDIF

END