; Hc/NtOpenFile
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciOpenFile:DWORD

.DATA
.CODE

HcOpenFile PROC
	mov r10, rcx
	mov eax, sciOpenFile
	syscall
	ret
HcOpenFile ENDP

ELSE
; 32bit

EXTERNDEF C sciOpenFile:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcOpenFile PROC
	mov eax, sciOpenFile
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcOpenFile ENDP

ENDIF

END