; Hc/NtOpenEnlistment
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciOpenEnlistment:DWORD

.DATA
.CODE

HcOpenEnlistment PROC
	mov r10, rcx
	mov eax, sciOpenEnlistment
	syscall
	ret
HcOpenEnlistment ENDP

ELSE
; 32bit

EXTERNDEF C sciOpenEnlistment:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcOpenEnlistment PROC
	mov eax, sciOpenEnlistment
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcOpenEnlistment ENDP

ENDIF

END