; Hc/NtPlugPlayControl
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciPlugPlayControl:DWORD

.DATA
.CODE

HcPlugPlayControl PROC
	mov r10, rcx
	mov eax, sciPlugPlayControl
	syscall
	ret
HcPlugPlayControl ENDP

ELSE
; 32bit

EXTERNDEF C sciPlugPlayControl:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcPlugPlayControl PROC
	mov eax, sciPlugPlayControl
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcPlugPlayControl ENDP

ENDIF

END