; Hc/NtPrePrepareEnlistment
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciPrePrepareEnlistment:DWORD

.DATA
.CODE

HcPrePrepareEnlistment PROC
	mov r10, rcx
	mov eax, sciPrePrepareEnlistment
	syscall
	ret
HcPrePrepareEnlistment ENDP

ELSE
; 32bit

EXTERNDEF C sciPrePrepareEnlistment:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcPrePrepareEnlistment PROC
	mov eax, sciPrePrepareEnlistment
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcPrePrepareEnlistment ENDP

ENDIF

END