; Hc/NtPrivilegedServiceAuditAlarm
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciPrivilegedServiceAuditAlarm:DWORD

.DATA
.CODE

HcPrivilegedServiceAuditAlarm PROC
	mov r10, rcx
	mov eax, sciPrivilegedServiceAuditAlarm
	syscall
	ret
HcPrivilegedServiceAuditAlarm ENDP

ELSE
; 32bit

EXTERNDEF C sciPrivilegedServiceAuditAlarm:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcPrivilegedServiceAuditAlarm PROC
	mov eax, sciPrivilegedServiceAuditAlarm
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcPrivilegedServiceAuditAlarm ENDP

ENDIF

END