; Hc/NtQuerySecurityObject
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciQuerySecurityObject:DWORD

.DATA
.CODE

HcQuerySecurityObject PROC
	mov r10, rcx
	mov eax, sciQuerySecurityObject
	syscall
	ret
HcQuerySecurityObject ENDP

ELSE
; 32bit

EXTERNDEF C sciQuerySecurityObject:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcQuerySecurityObject PROC
	mov eax, sciQuerySecurityObject
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcQuerySecurityObject ENDP

ENDIF

END