; Hc/NtQueryIntervalProfile
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciQueryIntervalProfile:DWORD

.DATA
.CODE

HcQueryIntervalProfile PROC
	mov r10, rcx
	mov eax, sciQueryIntervalProfile
	syscall
	ret
HcQueryIntervalProfile ENDP

ELSE
; 32bit

EXTERNDEF C sciQueryIntervalProfile:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcQueryIntervalProfile PROC
	mov eax, sciQueryIntervalProfile
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcQueryIntervalProfile ENDP

ENDIF

END