; Hc/NtQueryCompositionInputSinkViewId
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciQueryCompositionInputSinkViewId:DWORD

.DATA
.CODE

HcQueryCompositionInputSinkViewId PROC
	mov r10, rcx
	mov eax, sciQueryCompositionInputSinkViewId
	syscall
	ret
HcQueryCompositionInputSinkViewId ENDP

ELSE
; 32bit

EXTERNDEF C sciQueryCompositionInputSinkViewId:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcQueryCompositionInputSinkViewId PROC
	mov eax, sciQueryCompositionInputSinkViewId
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcQueryCompositionInputSinkViewId ENDP

ENDIF

END