; Hc/NtQueryCompositionSurfaceHDRMetaData
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciQueryCompositionSurfaceHDRMetaData:DWORD

.DATA
.CODE

HcQueryCompositionSurfaceHDRMetaData PROC
	mov r10, rcx
	mov eax, sciQueryCompositionSurfaceHDRMetaData
	syscall
	ret
HcQueryCompositionSurfaceHDRMetaData ENDP

ELSE
; 32bit

EXTERNDEF C sciQueryCompositionSurfaceHDRMetaData:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcQueryCompositionSurfaceHDRMetaData PROC
	mov eax, sciQueryCompositionSurfaceHDRMetaData
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcQueryCompositionSurfaceHDRMetaData ENDP

ENDIF

END