; Hc/NtQueryInformationFile
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciQueryInformationFile:DWORD

.DATA
.CODE

HcQueryInformationFile PROC
	mov r10, rcx
	mov eax, sciQueryInformationFile
	syscall
	ret
HcQueryInformationFile ENDP

ELSE
; 32bit

EXTERNDEF C sciQueryInformationFile:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcQueryInformationFile PROC
	mov eax, sciQueryInformationFile
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcQueryInformationFile ENDP

ENDIF

END