; Hc/NtQueryCompositionInputIsImplicit
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciQueryCompositionInputIsImplicit:DWORD

.DATA
.CODE

HcQueryCompositionInputIsImplicit PROC
	mov r10, rcx
	mov eax, sciQueryCompositionInputIsImplicit
	syscall
	ret
HcQueryCompositionInputIsImplicit ENDP

ELSE
; 32bit

EXTERNDEF C sciQueryCompositionInputIsImplicit:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcQueryCompositionInputIsImplicit PROC
	mov eax, sciQueryCompositionInputIsImplicit
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcQueryCompositionInputIsImplicit ENDP

ENDIF

END