; Hc/NtRaiseException
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciRaiseException:DWORD

.DATA
.CODE

HcRaiseException PROC
	mov r10, rcx
	mov eax, sciRaiseException
	syscall
	ret
HcRaiseException ENDP

ELSE
; 32bit

EXTERNDEF C sciRaiseException:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcRaiseException PROC
	mov eax, sciRaiseException
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcRaiseException ENDP

ENDIF

END