; Hc/NtRegisterProtocolAddressInformation
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciRegisterProtocolAddressInformation:DWORD

.DATA
.CODE

HcRegisterProtocolAddressInformation PROC
	mov r10, rcx
	mov eax, sciRegisterProtocolAddressInformation
	syscall
	ret
HcRegisterProtocolAddressInformation ENDP

ELSE
; 32bit

EXTERNDEF C sciRegisterProtocolAddressInformation:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcRegisterProtocolAddressInformation PROC
	mov eax, sciRegisterProtocolAddressInformation
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcRegisterProtocolAddressInformation ENDP

ENDIF

END