; Hc/NtReleaseMutant
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciReleaseMutant:DWORD

.DATA
.CODE

HcReleaseMutant PROC
	mov r10, rcx
	mov eax, sciReleaseMutant
	syscall
	ret
HcReleaseMutant ENDP

ELSE
; 32bit

EXTERNDEF C sciReleaseMutant:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcReleaseMutant PROC
	mov eax, sciReleaseMutant
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcReleaseMutant ENDP

ENDIF

END