; Hc/NtRemoveIoCompletion
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciRemoveIoCompletion:DWORD

.DATA
.CODE

HcRemoveIoCompletion PROC
	mov r10, rcx
	mov eax, sciRemoveIoCompletion
	syscall
	ret
HcRemoveIoCompletion ENDP

ELSE
; 32bit

EXTERNDEF C sciRemoveIoCompletion:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcRemoveIoCompletion PROC
	mov eax, sciRemoveIoCompletion
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcRemoveIoCompletion ENDP

ENDIF

END