; Hc/NtReplyWaitReceivePort
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciReplyWaitReceivePort:DWORD

.DATA
.CODE

HcReplyWaitReceivePort PROC
	mov r10, rcx
	mov eax, sciReplyWaitReceivePort
	syscall
	ret
HcReplyWaitReceivePort ENDP

ELSE
; 32bit

EXTERNDEF C sciReplyWaitReceivePort:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcReplyWaitReceivePort PROC
	mov eax, sciReplyWaitReceivePort
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcReplyWaitReceivePort ENDP

ENDIF

END