; Hc/NtRIMAreSiblingDevices
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciRIMAreSiblingDevices:DWORD

.DATA
.CODE

HcRIMAreSiblingDevices PROC
	mov r10, rcx
	mov eax, sciRIMAreSiblingDevices
	syscall
	ret
HcRIMAreSiblingDevices ENDP

ELSE
; 32bit

EXTERNDEF C sciRIMAreSiblingDevices:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcRIMAreSiblingDevices PROC
	mov eax, sciRIMAreSiblingDevices
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcRIMAreSiblingDevices ENDP

ENDIF

END