; Hc/NtRIMAddInputObserver
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciRIMAddInputObserver:DWORD

.DATA
.CODE

HcRIMAddInputObserver PROC
	mov r10, rcx
	mov eax, sciRIMAddInputObserver
	syscall
	ret
HcRIMAddInputObserver ENDP

ELSE
; 32bit

EXTERNDEF C sciRIMAddInputObserver:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcRIMAddInputObserver PROC
	mov eax, sciRIMAddInputObserver
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcRIMAddInputObserver ENDP

ENDIF

END