; Hc/NtRIMGetDevicePreparsedData
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciRIMGetDevicePreparsedData:DWORD

.DATA
.CODE

HcRIMGetDevicePreparsedData PROC
	mov r10, rcx
	mov eax, sciRIMGetDevicePreparsedData
	syscall
	ret
HcRIMGetDevicePreparsedData ENDP

ELSE
; 32bit

EXTERNDEF C sciRIMGetDevicePreparsedData:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcRIMGetDevicePreparsedData PROC
	mov eax, sciRIMGetDevicePreparsedData
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcRIMGetDevicePreparsedData ENDP

ENDIF

END