; Hc/NtRIMReadInput
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciRIMReadInput:DWORD

.DATA
.CODE

HcRIMReadInput PROC
	mov r10, rcx
	mov eax, sciRIMReadInput
	syscall
	ret
HcRIMReadInput ENDP

ELSE
; 32bit

EXTERNDEF C sciRIMReadInput:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcRIMReadInput PROC
	mov eax, sciRIMReadInput
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcRIMReadInput ENDP

ENDIF

END