; Hc/NtRIMSetTestModeStatus
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciRIMSetTestModeStatus:DWORD

.DATA
.CODE

HcRIMSetTestModeStatus PROC
	mov r10, rcx
	mov eax, sciRIMSetTestModeStatus
	syscall
	ret
HcRIMSetTestModeStatus ENDP

ELSE
; 32bit

EXTERNDEF C sciRIMSetTestModeStatus:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcRIMSetTestModeStatus PROC
	mov eax, sciRIMSetTestModeStatus
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcRIMSetTestModeStatus ENDP

ENDIF

END