; Hc/NtRollbackEnlistment
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciRollbackEnlistment:DWORD

.DATA
.CODE

HcRollbackEnlistment PROC
	mov r10, rcx
	mov eax, sciRollbackEnlistment
	syscall
	ret
HcRollbackEnlistment ENDP

ELSE
; 32bit

EXTERNDEF C sciRollbackEnlistment:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcRollbackEnlistment PROC
	mov eax, sciRollbackEnlistment
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcRollbackEnlistment ENDP

ENDIF

END