; Hc/NtSetCompositionSurfaceBufferCompositionModeAndOrientation
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciSetCompositionSurfaceBufferCompositionModeAndOrientation:DWORD

.DATA
.CODE

HcSetCompositionSurfaceBufferCompositionModeAndOrientation PROC
	mov r10, rcx
	mov eax, sciSetCompositionSurfaceBufferCompositionModeAndOrientation
	syscall
	ret
HcSetCompositionSurfaceBufferCompositionModeAndOrientation ENDP

ELSE
; 32bit

EXTERNDEF C sciSetCompositionSurfaceBufferCompositionModeAndOrientation:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcSetCompositionSurfaceBufferCompositionModeAndOrientation PROC
	mov eax, sciSetCompositionSurfaceBufferCompositionModeAndOrientation
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcSetCompositionSurfaceBufferCompositionModeAndOrientation ENDP

ENDIF

END