; Hc/NtSetCompositionSurfaceStatistics
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciSetCompositionSurfaceStatistics:DWORD

.DATA
.CODE

HcSetCompositionSurfaceStatistics PROC
	mov r10, rcx
	mov eax, sciSetCompositionSurfaceStatistics
	syscall
	ret
HcSetCompositionSurfaceStatistics ENDP

ELSE
; 32bit

EXTERNDEF C sciSetCompositionSurfaceStatistics:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcSetCompositionSurfaceStatistics PROC
	mov eax, sciSetCompositionSurfaceStatistics
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcSetCompositionSurfaceStatistics ENDP

ENDIF

END