; Hc/NtSetCachedSigningLevel
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciSetCachedSigningLevel:DWORD

.DATA
.CODE

HcSetCachedSigningLevel PROC
	mov r10, rcx
	mov eax, sciSetCachedSigningLevel
	syscall
	ret
HcSetCachedSigningLevel ENDP

ELSE
; 32bit

EXTERNDEF C sciSetCachedSigningLevel:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcSetCachedSigningLevel PROC
	mov eax, sciSetCachedSigningLevel
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcSetCachedSigningLevel ENDP

ENDIF

END