; Hc/NtSetCompositionSurfaceDirectFlipState
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciSetCompositionSurfaceDirectFlipState:DWORD

.DATA
.CODE

HcSetCompositionSurfaceDirectFlipState PROC
	mov r10, rcx
	mov eax, sciSetCompositionSurfaceDirectFlipState
	syscall
	ret
HcSetCompositionSurfaceDirectFlipState ENDP

ELSE
; 32bit

EXTERNDEF C sciSetCompositionSurfaceDirectFlipState:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcSetCompositionSurfaceDirectFlipState PROC
	mov eax, sciSetCompositionSurfaceDirectFlipState
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcSetCompositionSurfaceDirectFlipState ENDP

ENDIF

END