; Hc/NtSetDefaultLocale
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciSetDefaultLocale:DWORD

.DATA
.CODE

HcSetDefaultLocale PROC
	mov r10, rcx
	mov eax, sciSetDefaultLocale
	syscall
	ret
HcSetDefaultLocale ENDP

ELSE
; 32bit

EXTERNDEF C sciSetDefaultLocale:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcSetDefaultLocale PROC
	mov eax, sciSetDefaultLocale
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcSetDefaultLocale ENDP

ENDIF

END