; Hc/NtSetHighWaitLowEventPair
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciSetHighWaitLowEventPair:DWORD

.DATA
.CODE

HcSetHighWaitLowEventPair PROC
	mov r10, rcx
	mov eax, sciSetHighWaitLowEventPair
	syscall
	ret
HcSetHighWaitLowEventPair ENDP

ELSE
; 32bit

EXTERNDEF C sciSetHighWaitLowEventPair:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcSetHighWaitLowEventPair PROC
	mov eax, sciSetHighWaitLowEventPair
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcSetHighWaitLowEventPair ENDP

ENDIF

END