; Hc/NtSetInformationResourceManager
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciSetInformationResourceManager:DWORD

.DATA
.CODE

HcSetInformationResourceManager PROC
	mov r10, rcx
	mov eax, sciSetInformationResourceManager
	syscall
	ret
HcSetInformationResourceManager ENDP

ELSE
; 32bit

EXTERNDEF C sciSetInformationResourceManager:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcSetInformationResourceManager PROC
	mov eax, sciSetInformationResourceManager
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcSetInformationResourceManager ENDP

ENDIF

END