; Hc/NtSetTimer2
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciSetTimer2:DWORD

.DATA
.CODE

HcSetTimer2 PROC
	mov r10, rcx
	mov eax, sciSetTimer2
	syscall
	ret
HcSetTimer2 ENDP

ELSE
; 32bit

EXTERNDEF C sciSetTimer2:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcSetTimer2 PROC
	mov eax, sciSetTimer2
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcSetTimer2 ENDP

ENDIF

END