; Hc/NtSetWnfProcessNotificationEvent
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciSetWnfProcessNotificationEvent:DWORD

.DATA
.CODE

HcSetWnfProcessNotificationEvent PROC
	mov r10, rcx
	mov eax, sciSetWnfProcessNotificationEvent
	syscall
	ret
HcSetWnfProcessNotificationEvent ENDP

ELSE
; 32bit

EXTERNDEF C sciSetWnfProcessNotificationEvent:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcSetWnfProcessNotificationEvent PROC
	mov eax, sciSetWnfProcessNotificationEvent
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcSetWnfProcessNotificationEvent ENDP

ENDIF

END