; Hc/NtThawRegistry
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciThawRegistry:DWORD

.DATA
.CODE

HcThawRegistry PROC
	mov r10, rcx
	mov eax, sciThawRegistry
	syscall
	ret
HcThawRegistry ENDP

ELSE
; 32bit

EXTERNDEF C sciThawRegistry:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcThawRegistry PROC
	mov eax, sciThawRegistry
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcThawRegistry ENDP

ENDIF

END