; Hc/NtTokenManagerConfirmOutstandingAnalogToken
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciTokenManagerConfirmOutstandingAnalogToken:DWORD

.DATA
.CODE

HcTokenManagerConfirmOutstandingAnalogToken PROC
	mov r10, rcx
	mov eax, sciTokenManagerConfirmOutstandingAnalogToken
	syscall
	ret
HcTokenManagerConfirmOutstandingAnalogToken ENDP

ELSE
; 32bit

EXTERNDEF C sciTokenManagerConfirmOutstandingAnalogToken:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcTokenManagerConfirmOutstandingAnalogToken PROC
	mov eax, sciTokenManagerConfirmOutstandingAnalogToken
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcTokenManagerConfirmOutstandingAnalogToken ENDP

ENDIF

END