; Hc/NtTokenManagerGetOutOfFrameDirectFlipSurfaceUpdates
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciTokenManagerGetOutOfFrameDirectFlipSurfaceUpdates:DWORD

.DATA
.CODE

HcTokenManagerGetOutOfFrameDirectFlipSurfaceUpdates PROC
	mov r10, rcx
	mov eax, sciTokenManagerGetOutOfFrameDirectFlipSurfaceUpdates
	syscall
	ret
HcTokenManagerGetOutOfFrameDirectFlipSurfaceUpdates ENDP

ELSE
; 32bit

EXTERNDEF C sciTokenManagerGetOutOfFrameDirectFlipSurfaceUpdates:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcTokenManagerGetOutOfFrameDirectFlipSurfaceUpdates PROC
	mov eax, sciTokenManagerGetOutOfFrameDirectFlipSurfaceUpdates
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcTokenManagerGetOutOfFrameDirectFlipSurfaceUpdates ENDP

ENDIF

END