; Hc/NtTokenManagerOpenEvent
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciTokenManagerOpenEvent:DWORD

.DATA
.CODE

HcTokenManagerOpenEvent PROC
	mov r10, rcx
	mov eax, sciTokenManagerOpenEvent
	syscall
	ret
HcTokenManagerOpenEvent ENDP

ELSE
; 32bit

EXTERNDEF C sciTokenManagerOpenEvent:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcTokenManagerOpenEvent PROC
	mov eax, sciTokenManagerOpenEvent
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcTokenManagerOpenEvent ENDP

ENDIF

END