; Hc/NtUnloadDriver
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUnloadDriver:DWORD

.DATA
.CODE

HcUnloadDriver PROC
	mov r10, rcx
	mov eax, sciUnloadDriver
	syscall
	ret
HcUnloadDriver ENDP

ELSE
; 32bit

EXTERNDEF C sciUnloadDriver:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUnloadDriver PROC
	mov eax, sciUnloadDriver
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUnloadDriver ENDP

ENDIF

END