; Hc/NtUnmapViewOfSectionEx
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUnmapViewOfSectionEx:DWORD

.DATA
.CODE

HcUnmapViewOfSectionEx PROC
	mov r10, rcx
	mov eax, sciUnmapViewOfSectionEx
	syscall
	ret
HcUnmapViewOfSectionEx ENDP

ELSE
; 32bit

EXTERNDEF C sciUnmapViewOfSectionEx:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUnmapViewOfSectionEx PROC
	mov eax, sciUnmapViewOfSectionEx
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUnmapViewOfSectionEx ENDP

ENDIF

END