; Hc/NtUpdateWnfStateData
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUpdateWnfStateData:DWORD

.DATA
.CODE

HcUpdateWnfStateData PROC
	mov r10, rcx
	mov eax, sciUpdateWnfStateData
	syscall
	ret
HcUpdateWnfStateData ENDP

ELSE
; 32bit

EXTERNDEF C sciUpdateWnfStateData:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUpdateWnfStateData PROC
	mov eax, sciUpdateWnfStateData
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUpdateWnfStateData ENDP

ENDIF

END