; Hc/NtUserBeginLayoutUpdate
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserBeginLayoutUpdate:DWORD

.DATA
.CODE

HcUserBeginLayoutUpdate PROC
	mov r10, rcx
	mov eax, sciUserBeginLayoutUpdate
	syscall
	ret
HcUserBeginLayoutUpdate ENDP

ELSE
; 32bit

EXTERNDEF C sciUserBeginLayoutUpdate:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserBeginLayoutUpdate PROC
	mov eax, sciUserBeginLayoutUpdate
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserBeginLayoutUpdate ENDP

ENDIF

END