; Hc/NtUserSetWindowCompositionAttribute
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserSetWindowCompositionAttribute:DWORD

.DATA
.CODE

HcUserSetWindowCompositionAttribute PROC
	mov r10, rcx
	mov eax, sciUserSetWindowCompositionAttribute
	syscall
	ret
HcUserSetWindowCompositionAttribute ENDP

ELSE
; 32bit

EXTERNDEF C sciUserSetWindowCompositionAttribute:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserSetWindowCompositionAttribute PROC
	mov eax, sciUserSetWindowCompositionAttribute
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserSetWindowCompositionAttribute ENDP

ENDIF

END