; Hc/NtUserLockWorkStation
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserLockWorkStation:DWORD

.DATA
.CODE

HcUserLockWorkStation PROC
	mov r10, rcx
	mov eax, sciUserLockWorkStation
	syscall
	ret
HcUserLockWorkStation ENDP

ELSE
; 32bit

EXTERNDEF C sciUserLockWorkStation:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserLockWorkStation PROC
	mov eax, sciUserLockWorkStation
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserLockWorkStation ENDP

ENDIF

END