; Hc/NtUserBuildHwndList
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserBuildHwndList:DWORD

.DATA
.CODE

HcUserBuildHwndList PROC
	mov r10, rcx
	mov eax, sciUserBuildHwndList
	syscall
	ret
HcUserBuildHwndList ENDP

ELSE
; 32bit

EXTERNDEF C sciUserBuildHwndList:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserBuildHwndList PROC
	mov eax, sciUserBuildHwndList
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserBuildHwndList ENDP

ENDIF

END