; Hc/NtUserCalcMenuBar
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserCalcMenuBar:DWORD

.DATA
.CODE

HcUserCalcMenuBar PROC
	mov r10, rcx
	mov eax, sciUserCalcMenuBar
	syscall
	ret
HcUserCalcMenuBar ENDP

ELSE
; 32bit

EXTERNDEF C sciUserCalcMenuBar:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserCalcMenuBar PROC
	mov eax, sciUserCalcMenuBar
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserCalcMenuBar ENDP

ENDIF

END