; Hc/NtUserGetDpiForCurrentProcess
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserGetDpiForCurrentProcess:DWORD

.DATA
.CODE

HcUserGetDpiForCurrentProcess PROC
	mov r10, rcx
	mov eax, sciUserGetDpiForCurrentProcess
	syscall
	ret
HcUserGetDpiForCurrentProcess ENDP

ELSE
; 32bit

EXTERNDEF C sciUserGetDpiForCurrentProcess:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserGetDpiForCurrentProcess PROC
	mov eax, sciUserGetDpiForCurrentProcess
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserGetDpiForCurrentProcess ENDP

ENDIF

END