; Hc/NtUserValidateTimerCallback
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserValidateTimerCallback:DWORD

.DATA
.CODE

HcUserValidateTimerCallback PROC
	mov r10, rcx
	mov eax, sciUserValidateTimerCallback
	syscall
	ret
HcUserValidateTimerCallback ENDP

ELSE
; 32bit

EXTERNDEF C sciUserValidateTimerCallback:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserValidateTimerCallback PROC
	mov eax, sciUserValidateTimerCallback
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserValidateTimerCallback ENDP

ENDIF

END