; Hc/NtUserLockWindowUpdate
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserLockWindowUpdate:DWORD

.DATA
.CODE

HcUserLockWindowUpdate PROC
	mov r10, rcx
	mov eax, sciUserLockWindowUpdate
	syscall
	ret
HcUserLockWindowUpdate ENDP

ELSE
; 32bit

EXTERNDEF C sciUserLockWindowUpdate:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserLockWindowUpdate PROC
	mov eax, sciUserLockWindowUpdate
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserLockWindowUpdate ENDP

ENDIF

END