; Hc/NtUserInjectMouseInput
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserInjectMouseInput:DWORD

.DATA
.CODE

HcUserInjectMouseInput PROC
	mov r10, rcx
	mov eax, sciUserInjectMouseInput
	syscall
	ret
HcUserInjectMouseInput ENDP

ELSE
; 32bit

EXTERNDEF C sciUserInjectMouseInput:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserInjectMouseInput PROC
	mov eax, sciUserInjectMouseInput
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserInjectMouseInput ENDP

ENDIF

END