; Hc/NtUserLogicalToPerMonitorDPIPhysicalPoint
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserLogicalToPerMonitorDPIPhysicalPoint:DWORD

.DATA
.CODE

HcUserLogicalToPerMonitorDPIPhysicalPoint PROC
	mov r10, rcx
	mov eax, sciUserLogicalToPerMonitorDPIPhysicalPoint
	syscall
	ret
HcUserLogicalToPerMonitorDPIPhysicalPoint ENDP

ELSE
; 32bit

EXTERNDEF C sciUserLogicalToPerMonitorDPIPhysicalPoint:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserLogicalToPerMonitorDPIPhysicalPoint PROC
	mov eax, sciUserLogicalToPerMonitorDPIPhysicalPoint
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserLogicalToPerMonitorDPIPhysicalPoint ENDP

ENDIF

END