; Hc/NtUserBitBltSysBmp
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserBitBltSysBmp:DWORD

.DATA
.CODE

HcUserBitBltSysBmp PROC
	mov r10, rcx
	mov eax, sciUserBitBltSysBmp
	syscall
	ret
HcUserBitBltSysBmp ENDP

ELSE
; 32bit

EXTERNDEF C sciUserBitBltSysBmp:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserBitBltSysBmp PROC
	mov eax, sciUserBitBltSysBmp
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserBitBltSysBmp ENDP

ENDIF

END