; Hc/NtUserGetClipboardData
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserGetClipboardData:DWORD

.DATA
.CODE

HcUserGetClipboardData PROC
	mov r10, rcx
	mov eax, sciUserGetClipboardData
	syscall
	ret
HcUserGetClipboardData ENDP

ELSE
; 32bit

EXTERNDEF C sciUserGetClipboardData:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserGetClipboardData PROC
	mov eax, sciUserGetClipboardData
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserGetClipboardData ENDP

ENDIF

END