; Hc/NtUserGetImeInfoEx
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserGetImeInfoEx:DWORD

.DATA
.CODE

HcUserGetImeInfoEx PROC
	mov r10, rcx
	mov eax, sciUserGetImeInfoEx
	syscall
	ret
HcUserGetImeInfoEx ENDP

ELSE
; 32bit

EXTERNDEF C sciUserGetImeInfoEx:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserGetImeInfoEx PROC
	mov eax, sciUserGetImeInfoEx
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserGetImeInfoEx ENDP

ENDIF

END