; Hc/NtUserSetParent
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserSetParent:DWORD

.DATA
.CODE

HcUserSetParent PROC
	mov r10, rcx
	mov eax, sciUserSetParent
	syscall
	ret
HcUserSetParent ENDP

ELSE
; 32bit

EXTERNDEF C sciUserSetParent:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserSetParent PROC
	mov eax, sciUserSetParent
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserSetParent ENDP

ENDIF

END