; Hc/NtUserInitializePointerDeviceInjectionEx
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserInitializePointerDeviceInjectionEx:DWORD

.DATA
.CODE

HcUserInitializePointerDeviceInjectionEx PROC
	mov r10, rcx
	mov eax, sciUserInitializePointerDeviceInjectionEx
	syscall
	ret
HcUserInitializePointerDeviceInjectionEx ENDP

ELSE
; 32bit

EXTERNDEF C sciUserInitializePointerDeviceInjectionEx:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserInitializePointerDeviceInjectionEx PROC
	mov eax, sciUserInitializePointerDeviceInjectionEx
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserInitializePointerDeviceInjectionEx ENDP

ENDIF

END