; Hc/NtUserRegisterTasklist
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserRegisterTasklist:DWORD

.DATA
.CODE

HcUserRegisterTasklist PROC
	mov r10, rcx
	mov eax, sciUserRegisterTasklist
	syscall
	ret
HcUserRegisterTasklist ENDP

ELSE
; 32bit

EXTERNDEF C sciUserRegisterTasklist:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserRegisterTasklist PROC
	mov eax, sciUserRegisterTasklist
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserRegisterTasklist ENDP

ENDIF

END