; Hc/NtUserGetClipboardSequenceNumber
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserGetClipboardSequenceNumber:DWORD

.DATA
.CODE

HcUserGetClipboardSequenceNumber PROC
	mov r10, rcx
	mov eax, sciUserGetClipboardSequenceNumber
	syscall
	ret
HcUserGetClipboardSequenceNumber ENDP

ELSE
; 32bit

EXTERNDEF C sciUserGetClipboardSequenceNumber:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserGetClipboardSequenceNumber PROC
	mov eax, sciUserGetClipboardSequenceNumber
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserGetClipboardSequenceNumber ENDP

ENDIF

END