; Hc/NtUserGetTouchValidationStatus
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserGetTouchValidationStatus:DWORD

.DATA
.CODE

HcUserGetTouchValidationStatus PROC
	mov r10, rcx
	mov eax, sciUserGetTouchValidationStatus
	syscall
	ret
HcUserGetTouchValidationStatus ENDP

ELSE
; 32bit

EXTERNDEF C sciUserGetTouchValidationStatus:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserGetTouchValidationStatus PROC
	mov eax, sciUserGetTouchValidationStatus
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserGetTouchValidationStatus ENDP

ENDIF

END