; Hc/NtUserCreateLocalMemHandle
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserCreateLocalMemHandle:DWORD

.DATA
.CODE

HcUserCreateLocalMemHandle PROC
	mov r10, rcx
	mov eax, sciUserCreateLocalMemHandle
	syscall
	ret
HcUserCreateLocalMemHandle ENDP

ELSE
; 32bit

EXTERNDEF C sciUserCreateLocalMemHandle:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserCreateLocalMemHandle PROC
	mov eax, sciUserCreateLocalMemHandle
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserCreateLocalMemHandle ENDP

ENDIF

END