; Hc/NtUserSetDisplayAutoRotationPreferences
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserSetDisplayAutoRotationPreferences:DWORD

.DATA
.CODE

HcUserSetDisplayAutoRotationPreferences PROC
	mov r10, rcx
	mov eax, sciUserSetDisplayAutoRotationPreferences
	syscall
	ret
HcUserSetDisplayAutoRotationPreferences ENDP

ELSE
; 32bit

EXTERNDEF C sciUserSetDisplayAutoRotationPreferences:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserSetDisplayAutoRotationPreferences PROC
	mov eax, sciUserSetDisplayAutoRotationPreferences
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserSetDisplayAutoRotationPreferences ENDP

ENDIF

END