; Hc/NtUserEmptyClipboard
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserEmptyClipboard:DWORD

.DATA
.CODE

HcUserEmptyClipboard PROC
	mov r10, rcx
	mov eax, sciUserEmptyClipboard
	syscall
	ret
HcUserEmptyClipboard ENDP

ELSE
; 32bit

EXTERNDEF C sciUserEmptyClipboard:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserEmptyClipboard PROC
	mov eax, sciUserEmptyClipboard
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserEmptyClipboard ENDP

ENDIF

END