; Hc/NtUserAcquireIAMKey
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserAcquireIAMKey:DWORD

.DATA
.CODE

HcUserAcquireIAMKey PROC
	mov r10, rcx
	mov eax, sciUserAcquireIAMKey
	syscall
	ret
HcUserAcquireIAMKey ENDP

ELSE
; 32bit

EXTERNDEF C sciUserAcquireIAMKey:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserAcquireIAMKey PROC
	mov eax, sciUserAcquireIAMKey
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserAcquireIAMKey ENDP

ENDIF

END