; Hc/NtUserRegisterServicesProcess
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserRegisterServicesProcess:DWORD

.DATA
.CODE

HcUserRegisterServicesProcess PROC
	mov r10, rcx
	mov eax, sciUserRegisterServicesProcess
	syscall
	ret
HcUserRegisterServicesProcess ENDP

ELSE
; 32bit

EXTERNDEF C sciUserRegisterServicesProcess:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserRegisterServicesProcess PROC
	mov eax, sciUserRegisterServicesProcess
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserRegisterServicesProcess ENDP

ENDIF

END