; Hc/NtUserCallNextHookEx
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserCallNextHookEx:DWORD

.DATA
.CODE

HcUserCallNextHookEx PROC
	mov r10, rcx
	mov eax, sciUserCallNextHookEx
	syscall
	ret
HcUserCallNextHookEx ENDP

ELSE
; 32bit

EXTERNDEF C sciUserCallNextHookEx:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserCallNextHookEx PROC
	mov eax, sciUserCallNextHookEx
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserCallNextHookEx ENDP

ENDIF

END