; Hc/NtUserGetGestureInfo
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserGetGestureInfo:DWORD

.DATA
.CODE

HcUserGetGestureInfo PROC
	mov r10, rcx
	mov eax, sciUserGetGestureInfo
	syscall
	ret
HcUserGetGestureInfo ENDP

ELSE
; 32bit

EXTERNDEF C sciUserGetGestureInfo:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserGetGestureInfo PROC
	mov eax, sciUserGetGestureInfo
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserGetGestureInfo ENDP

ENDIF

END