; Hc/NtUserGetQueueStatusReadonly
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserGetQueueStatusReadonly:DWORD

.DATA
.CODE

HcUserGetQueueStatusReadonly PROC
	mov r10, rcx
	mov eax, sciUserGetQueueStatusReadonly
	syscall
	ret
HcUserGetQueueStatusReadonly ENDP

ELSE
; 32bit

EXTERNDEF C sciUserGetQueueStatusReadonly:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserGetQueueStatusReadonly PROC
	mov eax, sciUserGetQueueStatusReadonly
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserGetQueueStatusReadonly ENDP

ENDIF

END