; Hc/NtUserGetRawInputBuffer
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserGetRawInputBuffer:DWORD

.DATA
.CODE

HcUserGetRawInputBuffer PROC
	mov r10, rcx
	mov eax, sciUserGetRawInputBuffer
	syscall
	ret
HcUserGetRawInputBuffer ENDP

ELSE
; 32bit

EXTERNDEF C sciUserGetRawInputBuffer:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserGetRawInputBuffer PROC
	mov eax, sciUserGetRawInputBuffer
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserGetRawInputBuffer ENDP

ENDIF

END