; Hc/NtUserMNDragLeave
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserMNDragLeave:DWORD

.DATA
.CODE

HcUserMNDragLeave PROC
	mov r10, rcx
	mov eax, sciUserMNDragLeave
	syscall
	ret
HcUserMNDragLeave ENDP

ELSE
; 32bit

EXTERNDEF C sciUserMNDragLeave:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserMNDragLeave PROC
	mov eax, sciUserMNDragLeave
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserMNDragLeave ENDP

ENDIF

END