; Hc/NtUserDrawIconEx
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserDrawIconEx:DWORD

.DATA
.CODE

HcUserDrawIconEx PROC
	mov r10, rcx
	mov eax, sciUserDrawIconEx
	syscall
	ret
HcUserDrawIconEx ENDP

ELSE
; 32bit

EXTERNDEF C sciUserDrawIconEx:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserDrawIconEx PROC
	mov eax, sciUserDrawIconEx
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserDrawIconEx ENDP

ENDIF

END