; Hc/NtUserSetActiveProcessForMonitor
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserSetActiveProcessForMonitor:DWORD

.DATA
.CODE

HcUserSetActiveProcessForMonitor PROC
	mov r10, rcx
	mov eax, sciUserSetActiveProcessForMonitor
	syscall
	ret
HcUserSetActiveProcessForMonitor ENDP

ELSE
; 32bit

EXTERNDEF C sciUserSetActiveProcessForMonitor:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserSetActiveProcessForMonitor PROC
	mov eax, sciUserSetActiveProcessForMonitor
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserSetActiveProcessForMonitor ENDP

ENDIF

END