; Hc/NtUserEnableTouchPad
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserEnableTouchPad:DWORD

.DATA
.CODE

HcUserEnableTouchPad PROC
	mov r10, rcx
	mov eax, sciUserEnableTouchPad
	syscall
	ret
HcUserEnableTouchPad ENDP

ELSE
; 32bit

EXTERNDEF C sciUserEnableTouchPad:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserEnableTouchPad PROC
	mov eax, sciUserEnableTouchPad
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserEnableTouchPad ENDP

ENDIF

END