; Hc/NtUserSetCursorContents
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserSetCursorContents:DWORD

.DATA
.CODE

HcUserSetCursorContents PROC
	mov r10, rcx
	mov eax, sciUserSetCursorContents
	syscall
	ret
HcUserSetCursorContents ENDP

ELSE
; 32bit

EXTERNDEF C sciUserSetCursorContents:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserSetCursorContents PROC
	mov eax, sciUserSetCursorContents
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserSetCursorContents ENDP

ENDIF

END