; Hc/NtUserRegisterPointerInputTarget
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserRegisterPointerInputTarget:DWORD

.DATA
.CODE

HcUserRegisterPointerInputTarget PROC
	mov r10, rcx
	mov eax, sciUserRegisterPointerInputTarget
	syscall
	ret
HcUserRegisterPointerInputTarget ENDP

ELSE
; 32bit

EXTERNDEF C sciUserRegisterPointerInputTarget:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserRegisterPointerInputTarget PROC
	mov eax, sciUserRegisterPointerInputTarget
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserRegisterPointerInputTarget ENDP

ENDIF

END