; Hc/NtUserAlterWindowStyle
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserAlterWindowStyle:DWORD

.DATA
.CODE

HcUserAlterWindowStyle PROC
	mov r10, rcx
	mov eax, sciUserAlterWindowStyle
	syscall
	ret
HcUserAlterWindowStyle ENDP

ELSE
; 32bit

EXTERNDEF C sciUserAlterWindowStyle:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserAlterWindowStyle PROC
	mov eax, sciUserAlterWindowStyle
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserAlterWindowStyle ENDP

ENDIF

END