; Hc/NtUserGetClassInfoEx
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserGetClassInfoEx:DWORD

.DATA
.CODE

HcUserGetClassInfoEx PROC
	mov r10, rcx
	mov eax, sciUserGetClassInfoEx
	syscall
	ret
HcUserGetClassInfoEx ENDP

ELSE
; 32bit

EXTERNDEF C sciUserGetClassInfoEx:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserGetClassInfoEx PROC
	mov eax, sciUserGetClassInfoEx
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserGetClassInfoEx ENDP

ENDIF

END