; Hc/NtUserIsMouseInPointerEnabled
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserIsMouseInPointerEnabled:DWORD

.DATA
.CODE

HcUserIsMouseInPointerEnabled PROC
	mov r10, rcx
	mov eax, sciUserIsMouseInPointerEnabled
	syscall
	ret
HcUserIsMouseInPointerEnabled ENDP

ELSE
; 32bit

EXTERNDEF C sciUserIsMouseInPointerEnabled:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserIsMouseInPointerEnabled PROC
	mov eax, sciUserIsMouseInPointerEnabled
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserIsMouseInPointerEnabled ENDP

ENDIF

END