; Hc/NtUserUpdateWindowTransform
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserUpdateWindowTransform:DWORD

.DATA
.CODE

HcUserUpdateWindowTransform PROC
	mov r10, rcx
	mov eax, sciUserUpdateWindowTransform
	syscall
	ret
HcUserUpdateWindowTransform ENDP

ELSE
; 32bit

EXTERNDEF C sciUserUpdateWindowTransform:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserUpdateWindowTransform PROC
	mov eax, sciUserUpdateWindowTransform
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserUpdateWindowTransform ENDP

ENDIF

END