; Hc/NtUserCompositionInputSinkLuidFromPoint
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserCompositionInputSinkLuidFromPoint:DWORD

.DATA
.CODE

HcUserCompositionInputSinkLuidFromPoint PROC
	mov r10, rcx
	mov eax, sciUserCompositionInputSinkLuidFromPoint
	syscall
	ret
HcUserCompositionInputSinkLuidFromPoint ENDP

ELSE
; 32bit

EXTERNDEF C sciUserCompositionInputSinkLuidFromPoint:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserCompositionInputSinkLuidFromPoint PROC
	mov eax, sciUserCompositionInputSinkLuidFromPoint
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserCompositionInputSinkLuidFromPoint ENDP

ENDIF

END