; Hc/NtUserGetProcessDpiAwareness
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserGetProcessDpiAwareness:DWORD

.DATA
.CODE

HcUserGetProcessDpiAwareness PROC
	mov r10, rcx
	mov eax, sciUserGetProcessDpiAwareness
	syscall
	ret
HcUserGetProcessDpiAwareness ENDP

ELSE
; 32bit

EXTERNDEF C sciUserGetProcessDpiAwareness:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserGetProcessDpiAwareness PROC
	mov eax, sciUserGetProcessDpiAwareness
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserGetProcessDpiAwareness ENDP

ENDIF

END