; Hc/NtUserGetOpenClipboardWindow
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserGetOpenClipboardWindow:DWORD

.DATA
.CODE

HcUserGetOpenClipboardWindow PROC
	mov r10, rcx
	mov eax, sciUserGetOpenClipboardWindow
	syscall
	ret
HcUserGetOpenClipboardWindow ENDP

ELSE
; 32bit

EXTERNDEF C sciUserGetOpenClipboardWindow:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserGetOpenClipboardWindow PROC
	mov eax, sciUserGetOpenClipboardWindow
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserGetOpenClipboardWindow ENDP

ENDIF

END