; Hc/NtUserDwmGetDxRgn
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserDwmGetDxRgn:DWORD

.DATA
.CODE

HcUserDwmGetDxRgn PROC
	mov r10, rcx
	mov eax, sciUserDwmGetDxRgn
	syscall
	ret
HcUserDwmGetDxRgn ENDP

ELSE
; 32bit

EXTERNDEF C sciUserDwmGetDxRgn:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserDwmGetDxRgn PROC
	mov eax, sciUserDwmGetDxRgn
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserDwmGetDxRgn ENDP

ENDIF

END