; Hc/NtUserDefSetText
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserDefSetText:DWORD

.DATA
.CODE

HcUserDefSetText PROC
	mov r10, rcx
	mov eax, sciUserDefSetText
	syscall
	ret
HcUserDefSetText ENDP

ELSE
; 32bit

EXTERNDEF C sciUserDefSetText:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserDefSetText PROC
	mov eax, sciUserDefSetText
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserDefSetText ENDP

ENDIF

END