; Hc/NtUserRegisterBSDRWindow
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserRegisterBSDRWindow:DWORD

.DATA
.CODE

HcUserRegisterBSDRWindow PROC
	mov r10, rcx
	mov eax, sciUserRegisterBSDRWindow
	syscall
	ret
HcUserRegisterBSDRWindow ENDP

ELSE
; 32bit

EXTERNDEF C sciUserRegisterBSDRWindow:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserRegisterBSDRWindow PROC
	mov eax, sciUserRegisterBSDRWindow
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserRegisterBSDRWindow ENDP

ENDIF

END