; Hc/NtUserManageGestureHandlerWindow
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserManageGestureHandlerWindow:DWORD

.DATA
.CODE

HcUserManageGestureHandlerWindow PROC
	mov r10, rcx
	mov eax, sciUserManageGestureHandlerWindow
	syscall
	ret
HcUserManageGestureHandlerWindow ENDP

ELSE
; 32bit

EXTERNDEF C sciUserManageGestureHandlerWindow:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserManageGestureHandlerWindow PROC
	mov eax, sciUserManageGestureHandlerWindow
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserManageGestureHandlerWindow ENDP

ENDIF

END