; Hc/NtUserSetConsoleReserveKeys
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserSetConsoleReserveKeys:DWORD

.DATA
.CODE

HcUserSetConsoleReserveKeys PROC
	mov r10, rcx
	mov eax, sciUserSetConsoleReserveKeys
	syscall
	ret
HcUserSetConsoleReserveKeys ENDP

ELSE
; 32bit

EXTERNDEF C sciUserSetConsoleReserveKeys:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserSetConsoleReserveKeys PROC
	mov eax, sciUserSetConsoleReserveKeys
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserSetConsoleReserveKeys ENDP

ENDIF

END