; Hc/NtUserPeekMessage
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserPeekMessage:DWORD

.DATA
.CODE

HcUserPeekMessage PROC
	mov r10, rcx
	mov eax, sciUserPeekMessage
	syscall
	ret
HcUserPeekMessage ENDP

ELSE
; 32bit

EXTERNDEF C sciUserPeekMessage:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserPeekMessage PROC
	mov eax, sciUserPeekMessage
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserPeekMessage ENDP

ENDIF

END