; Hc/NtUserIsTouchWindow
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserIsTouchWindow:DWORD

.DATA
.CODE

HcUserIsTouchWindow PROC
	mov r10, rcx
	mov eax, sciUserIsTouchWindow
	syscall
	ret
HcUserIsTouchWindow ENDP

ELSE
; 32bit

EXTERNDEF C sciUserIsTouchWindow:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserIsTouchWindow PROC
	mov eax, sciUserIsTouchWindow
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserIsTouchWindow ENDP

ENDIF

END