; Hc/NtUserGetPointerDeviceProperties
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserGetPointerDeviceProperties:DWORD

.DATA
.CODE

HcUserGetPointerDeviceProperties PROC
	mov r10, rcx
	mov eax, sciUserGetPointerDeviceProperties
	syscall
	ret
HcUserGetPointerDeviceProperties ENDP

ELSE
; 32bit

EXTERNDEF C sciUserGetPointerDeviceProperties:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserGetPointerDeviceProperties PROC
	mov eax, sciUserGetPointerDeviceProperties
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserGetPointerDeviceProperties ENDP

ENDIF

END