; Hc/NtUserHwndQueryRedirectionInfo
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserHwndQueryRedirectionInfo:DWORD

.DATA
.CODE

HcUserHwndQueryRedirectionInfo PROC
	mov r10, rcx
	mov eax, sciUserHwndQueryRedirectionInfo
	syscall
	ret
HcUserHwndQueryRedirectionInfo ENDP

ELSE
; 32bit

EXTERNDEF C sciUserHwndQueryRedirectionInfo:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserHwndQueryRedirectionInfo PROC
	mov eax, sciUserHwndQueryRedirectionInfo
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserHwndQueryRedirectionInfo ENDP

ENDIF

END