; Hc/NtUserEndMenu
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserEndMenu:DWORD

.DATA
.CODE

HcUserEndMenu PROC
	mov r10, rcx
	mov eax, sciUserEndMenu
	syscall
	ret
HcUserEndMenu ENDP

ELSE
; 32bit

EXTERNDEF C sciUserEndMenu:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserEndMenu PROC
	mov eax, sciUserEndMenu
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserEndMenu ENDP

ENDIF

END