; Hc/NtUserAddClipboardFormatListener
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserAddClipboardFormatListener:DWORD

.DATA
.CODE

HcUserAddClipboardFormatListener PROC
	mov r10, rcx
	mov eax, sciUserAddClipboardFormatListener
	syscall
	ret
HcUserAddClipboardFormatListener ENDP

ELSE
; 32bit

EXTERNDEF C sciUserAddClipboardFormatListener:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserAddClipboardFormatListener PROC
	mov eax, sciUserAddClipboardFormatListener
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserAddClipboardFormatListener ENDP

ENDIF

END