; Hc/NtUserSoundSentry
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserSoundSentry:DWORD

.DATA
.CODE

HcUserSoundSentry PROC
	mov r10, rcx
	mov eax, sciUserSoundSentry
	syscall
	ret
HcUserSoundSentry ENDP

ELSE
; 32bit

EXTERNDEF C sciUserSoundSentry:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserSoundSentry PROC
	mov eax, sciUserSoundSentry
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserSoundSentry ENDP

ENDIF

END