; Hc/NtUserGetProcessDpiAwarenessContext
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserGetProcessDpiAwarenessContext:DWORD

.DATA
.CODE

HcUserGetProcessDpiAwarenessContext PROC
	mov r10, rcx
	mov eax, sciUserGetProcessDpiAwarenessContext
	syscall
	ret
HcUserGetProcessDpiAwarenessContext ENDP

ELSE
; 32bit

EXTERNDEF C sciUserGetProcessDpiAwarenessContext:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserGetProcessDpiAwarenessContext PROC
	mov eax, sciUserGetProcessDpiAwarenessContext
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserGetProcessDpiAwarenessContext ENDP

ENDIF

END