; Hc/NtUserInjectGesture
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserInjectGesture:DWORD

.DATA
.CODE

HcUserInjectGesture PROC
	mov r10, rcx
	mov eax, sciUserInjectGesture
	syscall
	ret
HcUserInjectGesture ENDP

ELSE
; 32bit

EXTERNDEF C sciUserInjectGesture:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserInjectGesture PROC
	mov eax, sciUserInjectGesture
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserInjectGesture ENDP

ENDIF

END