; Hc/NtUserSetThreadLayoutHandles
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserSetThreadLayoutHandles:DWORD

.DATA
.CODE

HcUserSetThreadLayoutHandles PROC
	mov r10, rcx
	mov eax, sciUserSetThreadLayoutHandles
	syscall
	ret
HcUserSetThreadLayoutHandles ENDP

ELSE
; 32bit

EXTERNDEF C sciUserSetThreadLayoutHandles:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserSetThreadLayoutHandles PROC
	mov eax, sciUserSetThreadLayoutHandles
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserSetThreadLayoutHandles ENDP

ENDIF

END