; Hc/NtUserUpdateDefaultDesktopThumbnail
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserUpdateDefaultDesktopThumbnail:DWORD

.DATA
.CODE

HcUserUpdateDefaultDesktopThumbnail PROC
	mov r10, rcx
	mov eax, sciUserUpdateDefaultDesktopThumbnail
	syscall
	ret
HcUserUpdateDefaultDesktopThumbnail ENDP

ELSE
; 32bit

EXTERNDEF C sciUserUpdateDefaultDesktopThumbnail:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserUpdateDefaultDesktopThumbnail PROC
	mov eax, sciUserUpdateDefaultDesktopThumbnail
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserUpdateDefaultDesktopThumbnail ENDP

ENDIF

END