; Hc/NtUserInvalidateRgn
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserInvalidateRgn:DWORD

.DATA
.CODE

HcUserInvalidateRgn PROC
	mov r10, rcx
	mov eax, sciUserInvalidateRgn
	syscall
	ret
HcUserInvalidateRgn ENDP

ELSE
; 32bit

EXTERNDEF C sciUserInvalidateRgn:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserInvalidateRgn PROC
	mov eax, sciUserInvalidateRgn
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserInvalidateRgn ENDP

ENDIF

END