; Hc/NtUserMagControl
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserMagControl:DWORD

.DATA
.CODE

HcUserMagControl PROC
	mov r10, rcx
	mov eax, sciUserMagControl
	syscall
	ret
HcUserMagControl ENDP

ELSE
; 32bit

EXTERNDEF C sciUserMagControl:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserMagControl PROC
	mov eax, sciUserMagControl
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserMagControl ENDP

ENDIF

END