; Hc/NtUserGetGestureExtArgs
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserGetGestureExtArgs:DWORD

.DATA
.CODE

HcUserGetGestureExtArgs PROC
	mov r10, rcx
	mov eax, sciUserGetGestureExtArgs
	syscall
	ret
HcUserGetGestureExtArgs ENDP

ELSE
; 32bit

EXTERNDEF C sciUserGetGestureExtArgs:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserGetGestureExtArgs PROC
	mov eax, sciUserGetGestureExtArgs
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserGetGestureExtArgs ENDP

ENDIF

END