; Hc/NtUserRealChildWindowFromPoint
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserRealChildWindowFromPoint:DWORD

.DATA
.CODE

HcUserRealChildWindowFromPoint PROC
	mov r10, rcx
	mov eax, sciUserRealChildWindowFromPoint
	syscall
	ret
HcUserRealChildWindowFromPoint ENDP

ELSE
; 32bit

EXTERNDEF C sciUserRealChildWindowFromPoint:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserRealChildWindowFromPoint PROC
	mov eax, sciUserRealChildWindowFromPoint
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserRealChildWindowFromPoint ENDP

ENDIF

END