; Hc/NtUserScrollDC
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserScrollDC:DWORD

.DATA
.CODE

HcUserScrollDC PROC
	mov r10, rcx
	mov eax, sciUserScrollDC
	syscall
	ret
HcUserScrollDC ENDP

ELSE
; 32bit

EXTERNDEF C sciUserScrollDC:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserScrollDC PROC
	mov eax, sciUserScrollDC
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserScrollDC ENDP

ENDIF

END