; Hc/NtUserShowSystemCursor
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserShowSystemCursor:DWORD

.DATA
.CODE

HcUserShowSystemCursor PROC
	mov r10, rcx
	mov eax, sciUserShowSystemCursor
	syscall
	ret
HcUserShowSystemCursor ENDP

ELSE
; 32bit

EXTERNDEF C sciUserShowSystemCursor:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserShowSystemCursor PROC
	mov eax, sciUserShowSystemCursor
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserShowSystemCursor ENDP

ENDIF

END