; Hc/NtUserGetPrecisionTouchPadConfiguration
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserGetPrecisionTouchPadConfiguration:DWORD

.DATA
.CODE

HcUserGetPrecisionTouchPadConfiguration PROC
	mov r10, rcx
	mov eax, sciUserGetPrecisionTouchPadConfiguration
	syscall
	ret
HcUserGetPrecisionTouchPadConfiguration ENDP

ELSE
; 32bit

EXTERNDEF C sciUserGetPrecisionTouchPadConfiguration:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserGetPrecisionTouchPadConfiguration PROC
	mov eax, sciUserGetPrecisionTouchPadConfiguration
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserGetPrecisionTouchPadConfiguration ENDP

ENDIF

END