; Hc/NtUserGetDCEx
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserGetDCEx:DWORD

.DATA
.CODE

HcUserGetDCEx PROC
	mov r10, rcx
	mov eax, sciUserGetDCEx
	syscall
	ret
HcUserGetDCEx ENDP

ELSE
; 32bit

EXTERNDEF C sciUserGetDCEx:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserGetDCEx PROC
	mov eax, sciUserGetDCEx
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserGetDCEx ENDP

ENDIF

END