; Hc/NtUserGetRawInputData
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserGetRawInputData:DWORD

.DATA
.CODE

HcUserGetRawInputData PROC
	mov r10, rcx
	mov eax, sciUserGetRawInputData
	syscall
	ret
HcUserGetRawInputData ENDP

ELSE
; 32bit

EXTERNDEF C sciUserGetRawInputData:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserGetRawInputData PROC
	mov eax, sciUserGetRawInputData
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserGetRawInputData ENDP

ENDIF

END