; Hc/NtUserSetKeyboardState
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserSetKeyboardState:DWORD

.DATA
.CODE

HcUserSetKeyboardState PROC
	mov r10, rcx
	mov eax, sciUserSetKeyboardState
	syscall
	ret
HcUserSetKeyboardState ENDP

ELSE
; 32bit

EXTERNDEF C sciUserSetKeyboardState:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserSetKeyboardState PROC
	mov eax, sciUserSetKeyboardState
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserSetKeyboardState ENDP

ENDIF

END