; Hc/NtUserInjectTouchInput
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserInjectTouchInput:DWORD

.DATA
.CODE

HcUserInjectTouchInput PROC
	mov r10, rcx
	mov eax, sciUserInjectTouchInput
	syscall
	ret
HcUserInjectTouchInput ENDP

ELSE
; 32bit

EXTERNDEF C sciUserInjectTouchInput:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserInjectTouchInput PROC
	mov eax, sciUserInjectTouchInput
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserInjectTouchInput ENDP

ENDIF

END