; Hc/NtUserGetListBoxInfo
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserGetListBoxInfo:DWORD

.DATA
.CODE

HcUserGetListBoxInfo PROC
	mov r10, rcx
	mov eax, sciUserGetListBoxInfo
	syscall
	ret
HcUserGetListBoxInfo ENDP

ELSE
; 32bit

EXTERNDEF C sciUserGetListBoxInfo:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserGetListBoxInfo PROC
	mov eax, sciUserGetListBoxInfo
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserGetListBoxInfo ENDP

ENDIF

END