; Hc/NtUserCreateAcceleratorTable
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserCreateAcceleratorTable:DWORD

.DATA
.CODE

HcUserCreateAcceleratorTable PROC
	mov r10, rcx
	mov eax, sciUserCreateAcceleratorTable
	syscall
	ret
HcUserCreateAcceleratorTable ENDP

ELSE
; 32bit

EXTERNDEF C sciUserCreateAcceleratorTable:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserCreateAcceleratorTable PROC
	mov eax, sciUserCreateAcceleratorTable
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserCreateAcceleratorTable ENDP

ENDIF

END