; Hc/NtUserRemoteRedrawRectangle
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserRemoteRedrawRectangle:DWORD

.DATA
.CODE

HcUserRemoteRedrawRectangle PROC
	mov r10, rcx
	mov eax, sciUserRemoteRedrawRectangle
	syscall
	ret
HcUserRemoteRedrawRectangle ENDP

ELSE
; 32bit

EXTERNDEF C sciUserRemoteRedrawRectangle:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserRemoteRedrawRectangle PROC
	mov eax, sciUserRemoteRedrawRectangle
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserRemoteRedrawRectangle ENDP

ENDIF

END