; Hc/NtUserGetCursorInfo
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserGetCursorInfo:DWORD

.DATA
.CODE

HcUserGetCursorInfo PROC
	mov r10, rcx
	mov eax, sciUserGetCursorInfo
	syscall
	ret
HcUserGetCursorInfo ENDP

ELSE
; 32bit

EXTERNDEF C sciUserGetCursorInfo:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserGetCursorInfo PROC
	mov eax, sciUserGetCursorInfo
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserGetCursorInfo ENDP

ENDIF

END