; Hc/NtUserGetWOWClass
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserGetWOWClass:DWORD

.DATA
.CODE

HcUserGetWOWClass PROC
	mov r10, rcx
	mov eax, sciUserGetWOWClass
	syscall
	ret
HcUserGetWOWClass ENDP

ELSE
; 32bit

EXTERNDEF C sciUserGetWOWClass:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserGetWOWClass PROC
	mov eax, sciUserGetWOWClass
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserGetWOWClass ENDP

ENDIF

END