; Hc/NtUserEnableScrollBar
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserEnableScrollBar:DWORD

.DATA
.CODE

HcUserEnableScrollBar PROC
	mov r10, rcx
	mov eax, sciUserEnableScrollBar
	syscall
	ret
HcUserEnableScrollBar ENDP

ELSE
; 32bit

EXTERNDEF C sciUserEnableScrollBar:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserEnableScrollBar PROC
	mov eax, sciUserEnableScrollBar
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserEnableScrollBar ENDP

ENDIF

END