; Hc/NtUserSetClassLongPtr
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserSetClassLongPtr:DWORD

.DATA
.CODE

HcUserSetClassLongPtr PROC
	mov r10, rcx
	mov eax, sciUserSetClassLongPtr
	syscall
	ret
HcUserSetClassLongPtr ENDP

ELSE
; 32bit

EXTERNDEF C sciUserSetClassLongPtr:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserSetClassLongPtr PROC
	mov eax, sciUserSetClassLongPtr
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserSetClassLongPtr ENDP

ENDIF

END