; Hc/NtUserGetUpdatedClipboardFormats
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserGetUpdatedClipboardFormats:DWORD

.DATA
.CODE

HcUserGetUpdatedClipboardFormats PROC
	mov r10, rcx
	mov eax, sciUserGetUpdatedClipboardFormats
	syscall
	ret
HcUserGetUpdatedClipboardFormats ENDP

ELSE
; 32bit

EXTERNDEF C sciUserGetUpdatedClipboardFormats:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserGetUpdatedClipboardFormats PROC
	mov eax, sciUserGetUpdatedClipboardFormats
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserGetUpdatedClipboardFormats ENDP

ENDIF

END