; Hc/NtUserGetKeyboardLayoutName
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserGetKeyboardLayoutName:DWORD

.DATA
.CODE

HcUserGetKeyboardLayoutName PROC
	mov r10, rcx
	mov eax, sciUserGetKeyboardLayoutName
	syscall
	ret
HcUserGetKeyboardLayoutName ENDP

ELSE
; 32bit

EXTERNDEF C sciUserGetKeyboardLayoutName:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserGetKeyboardLayoutName PROC
	mov eax, sciUserGetKeyboardLayoutName
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserGetKeyboardLayoutName ENDP

ENDIF

END