; Hc/NtUserGetDisplayConfigBufferSizes
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserGetDisplayConfigBufferSizes:DWORD

.DATA
.CODE

HcUserGetDisplayConfigBufferSizes PROC
	mov r10, rcx
	mov eax, sciUserGetDisplayConfigBufferSizes
	syscall
	ret
HcUserGetDisplayConfigBufferSizes ENDP

ELSE
; 32bit

EXTERNDEF C sciUserGetDisplayConfigBufferSizes:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserGetDisplayConfigBufferSizes PROC
	mov eax, sciUserGetDisplayConfigBufferSizes
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserGetDisplayConfigBufferSizes ENDP

ENDIF

END