; Hc/NtUserAutoPromoteMouseInPointer
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserAutoPromoteMouseInPointer:DWORD

.DATA
.CODE

HcUserAutoPromoteMouseInPointer PROC
	mov r10, rcx
	mov eax, sciUserAutoPromoteMouseInPointer
	syscall
	ret
HcUserAutoPromoteMouseInPointer ENDP

ELSE
; 32bit

EXTERNDEF C sciUserAutoPromoteMouseInPointer:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserAutoPromoteMouseInPointer PROC
	mov eax, sciUserAutoPromoteMouseInPointer
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserAutoPromoteMouseInPointer ENDP

ENDIF

END