; Hc/NtUserIsWindowGDIScaledDpiMessageEnabled
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserIsWindowGDIScaledDpiMessageEnabled:DWORD

.DATA
.CODE

HcUserIsWindowGDIScaledDpiMessageEnabled PROC
	mov r10, rcx
	mov eax, sciUserIsWindowGDIScaledDpiMessageEnabled
	syscall
	ret
HcUserIsWindowGDIScaledDpiMessageEnabled ENDP

ELSE
; 32bit

EXTERNDEF C sciUserIsWindowGDIScaledDpiMessageEnabled:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserIsWindowGDIScaledDpiMessageEnabled PROC
	mov eax, sciUserIsWindowGDIScaledDpiMessageEnabled
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserIsWindowGDIScaledDpiMessageEnabled ENDP

ENDIF

END