; Hc/NtUserGetDpiForMonitor
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserGetDpiForMonitor:DWORD

.DATA
.CODE

HcUserGetDpiForMonitor PROC
	mov r10, rcx
	mov eax, sciUserGetDpiForMonitor
	syscall
	ret
HcUserGetDpiForMonitor ENDP

ELSE
; 32bit

EXTERNDEF C sciUserGetDpiForMonitor:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserGetDpiForMonitor PROC
	mov eax, sciUserGetDpiForMonitor
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserGetDpiForMonitor ENDP

ENDIF

END