; Hc/NtUserDisableThreadIme
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserDisableThreadIme:DWORD

.DATA
.CODE

HcUserDisableThreadIme PROC
	mov r10, rcx
	mov eax, sciUserDisableThreadIme
	syscall
	ret
HcUserDisableThreadIme ENDP

ELSE
; 32bit

EXTERNDEF C sciUserDisableThreadIme:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserDisableThreadIme PROC
	mov eax, sciUserDisableThreadIme
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserDisableThreadIme ENDP

ENDIF

END