; Hc/NtUserIsTopLevelWindow
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserIsTopLevelWindow:DWORD

.DATA
.CODE

HcUserIsTopLevelWindow PROC
	mov r10, rcx
	mov eax, sciUserIsTopLevelWindow
	syscall
	ret
HcUserIsTopLevelWindow ENDP

ELSE
; 32bit

EXTERNDEF C sciUserIsTopLevelWindow:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserIsTopLevelWindow PROC
	mov eax, sciUserIsTopLevelWindow
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserIsTopLevelWindow ENDP

ENDIF

END