; Hc/NtUserDispatchMessage
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserDispatchMessage:DWORD

.DATA
.CODE

HcUserDispatchMessage PROC
	mov r10, rcx
	mov eax, sciUserDispatchMessage
	syscall
	ret
HcUserDispatchMessage ENDP

ELSE
; 32bit

EXTERNDEF C sciUserDispatchMessage:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserDispatchMessage PROC
	mov eax, sciUserDispatchMessage
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserDispatchMessage ENDP

ENDIF

END