; Hc/NtUserSetShellWindowEx
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserSetShellWindowEx:DWORD

.DATA
.CODE

HcUserSetShellWindowEx PROC
	mov r10, rcx
	mov eax, sciUserSetShellWindowEx
	syscall
	ret
HcUserSetShellWindowEx ENDP

ELSE
; 32bit

EXTERNDEF C sciUserSetShellWindowEx:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserSetShellWindowEx PROC
	mov eax, sciUserSetShellWindowEx
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserSetShellWindowEx ENDP

ENDIF

END