; Hc/NtUserSfmDxSetSwapChainBindingStatus
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserSfmDxSetSwapChainBindingStatus:DWORD

.DATA
.CODE

HcUserSfmDxSetSwapChainBindingStatus PROC
	mov r10, rcx
	mov eax, sciUserSfmDxSetSwapChainBindingStatus
	syscall
	ret
HcUserSfmDxSetSwapChainBindingStatus ENDP

ELSE
; 32bit

EXTERNDEF C sciUserSfmDxSetSwapChainBindingStatus:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserSfmDxSetSwapChainBindingStatus PROC
	mov eax, sciUserSfmDxSetSwapChainBindingStatus
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserSfmDxSetSwapChainBindingStatus ENDP

ENDIF

END