; Hc/NtUserSendEventMessage
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserSendEventMessage:DWORD

.DATA
.CODE

HcUserSendEventMessage PROC
	mov r10, rcx
	mov eax, sciUserSendEventMessage
	syscall
	ret
HcUserSendEventMessage ENDP

ELSE
; 32bit

EXTERNDEF C sciUserSendEventMessage:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserSendEventMessage PROC
	mov eax, sciUserSendEventMessage
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserSendEventMessage ENDP

ENDIF

END