; Hc/NtUserEndPaint
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserEndPaint:DWORD

.DATA
.CODE

HcUserEndPaint PROC
	mov r10, rcx
	mov eax, sciUserEndPaint
	syscall
	ret
HcUserEndPaint ENDP

ELSE
; 32bit

EXTERNDEF C sciUserEndPaint:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserEndPaint PROC
	mov eax, sciUserEndPaint
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserEndPaint ENDP

ENDIF

END