; Hc/NtUserToUnicodeEx
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserToUnicodeEx:DWORD

.DATA
.CODE

HcUserToUnicodeEx PROC
	mov r10, rcx
	mov eax, sciUserToUnicodeEx
	syscall
	ret
HcUserToUnicodeEx ENDP

ELSE
; 32bit

EXTERNDEF C sciUserToUnicodeEx:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserToUnicodeEx PROC
	mov eax, sciUserToUnicodeEx
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserToUnicodeEx ENDP

ENDIF

END