; Hc/NtUserBroadcastThemeChangeEvent
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserBroadcastThemeChangeEvent:DWORD

.DATA
.CODE

HcUserBroadcastThemeChangeEvent PROC
	mov r10, rcx
	mov eax, sciUserBroadcastThemeChangeEvent
	syscall
	ret
HcUserBroadcastThemeChangeEvent ENDP

ELSE
; 32bit

EXTERNDEF C sciUserBroadcastThemeChangeEvent:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserBroadcastThemeChangeEvent PROC
	mov eax, sciUserBroadcastThemeChangeEvent
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserBroadcastThemeChangeEvent ENDP

ENDIF

END