; Hc/NtUserSetThreadDesktop
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserSetThreadDesktop:DWORD

.DATA
.CODE

HcUserSetThreadDesktop PROC
	mov r10, rcx
	mov eax, sciUserSetThreadDesktop
	syscall
	ret
HcUserSetThreadDesktop ENDP

ELSE
; 32bit

EXTERNDEF C sciUserSetThreadDesktop:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserSetThreadDesktop PROC
	mov eax, sciUserSetThreadDesktop
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserSetThreadDesktop ENDP

ENDIF

END