; Hc/NtUserInheritWindowMonitor
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserInheritWindowMonitor:DWORD

.DATA
.CODE

HcUserInheritWindowMonitor PROC
	mov r10, rcx
	mov eax, sciUserInheritWindowMonitor
	syscall
	ret
HcUserInheritWindowMonitor ENDP

ELSE
; 32bit

EXTERNDEF C sciUserInheritWindowMonitor:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserInheritWindowMonitor PROC
	mov eax, sciUserInheritWindowMonitor
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserInheritWindowMonitor ENDP

ENDIF

END