; Hc/NtUserShowCaret
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserShowCaret:DWORD

.DATA
.CODE

HcUserShowCaret PROC
	mov r10, rcx
	mov eax, sciUserShowCaret
	syscall
	ret
HcUserShowCaret ENDP

ELSE
; 32bit

EXTERNDEF C sciUserShowCaret:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserShowCaret PROC
	mov eax, sciUserShowCaret
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserShowCaret ENDP

ENDIF

END