; Hc/NtUserRegisterErrorReportingDialog
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserRegisterErrorReportingDialog:DWORD

.DATA
.CODE

HcUserRegisterErrorReportingDialog PROC
	mov r10, rcx
	mov eax, sciUserRegisterErrorReportingDialog
	syscall
	ret
HcUserRegisterErrorReportingDialog ENDP

ELSE
; 32bit

EXTERNDEF C sciUserRegisterErrorReportingDialog:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserRegisterErrorReportingDialog PROC
	mov eax, sciUserRegisterErrorReportingDialog
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserRegisterErrorReportingDialog ENDP

ENDIF

END