; Hc/NtUserResolveDesktop
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserResolveDesktop:DWORD

.DATA
.CODE

HcUserResolveDesktop PROC
	mov r10, rcx
	mov eax, sciUserResolveDesktop
	syscall
	ret
HcUserResolveDesktop ENDP

ELSE
; 32bit

EXTERNDEF C sciUserResolveDesktop:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserResolveDesktop PROC
	mov eax, sciUserResolveDesktop
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserResolveDesktop ENDP

ENDIF

END