; Hc/NtUserIsNonClientDpiScalingEnabled
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserIsNonClientDpiScalingEnabled:DWORD

.DATA
.CODE

HcUserIsNonClientDpiScalingEnabled PROC
	mov r10, rcx
	mov eax, sciUserIsNonClientDpiScalingEnabled
	syscall
	ret
HcUserIsNonClientDpiScalingEnabled ENDP

ELSE
; 32bit

EXTERNDEF C sciUserIsNonClientDpiScalingEnabled:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserIsNonClientDpiScalingEnabled PROC
	mov eax, sciUserIsNonClientDpiScalingEnabled
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserIsNonClientDpiScalingEnabled ENDP

ENDIF

END