; Hc/NtUserActivateKeyboardLayout
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserActivateKeyboardLayout:DWORD

.DATA
.CODE

HcUserActivateKeyboardLayout PROC
	mov r10, rcx
	mov eax, sciUserActivateKeyboardLayout
	syscall
	ret
HcUserActivateKeyboardLayout ENDP

ELSE
; 32bit

EXTERNDEF C sciUserActivateKeyboardLayout:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserActivateKeyboardLayout PROC
	mov eax, sciUserActivateKeyboardLayout
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserActivateKeyboardLayout ENDP

ENDIF

END