; Hc/NtUserHideCaret
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserHideCaret:DWORD

.DATA
.CODE

HcUserHideCaret PROC
	mov r10, rcx
	mov eax, sciUserHideCaret
	syscall
	ret
HcUserHideCaret ENDP

ELSE
; 32bit

EXTERNDEF C sciUserHideCaret:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserHideCaret PROC
	mov eax, sciUserHideCaret
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserHideCaret ENDP

ENDIF

END