; Hc/NtUserDrawMenuBarTemp
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserDrawMenuBarTemp:DWORD

.DATA
.CODE

HcUserDrawMenuBarTemp PROC
	mov r10, rcx
	mov eax, sciUserDrawMenuBarTemp
	syscall
	ret
HcUserDrawMenuBarTemp ENDP

ELSE
; 32bit

EXTERNDEF C sciUserDrawMenuBarTemp:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserDrawMenuBarTemp PROC
	mov eax, sciUserDrawMenuBarTemp
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserDrawMenuBarTemp ENDP

ENDIF

END