; Hc/NtUserFrostCrashedWindow
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserFrostCrashedWindow:DWORD

.DATA
.CODE

HcUserFrostCrashedWindow PROC
	mov r10, rcx
	mov eax, sciUserFrostCrashedWindow
	syscall
	ret
HcUserFrostCrashedWindow ENDP

ELSE
; 32bit

EXTERNDEF C sciUserFrostCrashedWindow:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserFrostCrashedWindow PROC
	mov eax, sciUserFrostCrashedWindow
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserFrostCrashedWindow ENDP

ENDIF

END