; Hc/NtUserGetForegroundWindow
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserGetForegroundWindow:DWORD

.DATA
.CODE

HcUserGetForegroundWindow PROC
	mov r10, rcx
	mov eax, sciUserGetForegroundWindow
	syscall
	ret
HcUserGetForegroundWindow ENDP

ELSE
; 32bit

EXTERNDEF C sciUserGetForegroundWindow:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserGetForegroundWindow PROC
	mov eax, sciUserGetForegroundWindow
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserGetForegroundWindow ENDP

ENDIF

END