; Hc/NtUserSetWindowPos
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserSetWindowPos:DWORD

.DATA
.CODE

HcUserSetWindowPos PROC
	mov r10, rcx
	mov eax, sciUserSetWindowPos
	syscall
	ret
HcUserSetWindowPos ENDP

ELSE
; 32bit

EXTERNDEF C sciUserSetWindowPos:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserSetWindowPos PROC
	mov eax, sciUserSetWindowPos
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserSetWindowPos ENDP

ENDIF

END