; Hc/NtUserSetDisplayMapping
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserSetDisplayMapping:DWORD

.DATA
.CODE

HcUserSetDisplayMapping PROC
	mov r10, rcx
	mov eax, sciUserSetDisplayMapping
	syscall
	ret
HcUserSetDisplayMapping ENDP

ELSE
; 32bit

EXTERNDEF C sciUserSetDisplayMapping:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserSetDisplayMapping PROC
	mov eax, sciUserSetDisplayMapping
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserSetDisplayMapping ENDP

ENDIF

END