; Hc/NtUserUnhookWindowsHookEx
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserUnhookWindowsHookEx:DWORD

.DATA
.CODE

HcUserUnhookWindowsHookEx PROC
	mov r10, rcx
	mov eax, sciUserUnhookWindowsHookEx
	syscall
	ret
HcUserUnhookWindowsHookEx ENDP

ELSE
; 32bit

EXTERNDEF C sciUserUnhookWindowsHookEx:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserUnhookWindowsHookEx PROC
	mov eax, sciUserUnhookWindowsHookEx
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserUnhookWindowsHookEx ENDP

ENDIF

END