; Hc/NtUserMenuItemFromPoint
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserMenuItemFromPoint:DWORD

.DATA
.CODE

HcUserMenuItemFromPoint PROC
	mov r10, rcx
	mov eax, sciUserMenuItemFromPoint
	syscall
	ret
HcUserMenuItemFromPoint ENDP

ELSE
; 32bit

EXTERNDEF C sciUserMenuItemFromPoint:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserMenuItemFromPoint PROC
	mov eax, sciUserMenuItemFromPoint
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserMenuItemFromPoint ENDP

ENDIF

END