; Hc/NtUserGetCurrentInputMessageSource
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserGetCurrentInputMessageSource:DWORD

.DATA
.CODE

HcUserGetCurrentInputMessageSource PROC
	mov r10, rcx
	mov eax, sciUserGetCurrentInputMessageSource
	syscall
	ret
HcUserGetCurrentInputMessageSource ENDP

ELSE
; 32bit

EXTERNDEF C sciUserGetCurrentInputMessageSource:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserGetCurrentInputMessageSource PROC
	mov eax, sciUserGetCurrentInputMessageSource
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserGetCurrentInputMessageSource ENDP

ENDIF

END