; Hc/NtUserSetSystemMenu
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserSetSystemMenu:DWORD

.DATA
.CODE

HcUserSetSystemMenu PROC
	mov r10, rcx
	mov eax, sciUserSetSystemMenu
	syscall
	ret
HcUserSetSystemMenu ENDP

ELSE
; 32bit

EXTERNDEF C sciUserSetSystemMenu:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserSetSystemMenu PROC
	mov eax, sciUserSetSystemMenu
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserSetSystemMenu ENDP

ENDIF

END