; Hc/NtUserWaitForMsgAndEvent
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserWaitForMsgAndEvent:DWORD

.DATA
.CODE

HcUserWaitForMsgAndEvent PROC
	mov r10, rcx
	mov eax, sciUserWaitForMsgAndEvent
	syscall
	ret
HcUserWaitForMsgAndEvent ENDP

ELSE
; 32bit

EXTERNDEF C sciUserWaitForMsgAndEvent:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserWaitForMsgAndEvent PROC
	mov eax, sciUserWaitForMsgAndEvent
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserWaitForMsgAndEvent ENDP

ENDIF

END