; Hc/NtUserLoadKeyboardLayoutEx
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserLoadKeyboardLayoutEx:DWORD

.DATA
.CODE

HcUserLoadKeyboardLayoutEx PROC
	mov r10, rcx
	mov eax, sciUserLoadKeyboardLayoutEx
	syscall
	ret
HcUserLoadKeyboardLayoutEx ENDP

ELSE
; 32bit

EXTERNDEF C sciUserLoadKeyboardLayoutEx:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserLoadKeyboardLayoutEx PROC
	mov eax, sciUserLoadKeyboardLayoutEx
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserLoadKeyboardLayoutEx ENDP

ENDIF

END