; Hc/NtUserLogicalToPhysicalPoint
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserLogicalToPhysicalPoint:DWORD

.DATA
.CODE

HcUserLogicalToPhysicalPoint PROC
	mov r10, rcx
	mov eax, sciUserLogicalToPhysicalPoint
	syscall
	ret
HcUserLogicalToPhysicalPoint ENDP

ELSE
; 32bit

EXTERNDEF C sciUserLogicalToPhysicalPoint:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserLogicalToPhysicalPoint PROC
	mov eax, sciUserLogicalToPhysicalPoint
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserLogicalToPhysicalPoint ENDP

ENDIF

END