; Hc/NtUserCanBrokerForceForeground
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserCanBrokerForceForeground:DWORD

.DATA
.CODE

HcUserCanBrokerForceForeground PROC
	mov r10, rcx
	mov eax, sciUserCanBrokerForceForeground
	syscall
	ret
HcUserCanBrokerForceForeground ENDP

ELSE
; 32bit

EXTERNDEF C sciUserCanBrokerForceForeground:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserCanBrokerForceForeground PROC
	mov eax, sciUserCanBrokerForceForeground
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserCanBrokerForceForeground ENDP

ENDIF

END