; Hc/NtUserOpenWindowStation
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserOpenWindowStation:DWORD

.DATA
.CODE

HcUserOpenWindowStation PROC
	mov r10, rcx
	mov eax, sciUserOpenWindowStation
	syscall
	ret
HcUserOpenWindowStation ENDP

ELSE
; 32bit

EXTERNDEF C sciUserOpenWindowStation:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserOpenWindowStation PROC
	mov eax, sciUserOpenWindowStation
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserOpenWindowStation ENDP

ENDIF

END