; Hc/NtUserQueryInputContext
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserQueryInputContext:DWORD

.DATA
.CODE

HcUserQueryInputContext PROC
	mov r10, rcx
	mov eax, sciUserQueryInputContext
	syscall
	ret
HcUserQueryInputContext ENDP

ELSE
; 32bit

EXTERNDEF C sciUserQueryInputContext:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserQueryInputContext PROC
	mov eax, sciUserQueryInputContext
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserQueryInputContext ENDP

ENDIF

END