; Hc/NtUserGetAncestor
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserGetAncestor:DWORD

.DATA
.CODE

HcUserGetAncestor PROC
	mov r10, rcx
	mov eax, sciUserGetAncestor
	syscall
	ret
HcUserGetAncestor ENDP

ELSE
; 32bit

EXTERNDEF C sciUserGetAncestor:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserGetAncestor PROC
	mov eax, sciUserGetAncestor
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserGetAncestor ENDP

ENDIF

END