; Hc/NtUserValidateHandleSecure
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserValidateHandleSecure:DWORD

.DATA
.CODE

HcUserValidateHandleSecure PROC
	mov r10, rcx
	mov eax, sciUserValidateHandleSecure
	syscall
	ret
HcUserValidateHandleSecure ENDP

ELSE
; 32bit

EXTERNDEF C sciUserValidateHandleSecure:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserValidateHandleSecure PROC
	mov eax, sciUserValidateHandleSecure
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserValidateHandleSecure ENDP

ENDIF

END