; Hc/NtUserInternalGetWindowText
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserInternalGetWindowText:DWORD

.DATA
.CODE

HcUserInternalGetWindowText PROC
	mov r10, rcx
	mov eax, sciUserInternalGetWindowText
	syscall
	ret
HcUserInternalGetWindowText ENDP

ELSE
; 32bit

EXTERNDEF C sciUserInternalGetWindowText:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserInternalGetWindowText PROC
	mov eax, sciUserInternalGetWindowText
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserInternalGetWindowText ENDP

ENDIF

END