; Hc/NtUserInitialize
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserInitialize:DWORD

.DATA
.CODE

HcUserInitialize PROC
	mov r10, rcx
	mov eax, sciUserInitialize
	syscall
	ret
HcUserInitialize ENDP

ELSE
; 32bit

EXTERNDEF C sciUserInitialize:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserInitialize PROC
	mov eax, sciUserInitialize
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserInitialize ENDP

ENDIF

END