; Hc/NtUserGetCPD
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserGetCPD:DWORD

.DATA
.CODE

HcUserGetCPD PROC
	mov r10, rcx
	mov eax, sciUserGetCPD
	syscall
	ret
HcUserGetCPD ENDP

ELSE
; 32bit

EXTERNDEF C sciUserGetCPD:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserGetCPD PROC
	mov eax, sciUserGetCPD
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserGetCPD ENDP

ENDIF

END