; Hc/NtUserSetSensorPresence
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserSetSensorPresence:DWORD

.DATA
.CODE

HcUserSetSensorPresence PROC
	mov r10, rcx
	mov eax, sciUserSetSensorPresence
	syscall
	ret
HcUserSetSensorPresence ENDP

ELSE
; 32bit

EXTERNDEF C sciUserSetSensorPresence:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserSetSensorPresence PROC
	mov eax, sciUserSetSensorPresence
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserSetSensorPresence ENDP

ENDIF

END