; Hc/NtUserAcquireInteractiveControlBackgroundAccess
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserAcquireInteractiveControlBackgroundAccess:DWORD

.DATA
.CODE

HcUserAcquireInteractiveControlBackgroundAccess PROC
	mov r10, rcx
	mov eax, sciUserAcquireInteractiveControlBackgroundAccess
	syscall
	ret
HcUserAcquireInteractiveControlBackgroundAccess ENDP

ELSE
; 32bit

EXTERNDEF C sciUserAcquireInteractiveControlBackgroundAccess:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserAcquireInteractiveControlBackgroundAccess PROC
	mov eax, sciUserAcquireInteractiveControlBackgroundAccess
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserAcquireInteractiveControlBackgroundAccess ENDP

ENDIF

END