; Hc/NtUserOpenInputDesktop
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserOpenInputDesktop:DWORD

.DATA
.CODE

HcUserOpenInputDesktop PROC
	mov r10, rcx
	mov eax, sciUserOpenInputDesktop
	syscall
	ret
HcUserOpenInputDesktop ENDP

ELSE
; 32bit

EXTERNDEF C sciUserOpenInputDesktop:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserOpenInputDesktop PROC
	mov eax, sciUserOpenInputDesktop
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserOpenInputDesktop ENDP

ENDIF

END