; Hc/NtUserRegisterRawInputDevices
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserRegisterRawInputDevices:DWORD

.DATA
.CODE

HcUserRegisterRawInputDevices PROC
	mov r10, rcx
	mov eax, sciUserRegisterRawInputDevices
	syscall
	ret
HcUserRegisterRawInputDevices ENDP

ELSE
; 32bit

EXTERNDEF C sciUserRegisterRawInputDevices:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserRegisterRawInputDevices PROC
	mov eax, sciUserRegisterRawInputDevices
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserRegisterRawInputDevices ENDP

ENDIF

END