; Hc/NtUserSetLayeredWindowAttributes
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserSetLayeredWindowAttributes:DWORD

.DATA
.CODE

HcUserSetLayeredWindowAttributes PROC
	mov r10, rcx
	mov eax, sciUserSetLayeredWindowAttributes
	syscall
	ret
HcUserSetLayeredWindowAttributes ENDP

ELSE
; 32bit

EXTERNDEF C sciUserSetLayeredWindowAttributes:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserSetLayeredWindowAttributes PROC
	mov eax, sciUserSetLayeredWindowAttributes
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserSetLayeredWindowAttributes ENDP

ENDIF

END