; Hc/NtUserSetProcessDPIAware
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserSetProcessDPIAware:DWORD

.DATA
.CODE

HcUserSetProcessDPIAware PROC
	mov r10, rcx
	mov eax, sciUserSetProcessDPIAware
	syscall
	ret
HcUserSetProcessDPIAware ENDP

ELSE
; 32bit

EXTERNDEF C sciUserSetProcessDPIAware:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserSetProcessDPIAware PROC
	mov eax, sciUserSetProcessDPIAware
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserSetProcessDPIAware ENDP

ENDIF

END