; Hc/NtUserTransformPoint
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserTransformPoint:DWORD

.DATA
.CODE

HcUserTransformPoint PROC
	mov r10, rcx
	mov eax, sciUserTransformPoint
	syscall
	ret
HcUserTransformPoint ENDP

ELSE
; 32bit

EXTERNDEF C sciUserTransformPoint:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserTransformPoint PROC
	mov eax, sciUserTransformPoint
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserTransformPoint ENDP

ENDIF

END