; Hc/NtUserGetMenuBarInfo
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserGetMenuBarInfo:DWORD

.DATA
.CODE

HcUserGetMenuBarInfo PROC
	mov r10, rcx
	mov eax, sciUserGetMenuBarInfo
	syscall
	ret
HcUserGetMenuBarInfo ENDP

ELSE
; 32bit

EXTERNDEF C sciUserGetMenuBarInfo:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserGetMenuBarInfo PROC
	mov eax, sciUserGetMenuBarInfo
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserGetMenuBarInfo ENDP

ENDIF

END