; Hc/NtUserSetWindowShowState
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserSetWindowShowState:DWORD

.DATA
.CODE

HcUserSetWindowShowState PROC
	mov r10, rcx
	mov eax, sciUserSetWindowShowState
	syscall
	ret
HcUserSetWindowShowState ENDP

ELSE
; 32bit

EXTERNDEF C sciUserSetWindowShowState:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserSetWindowShowState PROC
	mov eax, sciUserSetWindowShowState
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserSetWindowShowState ENDP

ENDIF

END