; Hc/NtUserChangeDisplaySettings
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserChangeDisplaySettings:DWORD

.DATA
.CODE

HcUserChangeDisplaySettings PROC
	mov r10, rcx
	mov eax, sciUserChangeDisplaySettings
	syscall
	ret
HcUserChangeDisplaySettings ENDP

ELSE
; 32bit

EXTERNDEF C sciUserChangeDisplaySettings:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserChangeDisplaySettings PROC
	mov eax, sciUserChangeDisplaySettings
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserChangeDisplaySettings ENDP

ENDIF

END