; Hc/NtUserCreateDCompositionHwndTarget
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserCreateDCompositionHwndTarget:DWORD

.DATA
.CODE

HcUserCreateDCompositionHwndTarget PROC
	mov r10, rcx
	mov eax, sciUserCreateDCompositionHwndTarget
	syscall
	ret
HcUserCreateDCompositionHwndTarget ENDP

ELSE
; 32bit

EXTERNDEF C sciUserCreateDCompositionHwndTarget:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserCreateDCompositionHwndTarget PROC
	mov eax, sciUserCreateDCompositionHwndTarget
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserCreateDCompositionHwndTarget ENDP

ENDIF

END