; Hc/NtUserEnableWindowGDIScaledDpiMessage
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserEnableWindowGDIScaledDpiMessage:DWORD

.DATA
.CODE

HcUserEnableWindowGDIScaledDpiMessage PROC
	mov r10, rcx
	mov eax, sciUserEnableWindowGDIScaledDpiMessage
	syscall
	ret
HcUserEnableWindowGDIScaledDpiMessage ENDP

ELSE
; 32bit

EXTERNDEF C sciUserEnableWindowGDIScaledDpiMessage:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserEnableWindowGDIScaledDpiMessage PROC
	mov eax, sciUserEnableWindowGDIScaledDpiMessage
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserEnableWindowGDIScaledDpiMessage ENDP

ENDIF

END