; Hc/NtUserGetTopLevelWindow
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserGetTopLevelWindow:DWORD

.DATA
.CODE

HcUserGetTopLevelWindow PROC
	mov r10, rcx
	mov eax, sciUserGetTopLevelWindow
	syscall
	ret
HcUserGetTopLevelWindow ENDP

ELSE
; 32bit

EXTERNDEF C sciUserGetTopLevelWindow:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserGetTopLevelWindow PROC
	mov eax, sciUserGetTopLevelWindow
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserGetTopLevelWindow ENDP

ENDIF

END