; Hc/NtUserReleaseDC
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserReleaseDC:DWORD

.DATA
.CODE

HcUserReleaseDC PROC
	mov r10, rcx
	mov eax, sciUserReleaseDC
	syscall
	ret
HcUserReleaseDC ENDP

ELSE
; 32bit

EXTERNDEF C sciUserReleaseDC:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserReleaseDC PROC
	mov eax, sciUserReleaseDC
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserReleaseDC ENDP

ENDIF

END