; Hc/NtUserGetCaretPos
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserGetCaretPos:DWORD

.DATA
.CODE

HcUserGetCaretPos PROC
	mov r10, rcx
	mov eax, sciUserGetCaretPos
	syscall
	ret
HcUserGetCaretPos ENDP

ELSE
; 32bit

EXTERNDEF C sciUserGetCaretPos:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserGetCaretPos PROC
	mov eax, sciUserGetCaretPos
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserGetCaretPos ENDP

ENDIF

END