; Hc/NtUserVkKeyScanEx
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserVkKeyScanEx:DWORD

.DATA
.CODE

HcUserVkKeyScanEx PROC
	mov r10, rcx
	mov eax, sciUserVkKeyScanEx
	syscall
	ret
HcUserVkKeyScanEx ENDP

ELSE
; 32bit

EXTERNDEF C sciUserVkKeyScanEx:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserVkKeyScanEx PROC
	mov eax, sciUserVkKeyScanEx
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserVkKeyScanEx ENDP

ENDIF

END