; Hc/NtUserIsWindowBroadcastingDpiToChildren
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserIsWindowBroadcastingDpiToChildren:DWORD

.DATA
.CODE

HcUserIsWindowBroadcastingDpiToChildren PROC
	mov r10, rcx
	mov eax, sciUserIsWindowBroadcastingDpiToChildren
	syscall
	ret
HcUserIsWindowBroadcastingDpiToChildren ENDP

ELSE
; 32bit

EXTERNDEF C sciUserIsWindowBroadcastingDpiToChildren:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserIsWindowBroadcastingDpiToChildren PROC
	mov eax, sciUserIsWindowBroadcastingDpiToChildren
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserIsWindowBroadcastingDpiToChildren ENDP

ENDIF

END