; Hc/NtUserSBGetParms
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciUserSBGetParms:DWORD

.DATA
.CODE

HcUserSBGetParms PROC
	mov r10, rcx
	mov eax, sciUserSBGetParms
	syscall
	ret
HcUserSBGetParms ENDP

ELSE
; 32bit

EXTERNDEF C sciUserSBGetParms:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcUserSBGetParms PROC
	mov eax, sciUserSBGetParms
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcUserSBGetParms ENDP

ENDIF

END