; Hc/NtValidateCompositionSurfaceHandle
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciValidateCompositionSurfaceHandle:DWORD

.DATA
.CODE

HcValidateCompositionSurfaceHandle PROC
	mov r10, rcx
	mov eax, sciValidateCompositionSurfaceHandle
	syscall
	ret
HcValidateCompositionSurfaceHandle ENDP

ELSE
; 32bit

EXTERNDEF C sciValidateCompositionSurfaceHandle:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcValidateCompositionSurfaceHandle PROC
	mov eax, sciValidateCompositionSurfaceHandle
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcValidateCompositionSurfaceHandle ENDP

ENDIF

END