; Hc/NtWaitForMultipleObjects32
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciWaitForMultipleObjects32:DWORD

.DATA
.CODE

HcWaitForMultipleObjects32 PROC
	mov r10, rcx
	mov eax, sciWaitForMultipleObjects32
	syscall
	ret
HcWaitForMultipleObjects32 ENDP

ELSE
; 32bit

EXTERNDEF C sciWaitForMultipleObjects32:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcWaitForMultipleObjects32 PROC
	mov eax, sciWaitForMultipleObjects32
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcWaitForMultipleObjects32 ENDP

ENDIF

END