; Hc/NtWaitForKeyedEvent
; This file was automatically generated by Highcall's syscall generator.

IFDEF RAX
; 64bit

EXTERNDEF sciWaitForKeyedEvent:DWORD

.DATA
.CODE

HcWaitForKeyedEvent PROC
	mov r10, rcx
	mov eax, sciWaitForKeyedEvent
	syscall
	ret
HcWaitForKeyedEvent ENDP

ELSE
; 32bit

EXTERNDEF C sciWaitForKeyedEvent:DWORD

.586			  
.MODEL FLAT, C   
.STACK
.DATA
.CODE

ASSUME FS:NOTHING

HcWaitForKeyedEvent PROC
	mov eax, sciWaitForKeyedEvent
	mov ecx, fs:[0c0h]
	test ecx, ecx
	jne _wow64
	lea edx, [esp + 4]
	INT 02eh
	ret
	_wow64:
	xor ecx, ecx
	lea edx, [esp + 4h]
	call dword ptr fs:[0c0h]
	ret
HcWaitForKeyedEvent ENDP

ENDIF

END